### ISSUE TITLE
Hope support Node 18.x

### ISSUE THREAD

**Issue by femonkey** [neon-bindings/neon#1000]
Hope support Node 18.x.
Our team so expect to use it  in new version of electron's develop.Thanks

**Comment by kjvalencik** [comment]
Neon is fully supported in Node 18.

Are you having issues?

**Comment by femonkey** [comment]
sorry，I'm only see the Node version not contain in introduce description.

**Comment by kjvalencik** [comment]
It's supported, the README just hasn't been updated. It includes this text:

> Support for [LTS versions of Node](https://github.com/nodejs/LTS#release-schedule) and current are expected.
