### ISSUE TITLE
Invalid `main` property in generated package.json on Windows

### ISSUE THREAD

**Issue by brodeuralexis** [neon-bindings/neon#103]
On Windows, the path separator "\" must be escaped in JSON.

Use "\\" for path separators on Windows :

``` json
  "main": "lib\index.js"
```

must be 

``` json
  "main": "lib\\index.js"
```

**Comment by kjvalencik** [comment]
I don't think this is still an issue, but if it is it is only relevant to the deprecated `neon-cli`.
