### ISSUE TITLE
Neon fails when having a main.rs file

### ISSUE THREAD

**Issue by paviro** [neon-bindings/neon#1040]
Hi,
My project also builds a CLI tool from main.rs it seems like as soon as a main.rs is present neon fails with

```
> neon dist < cargo.log

error: No artifacts were generated for crate
```

Moving it to main_.rs and then back to main.rs when building with neon works.

Best,
Paul

**Comment by kjvalencik** [comment]
I believe when a crate is both a lib and a bin `cargo` defaults to building the bin. Can you try adding adding `--lib` to the build command?

```
cargo build --lib
```

**Comment by kjvalencik** [comment]
@dherman This might be a bug in the new CLI.

@paviro As a workaround you can make a wrapper crate for the Neon lib that re-exports everything. It will require making the project a workspace.

**Comment by paviro** [comment]
My workaround right now is:
```
cd src && mv main.rs main_.rs && cd .. && 
npm run build
cd src && mv main_.rs main.rs && cd ..
```

Looks ridiculous but works for my case. Thank you for the additional hints though!

**Comment by paviro** [comment]
I am quite new to rust and neon so I am not sure what exactly to test. Could you give me a hint?

**Comment by dherman** [comment]
I can reproduce too! I'll get this fixed asap.

**Comment by dherman** [comment]
Found the culprit. I'll publish a fix soon!

**Comment by dherman** [comment]
@paviro What version of @neon-rs/cli do you have in your package.json? I've published a new version that fixes the issue, and it should work to just update to 0.1.69. But let me know if you have trouble upgrading and I'll be happy to help.

**Comment by dherman** [comment]
(Reopening for now just to make sure it actually works for @paviro.)

**Comment by paviro** [comment]
It does work, thank you so much for the quick fix!

**Comment by tsingwong** [comment]
thanks. update the newest version help me fix the problem.
