### ISSUE TITLE
`npm init -- --app` should create an `"install"` hook

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#1042]
There's no `"install"` hook for `--app` projects created by the new `create-neon`.

**Comment by kjvalencik** [comment]
Should it be `prepare` and exist for both apps and libraries?

**Comment by dherman** [comment]
> Should it be `prepare` and exist for both apps and libraries?

Libraries aren't built on demand, they're built remotely on the CI/CD server across the full platform matrix and the binaries are published separately. The library itself doesn't require any local build process.

For apps, I think you're right that `"prepare"` is the right call.

**Comment by dherman** [comment]
I added this to #1041.

**Comment by kjvalencik** [comment]
The `prepare` hook only runs before a publish. That's not something we want to take advantage of for libs?

**Comment by dherman** [comment]
The `prepare` hook runs both before publish and install. You might be thinking of `prepublishOnly`, which only runs before publish.

For libs, we can't make use of a publish hook because it's synchronous, and libs need to fork a bunch of remote prebuilds running on CI/CD servers. So publishing is actually done via CI/CD instead of locally. But if you can think of a way to do this with an `npm publish` workflow, I'm open to it!

**Comment by kjvalencik** [comment]
Is there some other hook we can use that always gets run when you locally pull for both types?

**Comment by dherman** [comment]
Can you say more? I don't quite know what you mean by locally pull.

**Comment by dherman** [comment]
Followup: based on discussion in #1041, we agreed that this isn't a great idea after all. Rationale:
- There's no npm workflow for "please run this script the first time I set up node_modules".
- It's not great to force a rebuild every time you update a dependency.
- We don't really know how apps will set up their builds, so it's best not to try to guess, and just leave it to them.
- Consistency between both app and lib: if you want to run a local build, do `npm run build`.
