### ISSUE TITLE
cargo-cp-artifact error: "Did not copy cdylib:package" starting with rustc 1.79.0

### ISSUE THREAD

**Issue by adam-coster** [neon-bindings/neon#1049]
I'm using the `cargo-cp-artifact` package to build a simple Rust package called "pixel-checksum".

A few days ago, a daily GitHub workflow that I hadn't touched for a while started failing. My logs showed the error message `Did not copy "cdylib:pixel-checksum"` for the package that was trying to build. Since I hadn't changed anything, I assumed this was due to an update to the default `rustc` version on the GitHub runner.

I didn't get this error locally, but was on an older version of Rust (1.72.0). I updated to latest, and reproduced the error. I then confirmed that no other Rust versions reproduce this error:

- ✅ rustc 1.72.0
- ✅ rustc 1.75.0
- ✅ rustc 1.77.2
- ✅ rustc 1.78.0
- ❌ rustc 1.79.0

I found [this related issue](https://github.com/neon-bindings/neon/issues/818) but it doesn't seem to be applicable. I tried setting my package name to exactly match the crate name, and tried the `-a` parameter, as in that issue, to no avail.

Here's the project, for reference: https://github.com/bscotch/stitch/tree/develop/packages/pixel-checksum

I know very little about Rust, so I'm not 100% sure I've done my due diligence here. But it's definitely rustc-version-dependent!

I updated my workflow to include:

```yaml
      # ...
      - run: rustup default 1.78.0
      # ...
```

Which allowed my worfklow to work as it did before.

**Comment by kjvalencik** [comment]
This was a breaking change in cargo (started replacing hyphens with underscores).

A fix in `cargo-cp-artifact` to work around the change was published in 0.1.9.

Can you try upgrading to this version and see if it resolved the issue?

**Comment by antonok-edm** [comment]
@kjvalencik `cargo-cp-artifact` 0.1.9 fixed the issue, at least for me

(thanks!)

**Comment by darmie** [comment]
This issue persists in rustc 1.87.00-nightly
