### ISSUE TITLE
Neon CLI output is not visible w/ the solarized dark terminal theme

### ISSUE THREAD

**Issue by carllerche** [neon-bindings/neon#105]
![example](https://d17oy1vhnax1f7.cloudfront.net/items/3u121q1b0S0f2N1g0R0R/1__carllerche_Carls-MacBook-Pro____Code_cardstack_dotbc_dotbc-js__zsh__and_Google_Hangouts_-_me_carllerche_com.png?v=9da395a7)

**Comment by nixpulvis** [comment]
Screenshot is dead, but I think your point is mainly about avoiding "bad" colors.

**Comment by dherman** [comment]
We've replaced `neon-cli` with `npm init` so this should be obsolete, but we can reopen if we discover issues with the new CLI workflow.
