### ISSUE TITLE
Support Node v22

### ISSUE THREAD

**Issue by rtritto** [neon-bindings/neon#1082]

**Comment by kjvalencik** [comment]
Node v22 is supported. Is there a specific issue you are having?

**Comment by rtritto** [comment]
No, I had some doubts. Please can the Node v22 be added in the [table](https://github.com/neon-bindings/neon#nodejs) of README?

**Comment by kjvalencik** [comment]
Thanks for pointing that out!

I opted to [remove the table](https://github.com/neon-bindings/neon/commit/7dec390426cd7855c9963a649687183b3cae2a30) and instead make it more clear that we support all current and maintenance versions of Node.

Technically, all versions of Node >=10 are supported (provided an appropriate Node-API version), but we only actively test current versions.
