### ISSUE TITLE
CSlice / CMutSlice and Send + Sync

### ISSUE THREAD

**Issue by bluss** [neon-bindings/neon#120]
Your c slice types are unconditionally Sync. It should be conditional on the `T` type being sync.

We can look at libstd's slice iterators for an analogy where the Send/Sync impls are written out explicitly for us in the docs:

``` rust
impl<'a, T> Sync for Iter<'a, T> where T: Sync
impl<'a, T> Send for Iter<'a, T> where T: Sync

impl<'a, T> Sync for IterMut<'a, T> where T: Sync
impl<'a, T> Send for IterMut<'a, T> where T: Send
```

So that's your guide for how CSlice and CSliceMut should be.

(Also note how shared and mutable versions differ).

**Comment by dherman** [comment]
Moved to https://github.com/dherman/cslice in #181 and resolved in dherman/cslice#1.
