### ISSUE TITLE
Build succeeds with failed npm test

### ISSUE THREAD

**Issue by jedireza** [neon-bindings/neon#154]
Currently there is a failing npm test, but the build still succeeds. We need to correct the Travis config.

**Comment by ckee83** [comment]
Is this still a problem? I can't find any failing tests on Travis w/ a passing build. I get an error when trying to access builds from December though.

**Comment by jedireza** [comment]
Ah good call. The bug with the failing test was fixed via https://github.com/neon-bindings/neon/pull/161 and the failing tests producing a failing build was fixed via https://github.com/neon-bindings/neon/pull/191.
