### ISSUE TITLE
Unbalanced parentheses on example on website.

### ISSUE THREAD

**Issue by Darksonn** [neon-bindings/neon#160]
Under the section “Crash-Free Memory Management” on the [front page](https://www.neon-bindings.com/), there’s the following code example:

    fn hello(call: Call) -> JsResult<JsString> {
        // safely tracked throughout this function!
        let val = JsString::new(call.scope, "hello, Node")
                           .unwrap());
        ...
        Ok(val)
    }

Notice how the line `let val = JsString::new(call.scope, "hello, Node").unwrap());` has unbalanced parentheses.

**Comment by jedireza** [comment]
Thanks for letting us know. I've created a PR to fix here: https://github.com/neon-bindings/www/pull/4
