### ISSUE TITLE
more targeted workaround for Windows Command bug

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#162]
PR #159 applies a blunt fix by passing `--silent` to `npm install`. We should make it more targeted in a few ways:

* Do it only for `cfg(windows)`.
* Verify that `--loglevel error` works and use that instead.
* Once rust-lang/rust#38835 merges in Rust nightly, verify that it works and then use something like [rustc_version](https://crates.io/crates/rustc_version) in the build.rs to decide dynamically based on the Rust version whether it's no longer necessary to use the workaround.

**Comment by kjvalencik** [comment]
No longer relevant for Node-API backend.
