### ISSUE TITLE
use cargo workspaces

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#164]
Since there are multiple crates in this project, it should be configured with cargo workspaces.

**Comment by goto-bus-stop** [comment]
@dherman Looks like this was done in [`39dc4f5` (#314)](https://github.com/neon-bindings/neon/pull/314/commits/39dc4f52d115ce5bf488221c1b1fecd132303f0b)?

**Comment by kjvalencik** [comment]
This was implemented awhile ago.
