### ISSUE TITLE
IDL abstraction

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#19]
The type definitions, especially for various object brands, involve a fair bit of boilerplate. This should be generated either from a macro or a `build.rs` code generator.

**Comment by eddyb** [comment]
I have done this before (C++11, not Rust) in the now defunct [v8-gearbox](https://github.com/eddyb/v8-gearbox).

It ended up being easier to not mention types explicitly and overload C++ implicit conversions, which isn't really an option for Rust.

Eventually, a decorator (syntax extension) on a Rust function could generate the shim that handles all of the conversions before calling the function, but we can do most of it in `macro_rules` for now.

**Comment by drbo** [comment]
Alternatively, the Rust functions could have their parameters and return values bounded by a trait.

**Comment by dherman** [comment]
I'm going to attempt to address this with the "Classes 2.0" RFC.
