### ISSUE TITLE
exception (i.e., panic) safety

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#193]
There's another kind of safety we don't currently offer, but we can: _exception safety_.

The basic intuition of exception safety is that if an operation aborts halfway through modifying some state, it won't leave any data structures in an unpredictable intermediate state (or at least poisons them by default with an option to allow them to participate in an unwinding protocol).

Now, we can't guarantee this about _JavaScript_ objects, but JavaScript already doesn't have exception safety anyway. What we can do is guarantee that, any time Rust is operating on Rust data structures, a panic will cause that data structure to get poisoned.

We can do this because of the `Lock` API: we know exactly when we're operating on a Rust data structure. So we add a "nullability" protocol and require that for the locking protocol. The locking API would wrap the operation with `catch_unwind`, and if a panic occurred, null out the data structure and then `resume_unwind`.

This also fits well with typed arrays, which have a "[neutering](http://v8.paulfryzel.com/docs/master/classv8_1_1_array_buffer.html#a3420f7d38a8fe20e8f40fb82e6acb325)" operation that can be used for this purpose.

For custom classes, we can just use an Option under the hood of the class implementation.

**Comment by nixpulvis** [comment]
There is an important distinction between safety (in the static sense) and safety in this sense (dynamic). I'm also not sure I completely understand, but returning `null` on exception seems like the wrong thing to do for JS. I would want to force an error on the JS programmer if I saw one in Rust land.

**Comment by kjvalencik** [comment]
This is generally covered under Node-API.
