### ISSUE TITLE
Module failed to self-register on BSD

### ISSUE THREAD

**Issue by SomeKittens** [neon-bindings/neon#195]
`require('./native');` fails to run on BSD:

`Module failed to self-register`

```
Node: v7.7.1
npm: 4.1.2
$ rustc --version
rustc 1.15.1 (021bd294c 2017-02-08)
```

Here's a nifty gist to get one up and running on BSD with Vagrant: https://gist.github.com/anonymous/f432657ea0fd7123ce4650f153151251

**Comment by kjvalencik** [comment]
This was likely related to the neon-sys backend. As far as I know, the Node-API backend works on BSD.
