### ISSUE TITLE
cull dead neon-runtime functions

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#20]
There are some crufty `neon-runtime` functions that aren't being used anymore; we should get rid of them.

**Comment by SeanPrashad** [comment]
Hi @dherman - me again! I'd like to fix up this bug if it's still available

**Comment by dherman** [comment]
@SeanPrashad Go for it! Ping me on Slack any time if you need any help.

**Comment by SeanPrashad** [comment]
Just checking in - haven't gone into hiding (just swamped with other coursework). I will hopefully get a chance to take a look in the next few days!

**Comment by dherman** [comment]
This was related to the legacy backend, which will eventually be removed anyway, so closing as not worth it.
