### ISSUE TITLE
How to serialize a JsObject?

### ISSUE THREAD

**Issue by nswbmw** [neon-bindings/neon#203]

**Comment by dherman** [comment]
I apologize for not seeing this sooner. It would be helpful to get more information about what you're looking for. If you're looking for a way to iterate over the properties of an object, you can use [`JsObject::get_own_property_names`](https://api.neon-bindings.com/neon/js/trait.object#method.get_own_property_names). I'm closing this issue for now but please feel free to reopen if you'd like to ask followup questions!
