### ISSUE TITLE
Hide __LOAD_NEON_MODULE by using #[used] on a private static.

### ISSUE THREAD

**Issue by eddyb** [neon-bindings/neon#204]
See https://github.com/rust-lang/rust/pull/39987. Still unstable, so you may want to wait for stabilization (if it's happening soon).

**Comment by RReverser** [comment]
@eddyb This is so great. Literally few minutes ago had to workaround this via `std::sync::{Once, ONCE_INIT}`.

**Comment by dherman** [comment]
Here's the tracking issue: rust-lang/rust#40289

When it lands in Rust stable we can use it ASAP.

**Comment by kjvalencik** [comment]
The Node-API backend uses a magic symbol name instead.
