### ISSUE TITLE
missing ts-typed-json

### ISSUE THREAD

**Issue by gporrata** [neon-bindings/neon#205]
When I installed neon-cli it was missing ts-typed-json. Quick fix is simply to add the dependency to to /usr/local/node_modules/neon-cli (am using macOs). Just thought somebody should know/fix.

**Comment by ffflorian** [comment]
@gporrata See https://github.com/neon-bindings/neon-cli/pull/57

**Comment by dherman** [comment]
Fixed in neon-bindings/neon-cli#57
