### ISSUE TITLE
Ability to have property accessors for native objects

### ISSUE THREAD

**Issue by jugglingcats** [neon-bindings/neon#208]
It would be nice to be able to define first class properties with native objects. Psuedo-code:

```
declare_types! {

    /// JS class wrapping Employee records.
    pub class JsEmployee for Employee {

        property name {
            get(call) {
               // return the value
            }
            set(call) {
               // set the value
            }
        }
    }
};
```

There seems to be (or have been) a SetAccessor method in the v8 or NaN API, but hard to find good references to it!

**Comment by kjvalencik** [comment]
`declare_types` have been deprecated. This feature would need to be part of classes 2.0.

https://github.com/neon-bindings/rfcs/pull/43
