### ISSUE TITLE
The documentation URL on crates.io is out of date

### ISSUE THREAD

**Issue by abrodersen** [neon-bindings/neon#211]
Working URL: `https://api.neon-bindings.com/neon/index.html`
Current URL: `https://docs.neon-bindings.com/neon/index.html`

**Comment by SeanPrashad** [comment]
Hi there! I'm a student at Seneca College who's taking an Open Source course taught by David Humphrey and I'd love to take on this bug as one of my first if it's still available!

**Comment by dherman** [comment]
@SeanPrashad I'm dreadfully late on this, but if you're still up for it, that would be great!

**Comment by dherman** [comment]
@SeanPrashad As a hint, all you should need to do is modify the `Cargo.toml` file. You can learn more from the Cargo documentation at http://doc.crates.io/guide.html :)

**Comment by SeanPrashad** [comment]
I'm on it!!!
