### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by crazyfrozenpenguin** [neon-bindings/neon#212]
This project activity is low and I'm wondering if it is defunct?

**Comment by Hammster** [comment]
I would not say so, this project may not be frequently updated in within weeks but since the maintainers, GH profile has been inactive for 3 weeks now I would assume he's on vacation ;)

**Comment by dherman** [comment]
Definitely not dead! :D I just don't get to devote work time on it so I have to work on it in bits and pieces. I am still looking for ways to be able to get more time to work on it regularly, and hoping also to get some more contributors as we make progress on the features.

**Comment by crazyfrozenpenguin** [comment]
Thanks! I'm new to Rust and to Neon. Even with my little knowledge of the language and Neon I was already able to develop a mini RSA ciphering tool. Quite happy with the results so far. Hence, the reason for being concerned about this project being defunct. Glad it is not because using Neon was a breeze of fresh air when compared to direct use of node-ffi. Thanks for all your hard work. Cheers
