### ISSUE TITLE
"call_js_function" test fails. JsFunction.call(...) always returns JsResult<JsUndefined> 

### ISSUE THREAD

**Issue by IMRaziel** [neon-bindings/neon#219]
I tried calling js function by compiling and running tests in "tests" folder of this repo. 
Compiled using `electron-build-env neon build`, on windows 10, called a function from js in electron renderer part using 
```js
let addon = require('electron').remote.require('/path/to/native')
addon.call_js_function(function(x) { 
    console.log(x)
    return x + 1 
})
```
function call was failing with error in native code because `f.call(scope, JsNull::new(), args)` was returning `JsResult<JsUndefined>` instead of expected `JsResult<JsNumber>`. I changed types to `JsResult<JsValue>` and tried again.

Function was called, i can see value of x in console. But return value is always `undefined` no matter what i return from js function

**Comment by dherman** [comment]
@IMRaziel This may be too late, but could you share the full test case?

**Comment by kjvalencik** [comment]
Closing since this issue does not include enough details to reproduce.
