### ISSUE TITLE
error running helloworld, Module version mismatch

### ISSUE THREAD

**Issue by ctaggart** [neon-bindings/neon#223]
I originally had Node.js 8.3 installed on Windows 10, but ran into bug #222. Node 8.3 has module version 57. I then installed 6.11.2, the LTS version of Node.js which has module version 48. When I try `node lib\index.js`, I get error:  `Module version mismatch. Expected 48, got 57.`.  I'm not sure where this error is coming from. I've cleaned out all build artifacts that I can think of.

https://nodejs.org/en/download/releases/

**Comment by ctaggart** [comment]
The good news is 8.0.0 does work.

However, Node.js 8.0.0 is the only version that works for me right now on Windows. Versions above 8.0.0 are affected by #222 and versions below 8.0.0 are affected by this. I still don't know what is causing this.

**Comment by hone** [comment]
@ctaggart does #221 fix this for you?

**Comment by ctaggart** [comment]
I'm assuming it does. I'll reopen if it does not.
