### ISSUE TITLE
line wraps in validation errors confuse inquirer

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#237]
_From @dherman on January 5, 2016 21:9_

Validation errors that are longer than the terminal width and wrap around to the next line cause inquirer to get confused about how to position the cursor back on the preceding line.

_Copied from original issue: neon-bindings/neon-cli#24_

**Comment by janowsiany** [comment]
@dherman Hello, is this still valid issue? I tried to reproduce it and potentially fix it but it seemed to work just fine even for long validation messages.

**Comment by lp** [comment]
Hi!  would that task still be relevant atm?

**Comment by kjvalencik** [comment]
As part of [this RFC](https://github.com/neon-bindings/rfcs/pull/36), `neon-cli` will be deprecated. Anything related to it that isn't necessary maintenance likely isn't needed.
