### ISSUE TITLE
Prompted responses in `neon new` not escaped in generated package.json

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#238]
_From @bantic on August 11, 2016 4:28_

The response to the prompts in the `neon new` flow are not escaped when they are interpolated into the resulting `package.json`, which can lead to an invalid JSON structure. For instance, entering the value `my "cool" project` for the "description" prompt results in a package.json that looks like:

``` javascript
// ....
"description": "my "cool" project",
// ...
```

_Copied from original issue: neon-bindings/neon-cli#30_

**Comment by robbiepitts** [comment]
Looking into this.

**Comment by dherman** [comment]
Fixed in #238. Thanks, @robbiepitts!
