### ISSUE TITLE
Abstract build functionality into a neon-build module

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#239]
_From @jedireza on December 13, 2016 7:42_

Right now the `neon` cli serves as both the utility for starting new neon modules (the boilerplate) and the cargo build tool. I'm suggesting that we separate the cargo build functionality into it's own module `neon-build`.

Separating the build functionality into a `neon-build` dependency means neon modules don't have to depend on the entire `neon-cli`, reducing the dependency tree for neon modules _and consumers of neon modules_.

Additionally this can help get us closer to a `npm` scripts style workflow (rather than expecting `neon` to be on the path globally). Mentioned in #34 and https://github.com/neon-bindings/neon/pull/126.

We can achieve this without breaking changes to `neon-cli` by using the new `neon-build` module internally. We could probably just replace the [`require` statement for `./opts/neon_ build.js`](https://github.com/neon-bindings/neon-cli/blob/831adea0ba1cae5fe1fbca7851c3030709dcf369/src/cli.js#L5), or something similarly simple.

_Copied from original issue: neon-bindings/neon-cli#35_

**Comment by dherman** [comment]
Blocked on a xargo-like cargo wrapper RFC (see #240, #242, #243, #244)

**Comment by kjvalencik** [comment]
`neon-cli` is deprecated and special building is no longer necessary.
