### ISSUE TITLE
A small guide on hacking neon?

### ISSUE THREAD

**Issue by ArsalanDotMe** [neon-bindings/neon#24]
I'm a newbie to both Rust, and node-gyp but I found this project on twitter and thought it was pretty cool. I want to contribute to this repo and learn Rust too. So can you write a little "Hacking neon for dummies" guide to help newcomers like me get started? I just installed Rust, discovered Cargo, and am just checking out the code in this repo.

Thanks!

**Comment by marxo** [comment]
+1

**Comment by dherman** [comment]
@ArsalanDotMe @marxo A quick progress report: I've got a [docs site](http://neon.rustbridge.io) set up, and I've stubbed out a [hacking guide](http://neon.rustbridge.io/hacking.html), but no contents yet. Steadily making progress though!

For the time being, if you're interested in contributing please feel free to come hang out on the [community slack](http://rustbridge.slack.com) (grab an [automatic invite](http://rustbridge-community-slackin.herokuapp.com/) to join) and ask questions on `#neon`. (Or you can join `#neon` on `irc.mozilla.org` if you prefer IRC.)

**Comment by tomjakubowski** [comment]
@dherman I tried to grab an automatic invite, but the site returns an "Application Error" page. Could you send one to my email address (on my GitHub profile). Thanks!

**Comment by nixpulvis** [comment]
I love writing guides FWIW, though I'm hesistent to dive into this until:

1. I know neon a lot more (working on it).
2. I feel like the docs I'm writing are going to stick, pending big API changes.

Let me know if there are any areas in specific we should tackle sooner rather than later.

**Comment by dherman** [comment]
Let's open an issue in the guides repo for this. @nixpulvis I'm excited you want to help with this and I hear you Re: not wanting to write about stuff that's likely to change. I think Classes 2.0 and VM 2.0 are the biggest changes coming, so maybe we can discuss this during/after those RFCs.
