### ISSUE TITLE
`neon build` force rebuilds everything after a compiler error

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#242]
_From @matklad on April 30, 2017 17:49_

Hi! I am writing an electron node addon based on https://github.com/dherman/neon-electron-hello (thank you very much for this example, I was able to get up in running in no time despite the fact that it was my first ever electron program).

The problem is, everytime I run `npm run build` when there is a compile time error in my Rust code, neon prints:

```
neon info forcing rebuild for new build settings
neon info running cargo
```

and then rebuilds the world, which is kinda slow:

```
   Compiling neon v0.1.15
   Compiling neon-build v0.1.15
   Compiling cslice v0.2.0
   Compiling gcc v0.3.45
   Compiling neon-hello v0.1.0 (file:///home/matklad/projects/neon-hello/native)
   Compiling neon-runtime v0.1.15
```

If I change my rust code without introducing any errors, then only my code gets rebuild. Perhaps this `forcing rebuild` is spurios? I didn't change `package.json`, so the build settings are the same. 

Or perhaps there's something wrong with my build setup?

I have `projects/neon-electron-hello` and `projects/neon-hello` and I've executed `npm link ../neon-hello` inside of `neon-electron-hello`. 

_Copied from original issue: neon-bindings/neon-cli#55_

**Comment by dherman** [comment]
_From @matklad on April 30, 2017 17:53_

So after erroneous compilation my artifacts.json looks like this:

`{"active":null,"targets":{}}`

**Comment by dherman** [comment]
_From @matklad on April 30, 2017 17:57_

These two lines are to blame: 

https://github.com/neon-bindings/neon-cli/blob/df442e3b5241ee29920203a13b4a33efeb080e6c/src/target.js#L77

https://github.com/neon-bindings/neon-cli/blob/df442e3b5241ee29920203a13b4a33efeb080e6c/src/target.js#L84

Perhaps we shouldn't remove artifacts if we were able to execute cargo regardless of exit code?

**Comment by dherman** [comment]
_From @jchlapinski on July 23, 2017 18:59_

+1 I have exactly the same problem, could someone from neon team comment on how can this be fixed? Regards

**Comment by fasihrana** [comment]
Ran into this :/

**Comment by matklad** [comment]
A workaround for this issue is to setup sccache: http://doc.crates.io/guide.html#build-cache

**Comment by dherman** [comment]
This is related to the need for a xargo-like Cargo wrapper RFC (see #244 and #243), but it's also just a bug in the caching logic and should be fixable before even working out an improved workflow.

**Comment by dherman** [comment]
@matklad Thank you so much for the detective work! Working on fixing this tonight.
