### ISSUE TITLE
put internal metadata in a .neon directory

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#243]
_From @dherman on June 8, 2017 4:48_

Neon projects should always contain a `.neon` directory for internal metadata that doesn't go into source control. This is an idiomatic way to hide metadata that users shouldn't normally have to think about.

The `artifacts.json` file should live in that directory instead of under `native/`, and then it doesn't need an entry in `.gitignore`.

This will also then become the easy way to determine whether a project is a Neon project, and electron-rebuild can use it as the heuristic to build the project with Neon.

_Copied from original issue: neon-bindings/neon-cli#60_

**Comment by dherman** [comment]
This is also related to the need for a xargo-like cargo wrapper RFC. (See #244)

**Comment by kjvalencik** [comment]
Internal metadata is not needed for the Node-API backend.
