### ISSUE TITLE
Linker errors when running `cargo test` in native folder

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#244]
_From @jchlapinski on July 25, 2017 21:4_

I have prepared a repo with example that illustrates my problem: https://github.com/jchlapinski/neon-debug-example

Basically when I try to run unit tests for debug profile in my rust code (see https://github.com/jchlapinski/neon-debug-example/blob/master/neon-build-debug.sh) I get linker errors when compiling tests. Everything works OK, when I use release profile (see https://github.com/jchlapinski/neon-debug-example/blob/master/neon-build-release.sh).

Is this a neon-bindings bug or am I doing something wrong here?

Regards

_Copied from original issue: neon-bindings/neon-cli#61_

**Comment by dherman** [comment]
This is related to the need for a clearer, xargo-like wrapper for cargo (until cargo has all the hooks necessary so we don't need a wrapper anymore). Needs an RFC!

**Comment by kjvalencik** [comment]
This was fixed, but additionally it's not an issue with the Node-API backend.
