### ISSUE TITLE
change top-level test workflow to use cargo

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#246]
Running all the Neon tests should be kicked off with `cargo test`, which is the idiomatic way to run tests for a Rust project. This can be done by shelling out to `npm` etc where necessary.

- [x] one test called `cli`:
  - in the `cli` directory: shells out to `npm install` and `npm run transpile`
  - in the `test/cli` directory: shells out to `npm install` and `npm run transpile` and `npm test`
- [x] one test called `static`, only enabled if we're in Rust nightly:
  - in `test/static` directory: shells out to `cargo test`
  - or maybe it can be called into through a compiletest API instead of shelling from cargo to cargo?
- [x] one test called `dynamic`:
  - in `test/dynamic` directory: shells out to `npm install` and `npm test`

Then the CI scripts can be changed to just do a single `cargo test` instead of all of the above.

**Comment by dherman** [comment]
@humphd That would be amazing! I'd be happy to help mentor any students who want to help with this, too. (I have so far been having trouble keeping to a regular schedule monitoring these issue threads, but if you ever need my attention, please feel free -- you or your students -- to ping me on slack or twitter to check a thread, I'll make sure to respond as quickly as possible.)

**Comment by dherman** [comment]
@humphd Looks like @MilanLoveless got to this one already in #255, at least partially. Another infrastructure issue we could really use help with is getting #252 over the finish line -- do you think your students might be interested/able to help with that one?

**Comment by humphd** [comment]
OK, thanks for letting me know.  Reading that PR, it also looks like "make this work fully on Windows" might be something for them to do in future as well.  RE: #252, I know that @SeanPrashad hit this recently, and I was suggesting he look into it.  Maybe he'd like to try this?

I'll circle back to this stuff later and do some bugs with my students as it lines up with topics we're covering.

**Comment by SeanPrashad** [comment]
@humphd @dherman and I spoke briefly about this on Slack last night! I'd love to try and tackle #252 in the near future if that's ok with everyone 😬

**Comment by humphd** [comment]
@SeanPrashad I think it would be a good fit for you, and give you some nice exposure to build automation, which is something I remember you expressing interest in at the start of the term.

**Comment by dherman** [comment]
I believe this was fixed by @MilanLoveless in #255 (with a couple follow-up commits from me for Windows)!
