### ISSUE TITLE
merge release notes

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#247]
Merge stuff from cli/RELEASES.md into RELEASES.md -- since the PRs reference the `neon-cli` repo either change the links to reference that repo or link to the commits.

**Comment by SeanPrashad** [comment]
Hi @dherman! I'd like to tackle this bug if it's still unassigned but I'm not sure where to start - would you be able to provide some details?

**Comment by dherman** [comment]
@SeanPrashad Yes, exactly :D When you bring the cli/RELEASES.md comments into RELEASES.md, wherever they reference neon issues/PRs, you can eliminate the explicit reference to neon (e.g., "neon-bindings/neon#214" can just become "#214"), and wherever they reference neon-cli issues/PRs, please make those explicitly reference the old repo (e.g., "TypeScript upgrade fixes (#62, #65)" becomes "TypeScript upgrade fixes (neon-bindings/neon-cli#62, neon-bindings/neon-cli#65)").

Also, would you mind fixing up the markdown so they render as actual links?

**Comment by SeanPrashad** [comment]
Got it! I will take a look at merging the two files and fixing up the markdown to render links and get back to you if I have any questions!
