### ISSUE TITLE
API for getting the global object

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#249]
There needs to be an API for getting at the global object. In the V8 API you can get this from [v8::Context::Global()](https://v8docs.nodesource.com/node-8.0/df/d69/classv8_1_1_context.html). In Neon it should probably be a method of `Scope`, something like:

```rust
fn global(&mut self) -> Handle<JsObject>;
```

**Comment by reSHARMA** [comment]
I am new to neon , but I really want to contribute on this issue . Can you guide me what should I do next ?

**Comment by dherman** [comment]
@reSHARMA So sorry, @GabrielCastro got to this one first with #249. I'm planning to spend some time tomorrow finding more good tasks for first-time contributors.

**Comment by dherman** [comment]
Fixed in #249.
