### ISSUE TITLE
Compiling with debugging symbols

### ISSUE THREAD

**Issue by jjpe** [neon-bindings/neon#256]
I think my neon-based project is doing something Node doesn't like as the node proc segfaults.
So I'd like to compile it with debugging symbols intact, rather than in release mode.
How do I go about doing this? I'd consult the [website](https://guides.neon-bindings.com/debugging/), but it's a bit Lorem Ipsummy.

**Comment by dherman** [comment]
I agree this would be nice to have, but as you say I'm not sure if it's possible. We'll try to triage this with labels that might help people who have the relevant skills to be able to help.

Also cc'ing @bnoordhuis and @eddyb who might have some ideas?

**Comment by bnoordhuis** [comment]
Correct me if I'm wrong but doesn't `env DEBUG=true neon build` turn on debug mode?

If you also want debug symbols for the node binary itself, you'll have to build it from source with `./configure --debug && make`.

**Comment by jjpe** [comment]
I just tried this on OS X, and here setting it seems to do nothing: 

````
$ env DEBUG=true neon build
neon info running cargo
   Compiling sbr-validate-npm v0.7.4 (file:///Users/j/Development/accept/sbr-validate-npm/native)
warning: variable does not need to be mutable
   --> src/lib.rs:129:1
    |
129 | / register_module!(m, {
130 | |     let repl_class: Handle<JsClass<JsRepl>> = JsRepl::class(m.scope)?;
131 | |     let repl_ctor: Handle<JsFunction<JsRepl>> = repl_class.constructor(m.scope)?;
132 | |     m.exports.set("Repl", repl_ctor.as_value(m.scope))?;
133 | |     Ok(())
134 | | });
    | |___^ help: remove this `mut`
    |
    = note: #[warn(unused_mut)] on by default
    = note: this error originates in a macro outside of the current crate

    Finished release [optimized] target(s) in 8.15 secs
neon info generating native/index.node
````

**Comment by dherman** [comment]
@jjpe Ugh I'm slapping my forehead right now, I completely forgot there is already the functionality for this. I just did a quick test and I think it's working. Give it a try if you're still interested and see if it works for you.

All you have to do is pass `-d` or `--debug` to `neon build`:

```
$ neon build --debug
```

**Comment by jjpe** [comment]
That did it. The original trigger for this issue has since been solved, but it is nice to see nonetheless that this is possible. Awesome work guys :)
