### ISSUE TITLE
Windows: 'Couldn't find node_root_dir in node-gyp output.'

### ISSUE THREAD

**Issue by fasihrana** [neon-bindings/neon#263]
I'm getting an error on windows when I compile the skeleton neon program using `neon build`.

node v8.8.0
npm 5.4.2
rustc 1.21.0 (3b72af97e 2017-10-09)
cargo 0.22.0 (3423351a5 2017-10-06)

-------------------------------------------------------------------------------------------------------------------
error: failed to run custom build command for `neon-runtime v0.1.20`
process didn't exit successfully: `C:\Users\fasih\workspace\experiment\neon\myproj\native\target\release\build\neon-runtime-894bed62900c6e34\build-script-build` (exit code: 101)
--- stdout
'Skipping node-gyp installation as part of npm install.'
up to date in 0.392s
cargo:node_arch=x64

--- stderr
thread 'main' panicked at 'Couldn't find node_root_dir in node-gyp output.', src\libcore\option.rs:819:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

neon ERR! cargo build failed

**Comment by fasihrana** [comment]
This is my mistake. Should have read the instructions clearly!

`C:\> npm install --global --production windows-build-tools` did the trick.

**Comment by hardliner66** [comment]
I have the same error, even after installing the windows-build-tools package.
