### ISSUE TITLE
Allow closures for JsFunction initialization

### ISSUE THREAD

**Issue by abrodersen** [neon-bindings/neon#264]
Currently, the constructor for  `JsFunction` values only permits passing static function pointers. This makes continuation passing APIs impossible to write. 

For example, say I want to design a function `doWork` that accepts a callback, and this callback must provide a value asynchronously. I would design the function such that I would pass a continuation into the callback like so:

````
doWork(someData, (continue) => {
  doSomethingAsynchronously(otherData, (result) => { continue(result) });
});
````

Within Rust, I would like to pass some context into the continuation:

````
fn do_work(call: Call) -> JsResult<JsValue> {
    let callback = call.arguments.require(call.scope, 0)?.check::<JsFunction>()?;
    let some_other_state = ();
    let continuation = JsFunction::new(scope, move |call| {
        let extra_data = call.require(call.scope, 0)?;
        // do something with some_other_state
    });
    
    // I might want to pass the context into a task
    let task = MyTask { some_other_state };
    task.schedule(callback);

    Ok(JsUndefined::new().upcast())
}
````

This style of API is very common in Node.js, especially when doing things like asynchronous IO.

Looking at the source code, it appears that the function pointer is merely turned into a raw pointer. Couldn't the code be modified to use a `Box<FnMut(Call) -> JsResult<JsValue>>` when creating a `JsFunction`? `Box` even has built in methods for converting too and from raw pointers.

**Comment by kjvalencik** [comment]
These use cases are covered under the Classes 2.0 RFC and the async task API.
