### ISSUE TITLE
Electron/NWJS on Windows "Uncaught Error: Module did not self-register."

### ISSUE THREAD

**Issue by fasihrana** [neon-bindings/neon#265]
I have run into a problem where I cannot get the node module to load in either Electron or NWJS. Both of those are giving me the same error:

```
(unknown) Uncaught Error: Module did not self-register.
    at Object.Module._extensions..node (module.js:695:18)
    at Module.load (module.js:569:32)
    at tryModuleLoad (module.js:532:12)
    at Function.Module._load (module.js:524:3)
    at Module.require (module.js:592:17)
    at require (internal/module.js:11:18)
    at self.require (<anonymous>:11:26)
```

The problem only arises when I try to load the module on Windows in Electron or NWJS. If I require the module in a simple js file and then run using node, it works completely fine. I did not have this problem on Linux/Ubuntu and I cannot find any reference regarding this on neon but there are some instances of this error elsewhere if I google this.

Would greatly appreciate the help.

**Comment by bnoordhuis** [comment]
Did you recompile your module for electron and nw.js?  They aren't binary-compatible with node.js.

Nor is node.js with itself between major versions, for that matter.

**Comment by fasihrana** [comment]
Sorry for my ignorance, but how does one go about recompiling the node module for nwjs when building with neon?

**Comment by bnoordhuis** [comment]
Have you seen https://guides.neon-bindings.com/electron-apps/ ?  I don't know if it's also supposed to work with nw.js but that's where I would start looking.

**Comment by fasihrana** [comment]
Is this recompiling only necessary for windows? Worked perfectly fine on Ubuntu with this additional step.

**Comment by bnoordhuis** [comment]
When you say "worked perfectly fine" you mean with a from-scratch project as described in the link I posted?

**Comment by fasihrana** [comment]
"From scratch" in my case meaning that I only followed [Getting Started](https://guides.neon-bindings.com/getting-started/) and [Hello, World!](https://guides.neon-bindings.com/hello-world/) links only.

"Perfectly fine" means, that I was able to load this module in electron and in nwjs without performing any additional build steps. That is what surprised me when I brought my project onto windows and attempted the same steps.

**Comment by bnoordhuis** [comment]
Aha.  No idea why Windows would be more problematic than others, sorry.

**Comment by fasihrana** [comment]
I'm going to try that extra step on windows and see if that helps with getting it to load in electron. Will update when I know more. Will leave this issue open as I feel either this could be added to FAQs and also we should not neglect nwjs as a platform given that nwjs is on Chrome 62 and nodejs 8.7 for those of us living on the "edge".

**Comment by fasihrana** [comment]
Ok, so no joy.

I have two folders as follows:
```
-ob //this is my electron app
   |- package.json
   |- main.js
   |- index.html
-sample //this is my default neon module
   |- *all default files*
```

My `sample/package.json` is as follows:
```
{
  "name": "sample",
  "version": "0.1.0",
  "description": "",
  "main": "lib/index.js",
  "author": "fasihrana",
  "license": "MIT",
  "dependencies": {
    "neon-cli": "^0.1.20"
  },
  "scripts": {
    "install": "neon build"
  }
}
```

My `ob/package.json` is as follows:
```{
        "name": "ob",
        "version": "0.1.0",
        "main": "main.js",
        "dependencies": {
                "sample": "file:../sample"
        },
        "dev-dependencies": {
                "electron-build-env": "^0.2",
                "neon-cli": "^0.1.2"
        },
        "scripts": {
                "build": "electron-build-env neon build sample"
        }
}
```

I don't understand what i am doing wrong here.

**Comment by fasihrana** [comment]
Ok, so figured out that I needed to change the following in `ob\package.json`

```
"dev-dependencies": {
                "electron-build-env": "^0.2",
                "neon-cli": "^0.1.2"
        }
```
to
```
"devDependencies": {
                "electron": "^1.6.2",
                "electron-build-env": "^0.2",
                "neon-cli": "^0.1.2"
        }
```

**Comment by itserg2008** [comment]
I have exactly the same issue. Has anyone resolved it somehow?
