### ISSUE TITLE
Suggestion: use `'j` as a lifetime name inside various `Handle`s and `Scope`s

### ISSUE THREAD

**Issue by matklad** [neon-bindings/neon#268]
Using `'a` is not really illuminating, especially if you have constructions like `&'a mut Scope<'b>`. Using `'j` inside neons codebase would give a common sweet name to this lifetime to the whole neon-community.

**Comment by matklad** [comment]
To make it clear, I would love to see `Call<'j>`, `RootScope<'j>`, `Handle<'j, JsValue>` :)

**Comment by RReverser** [comment]
So to be clear - is this just a documentation change? Because from consumer point of view you can already name lifetimes you pass in as you wish, and `'a` is just a very common placeholder for lifetimes in Rust.

**Comment by matklad** [comment]
Yep! Just code style and documentation: while consumers can use whatever lifetime they choose, it's a high chance they'll use whatever neon itself uses. 

A good example of what I have in mind is how serde consistently uses `'de` for lifetime of data to be deserialized. 

Context: i was fixing some lifetime-related problems in serde-neon (https://github.com/GabrielCastro/neon-serde/pull/7), and seeing `&'a Scope<'b>` and `Handle<'b, JsValue>` everywhere didn't helped me much :)

**Comment by dherman** [comment]
@matklad What would you do when there are multiple such lifetimes? I'm trying to understand the full convention you're proposing.

**Comment by dherman** [comment]
(If/when we get to a good consensus on a convention then it should be ready to label as `beginner friendly`.)

**Comment by nixpulvis** [comment]
I'm personally a fan of one letter lifetimes, though I don't know why. Types in Rust do tend to get rather long from time to time, I'd propose to aim to keep short lifetimes at least.

**Comment by matklad** [comment]
>What would you do when there are multiple such lifetimes? I'm trying to understand the full convention you're proposing.

Hm, and are there use-cases for user-facing code when there are several *different* `Scope` lifetimes in scope? I would probably go with `j1` and `j2` for unrelated lifetimes, and `j1` and `j: j1` for nested lifetimes.

**Comment by dherman** [comment]
@matklad I'm still having a little trouble understanding this. Could you maybe write a concrete example?

**Comment by matklad** [comment]
I've tried to dig into "multiple lifetimes" use case and I can say that now it's not obvious to me which convention is the best :) 

A good example is `ToJsString` imls: https://github.com/matklad/neon/commit/7ce9dfcb61152201d71cb8bbe1759488f592e83d#diff-9b4b0129f7401327b05224aec23f343bL354

```Rust
impl<'j2> ToJsString for Handle<'j2, JsString> {
    fn to_js_string<'j1, T: Scope<'j1>>(&self, _: &mut T) -> Handle<'j1, JsString> {
        Handle::new_internal(JsString::from_raw(self.to_raw()))
    }
}

impl<'a> ToJsString for &'a str {
    fn to_js_string<'j, T: Scope<'j>>(&self, scope: &mut T) -> Handle<'j, JsString> {
        match JsString::new_internal(scope.isolate(), self) {
            Some(s) => s,
            None => JsString::new_internal(scope.isolate(), "").unwrap()
        }
    }
}
```

Here we see `j`s which mean that there's some v8 scope behind the scene, and `a` which means just some lifetime of an usual rust reference, not tied to v8 at all.

But I don't quite understand how to deal with NestedScope and ChainedScope :)

**Comment by kjvalencik** [comment]
Closing this as a stale issue. Will re-open if participants still feel strongly.
