### ISSUE TITLE
Neon module with classes fails mysteriously when run from vscode with debugger

### ISSUE THREAD

**Issue by matklad** [neon-bindings/neon#275]
I've recently added classes to my neon-based extension to VsCode and while by itself they work as expected, if I try to debug the extension, the extension development host crashes. If I just install extension, or if I don't export any classes, everything works fine

Steps to reproduce:

```
$ git clone https://github.com/matklad/fall.git
$ cd fall
$ git reset --hard d40091c3fc5344760418b1bed96a183e64dc1cf1
$ cd code
$ npm install
$ code .

# open extension.ts
# press F5 to launch debugging session
# in the extension development host code, open any file with .fall extension, for example, `lang/rust/src/rust.fall`.
# see the vscode crash
```

However, when running extension without debugger, everything works fine:

```
$ code --extensionDevelopmentPath=/path/to/repository/fall/code
# alternatively, `just code` to install extension
```

Version of `code` might be relevant:

```
Version 1.13.0
Commit 376c52b955428d205459bea6619fc161fc8faacf
Date 2017-06-08T16:41:25.571Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
```

Here's where I declare my class: https://github.com/matklad/fall/blob/d40091c3fc5344760418b1bed96a183e64dc1cf1/code/native/src/lib.rs

**Comment by dherman** [comment]
I don't know off the top of my head what's going on here but I also use VSCode so I have some personal motivation to fix this too. ;) It'll require some investigation though.

**Comment by kjvalencik** [comment]
`declare_types` has been deprecated and does not exist for the Node-API backend.
