### ISSUE TITLE
functional regression: `JsInteger` removed in 0.1.21

### ISSUE THREAD

**Issue by vmx** [neon-bindings/neon#279]
Please bump Neon to 0.2.0.

`JsInteger` got removed in version 0.1.21, which is a breaking change. This can break projects that depend on Neon 0.1.x.

**Comment by dherman** [comment]
My bad! I will revert the removal of `JsInteger` and push it as 0.1.22 and then yank 0.1.21. I should be able to do this late tonight.

**Comment by dherman** [comment]
Fell asleep while testing! 😜 Working on getting this done this morning...

**Comment by dherman** [comment]
Published as 0.1.22 and yanked 0.1.21. Please do keep in mind that `JsInteger` is deprecated and we'll be removing it for 0.2.
