### ISSUE TITLE
neon::js::error::Kind does not implement `Copy`

### ISSUE THREAD

**Issue by kjvalencik** [neon-bindings/neon#290]
I have a somewhat niche issue where I wanted to generate two errors with the identical kind. However, since `Kind` does not implement `Copy` _and_ the `JsError` constructor moves kind instead of borrows, it requires a bit of boilerplate.

```rust
// Compile error
let err = JsError::new(scope, kind, msg.as_str())?;
let cause = JsError::new(scope, kind, msg.as_str())?;
```

The work around is to write my own copy wrapper.

```rust
fn copy_kind(kind: &Kind) -> Kind {
	match *kind {
		Kind::Error => Kind::Error,
		Kind::TypeError => Kind::TypeError,
		Kind::ReferenceError => Kind::ReferenceError,
		Kind::RangeError => Kind::RangeError,
		Kind::SyntaxError => Kind::SyntaxError,
	}
}

let err = JsError::new(scope, copy_kind(kind), msg.as_str())?;
let cause = JsError::new(scope, kind, msg.as_str())?;
```

But, it would be preferable to reduce this boilerplate by deriving the `Copy` trait on the enum.

**Comment by dherman** [comment]
Agreed—it should definitely implement `Copy`.

**Comment by ea2973929** [comment]
Due to https://github.com/neon-bindings/neon/pull/325/ this is no longer applicable and should be closed?
