### ISSUE TITLE
Feature Req: Set the target directory

### ISSUE THREAD

**Issue by flukejones** [neon-bindings/neon#292]
I was evaluating how I could use Neon to leverage Rust for use on AWS Lambdas and bumped up against a small issue.

The Lambdas require building against amazon Linux if you want to use native code due to the Amazon glibc being a different version to most Linux distros - as such I do all my compilation for them through a Docker image. This results in the final compiled libraries being located in `target/x86_64-unknown-linux-gnu/<release/debug>` though, and so the `neon build` (or npm install) fails since it can't find the library in `target/release`.

Is there a way to set the directory that `neon build` gets the compiled library from?

**Comment by muditsaurabh** [comment]
Please refer to https://dev.to/kayis/rust-on-aws-lambda-with-neon--cloud9--4el7

**Comment by Luke-Nukem** [comment]
That is helpful, but not convenient at all for local development.

**Comment by kjvalencik** [comment]
Would something like this work?

```Dockerfile
FROM lambci/lambda:build-nodejs6.10

RUN curl https://sh.rustup.rs -sSf | sh /dev/stdin -y

ENV PATH="$PATH:/root/.cargo/bin"
```

```sh
docker build -t lambda-neon-dev .

docker run --rm \
    -w /src \
    -v $(pwd):/src \
    -v $(pwd)/node_modules/.cargo/registry:/root/.cargo/registry \
  lambda-neon-dev npm install
```

**Comment by dherman** [comment]
@Luke-Nukem Totally legit request! Right now we're just inferring the target info from the current machine, which means we don't support cross-compilation. I've filed an RFC issue here:

https://github.com/neon-bindings/rfcs/issues/16

In the meantime can any of the suggestions above get you unstuck? If not we can try to prioritize getting the CLI options fleshed out and implemented.

**Comment by kjvalencik** [comment]
Workaround is using `.cargo/config` to set target directory.

**Comment by kjvalencik** [comment]
This was fixed in `neon-cli`, but is also not relevant for `cargo-cp-artifact` which reads metadata directly from `cargo` output.
