### ISSUE TITLE
Using NEON for non library projects?

### ISSUE THREAD

**Issue by moonheart08** [neon-bindings/neon#293]
Is it sane to use NEON for projects that function as an application, not a library, or should it be separated into a NEON module and the main project?

**Comment by kjvalencik** [comment]
Given the build constraints, in my opinion, it makes more sense to be integrated into an application.

I think deploying it as a library seamlessly would need resolution on https://github.com/neon-bindings/neon/issues/117.

**Comment by dherman** [comment]
@moonheart08 Totally! I think right now applications are one of the best-served use cases for Neon. (But we do have ideas for making libraries more easily deployable too!)
