### ISSUE TITLE
Investigate using node-cmake

### ISSUE THREAD

**Issue by tptee** [neon-bindings/neon#299]
[`node-cmake`](https://github.com/cjntaylor/node-cmake/blob/dev/NodeJS.cmake) might solve some recent pain points:

- Doesn't depend on Python like `node-gyp` (latest Homebrew formulas install Python 3 and break the experience out-of-the-box for Mac devs)
- Seems to have a sane cross-compilation story

**Comment by WangZishi** [comment]
what do you think about https://github.com/cmake-js/cmake-js

**Comment by kjvalencik** [comment]
Thanks for sharing @WangZishi. This could be valuable with the N-API work. The N-API branch will only require a non-Rust build chain for Windows. The two primary things that are needed are the win delay load hook and the node lib to link.

Given this very simple use case, a full build system isn't necessary. Compiling the win delay hook is fairly trivial (and might be portable to Rust), but, identifying the current node version and downloading the correct Windows library is not. It would be awesome if there was a library that did _only_ this.

**Comment by kjvalencik** [comment]
No longer necessary with n-api.
