### ISSUE TITLE
"Module not found" for native when building an electron app

### ISSUE THREAD

**Issue by AviateX14** [neon-bindings/neon#302]
Hi,

I mentioned this in the IRC channel but I don't think anyone was around. Essentially I'm trying to get a very basic electron app to run with a neon module on windows. When I build it errors with:

```
ERROR in ./node_modules/neon-test/lib/index.js
Module not found: Error: Can't resolve '../native' in 'D:\apps\junk\test-app\node_modules\neon-test\lib'
```

OS: Windows 10 
Node version: 9.10.1
Rust Version: nigthly latest
Neon Version: 0.1.22

Steps to reproduce:

1. Clone electron quickstart & npm install from: https://github.com/pastahito/electron-react-webpack 
2. Create a local_modules directory in the electron-react-webpack tree, at the same level as node_modules
3. From within local_modules, `neon new neon-test`
4. Modify neon-test/lib/index.js and append: `exports.hello = addon.hello;`
5. neon build
6. Modify the electron app's package json to include a script for the electron-build-env ([as per this guide](https://guides.neon-bindings.com/electron-apps/)): `"neon": "electron-build-env neon build user-api",`
7. Install the local module: `npm install --save local_modules/neon-test
8. Simple test import in app/src/App.jsx: `import * as test from 'neon-test'; console.log(test);`
9. npm run neon && npm start
10. Receive error.

For record, cd'ing into local_modules/neon-test, and importing the module into a node shell works as per the guide:
```
node
require('.');
```

**Comment by jamespantalones** [comment]
@AviateX14 did you ever get this resolved? having same issue

**Comment by jamespantalones** [comment]
Ok, think i got it sorted. In my case, i was using `neon` in context of React/Electron app and the issue was I needed to add a [native loader](https://github.com/webpack-contrib/node-loader) to my `webpack` config to get this to work. I also had to adjust the `lib/index.js` file in the neon binding to export `../native/index.node` explicitly instead of just `../native`
