### ISSUE TITLE
Having multiple `pub(restricted)` syntax is experimental (see issue #32409)

### ISSUE THREAD

**Issue by theHazzard** [neon-bindings/neon#304]
Hi, I'm running a newly created project and have multiple "`pub(restricted)` syntax is experimental" errors, Im doing something wrong? I just created the project and typed "npm i"

**Comment by theHazzard** [comment]
https://pastebin.com/cJ2JLxER

**Comment by kjvalencik** [comment]
This appears to be a version of rust that was too old. Please re-open if issues persist after upgrading to latest stable.
