### ISSUE TITLE
Asynchronous creation of JsClass instance with parameters

### ISSUE THREAD

**Issue by ballwood** [neon-bindings/neon#312]
Hi,

Just made a project using neon-bindings [here](https://github.com/ballwood/snips-nlu-js), its been pretty painless...even being a newbie at rust myself! Good work 👍  

I have a few questions:

- Currently my library is completely synchronous so it blocks on the creation of a JsClass. I was wondering how I could return an instance of this class from a exported function?.
- I assume I would need to use the Task trait to do this in a thread. Whats the best way of passing arguments to this? I thought of doing something like this (ripped mostly from examples from the [tests](https://github.com/neon-bindings/neon/blob/master/test/dynamic/native/src/js/tasks.rs)):

````
struct CreateEngineTask {
    filename: String
};

impl Task for CreateEngineTask {
    type Output = SnipsNluEngine;
    type Error = String;
    type JsEvent = JsNluEngine;

    fn perform(&self) -> Result<Self::Output, Self::Error> {

        let configuration = match FileBasedConfiguration::from_path(self.filename, false) {
          Ok(conf) => conf,
          Err(_e) => panic!(format!("{}", _e)),
        };

        let _nlu_engine = match SnipsNluEngine::new(configuration) {
           Ok(engine) => engine,
           Err(_e) => panic!(format!("{}", _e))
        };

        Ok(_nlu_engine);
    }

    fn complete<'a, T: Scope<'a>>(self, scope: &'a mut T, result: Result<Self::Output, Self::Error>) -> JsResult<Self::JsEvent> {
        // create instance of JsNluEngine
        Ok(JsNluEngine::new(scope, result.unwrap()))
    }
}
````
- How would I make a method on a JsClass that has a callback as the second argument? I saw you could pass functions around but args seems to be a typed vector ([here](https://github.com/neon-bindings/neon/blob/d96c418ba86ff72c1760e472e15fe8438061b5ec/test/dynamic/native/src/js/functions.rs#L19))? Would I be able to just define the vector as JsValue and cast everything up?

Apologies if any of the q's are basic rust...again I'm a bit of a newb at it. Thanks in advance

**Comment by kjvalencik** [comment]
[This example](https://github.com/neon-bindings/examples/blob/master/event-emitter/native/src/lib.rs) demonstrates a class method that spawns a task.
