### ISSUE TITLE
Ability to Convert between JsObject and JsString?

### ISSUE THREAD

**Issue by enioluwa23** [neon-bindings/neon#316]
I have been toying around with neon modules and I have found it easy to convert between `&str` and `JsString` but have not found any equivalent ease in constructing or dealing with `JsObject`. 

My goal is to create a library to test a generic JSON `parse` and `stringify` library done in a Neon module vs in Node, but I have no pointers on converting  between an unknown `JsObject` and `JsString` using Rust types. I did some research with using a combination of [`serde`](https://github.com/serde-rs/json) and [`neon-serde`](https://github.com/GabrielCastro/neon-serde/tree/0.0.3) to help with back and forth conversion but their use requires forward knowledge about the structure of the JSON/String.

I imagine [`JsObject::get_own_property_names`](https://api.neon-bindings.com/neon/js/trait.object#method.get_own_property_names) would a step in the right direction but I am unsure how to append to a `JsString` using what is returned.

Is there a good way to marshal the conversion between these two types?

**Comment by kjvalencik** [comment]
I don't think that `neon-serde` needs to know about the structure. It can from a `JsValue`. `JsValue` is the catch-all enum that could be _any_ JS type. The same goes for `serde`. It has a `Value` type.

```rs
#[macro_use]
extern crate neon;
extern crate neon_serde;
extern crate serde_json;

use neon::js::error::{JsError, Kind};
use neon::js::{JsString, JsValue};
use neon::vm::{Call, JsResult};

fn parse(call: Call) -> JsResult<JsValue> {
	let scope = call.scope;
	let s = call.arguments
		.require(scope, 0)?
		.check::<JsString>()?;

	let o: serde_json::Value = serde_json::from_str(&s.value())
		.or_else(|err| JsError::throw(Kind::Error, &err.to_string()))?;

	let o = neon_serde::to_value(scope, &o)?;

	Ok(o)
}

fn stringify(call: Call) -> JsResult<JsString> {
	let scope = call.scope;
	let o = call.arguments
		.require(scope, 0)?
		.check::<JsValue>()?;

	let o: serde_json::Value = neon_serde::from_value(scope, o)?;
	let s = serde_json::to_string(&o)
		.or_else(|err| JsError::throw(Kind::Error, &err.to_string()))?;

	JsString::new_or_throw(scope, &s)
}

register_module!(m, {
	m.export("parse", parse)?;
	m.export("stringify", stringify)?;

	Ok(())
});
```

**Comment by enioluwa23** [comment]
@kjvalencik This is great. I did not go for using `JsValue` because I was not sure it would act the same way as `JsObject` but I guess it is feasible. Exactly what I was looking for! I will close this.
