### ISSUE TITLE
Windows error with npm i

### ISSUE THREAD

**Issue by zachrip** [neon-bindings/neon#32]
I'm running `npm i` on a new neon project as well as the word count project and I am getting the following:

```
H:\Desktop\wc-demo-master>npm i

> wc-demo@0.1.0 install H:\Desktop\wc-demo-master
> node-gyp rebuild


H:\Desktop\wc-demo-master>if not defined npm_config_node_gyp (node "C:\Users\Zach\AppData\Roaming\nvm\v4.2.3\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
  File "<string>", line 1
    'import
          ^
SyntaxError: EOL while scanning string literal
gyp: Call to 'python -c 'import os, json; print("" if u"--debug" in json.loads(os.getenv("npm_config_argv"))["cooked"] else "--release")'' returned exit status 1. while trying to load binding.gyp
```

I'm running Node v4.2.3 and Python2.7.10 - other native node modules build, which is odd because it partially seems like an issue with node-gyp as well as Python.

**Comment by andruhon** [comment]
This one seems to be related https://github.com/dherman/wc-demo/issues/5

**Comment by dherman** [comment]
I think this should be fixed by now -- it was reported back before we were testing Windows regularly and in CI. Closing but please do reopen if you see the same issue again!
