### ISSUE TITLE
is that possible to change the subdirectory name instead of `native`?

### ISSUE THREAD

**Issue by VikingMew** [neon-bindings/neon#321]
is there any options to support that?

I just test neon binding in electron and I found that I cannot import neon-hello and neon-other-hello(an exactly same except name copy) since they are both using  `../native` as require path. and electron/node will show `Error: Module did not self-register.` when I want to import both, meanwhile import either of them is working .

**Comment by kjvalencik** [comment]
Closing in favor of https://github.com/neon-bindings/neon/issues/361
