### ISSUE TITLE
compilation error on osx, symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by cdaringe** [neon-bindings/neon#337]
# problem

project fails to build with `ld: symbol(s) not found for architecture x86_64`

full `cargo build` failure output here: https://gist.github.com/cdaringe/2181b72aa7d698e32e03d40da9154324

# context

## neon version

[dependencies]
neon = { git = "https://github.com/neon-bindings/neon" } @ commit ca17a7ba278f7b02b68c745a27274db77ccb8e75

## rust

active toolchain
----------------
nightly-x86_64-apple-darwin (default)
rustc 1.29.0-nightly (e5f6498d3 2018-07-10)

## osx

high sierra

## node

10.0.0 && 10.6.0

## code

[this exact commit won't build](https://github.com/dino-dna/clipster/commit/43fcb9ede63165d0b0f6c5e739ad21d52578adde)

**Comment by kjvalencik** [comment]
This may have been resolved in one of the other fixes (#367). Please re-open if issues persist.
