### ISSUE TITLE
Build fails on Windows

### ISSUE THREAD

**Issue by hardliner66** [neon-bindings/neon#341]
I have installed all the dependencies and tried to run a compile a basic example, but i always get the following error:
`thread 'main' panicked at 'Couldn't find node_root_dir in node-gyp output.', libcore\option.rs:914:5`

I'm on Node Version v10.7.0 x64, on Windows 10 x64.

**Comment by hardliner66** [comment]
After adding some debug output to the build script, I fixed the problem. It was a misconfiguration in npm config. I accidently set the config "target" to the target triple. node gyp reads this config as target node version.

After cleaning up my node config everything worked as expected.

**Comment by mitchhentges** [comment]
For future people who run into the same error, [these instructions](https://neon-bindings.com/docs/getting-started#windows) resolved the situation for me:

From a powershell/command prompt as admin:
```
npm install --global --production windows-build-tools
```

**Comment by pharazen** [comment]
Encountering this issue even after the above mentioned fix by @mitchhentges
