### ISSUE TITLE
monorepo support

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#345]
A couple great questions brought up on Slack:

From @samrg472:

> I have a workflow problem and I’d like some advice (more rough edges :)) for a better workflow. Right now there’s a Cargo workspace setup (developing a native rust library alongside the neon bindings) with a path dependency to my library (workspaces are wonderful for this).
> 
> Unfortunately, it’s breaking auto-complete/error checking/linting (using VSCode) if I exclude the crate from my cargo members array. It works if I include the crate as a member, but it breaks cargo build (and I don’t know what neon build is doing to get it to link to node). Is it possible to get it to work in a monolith repo?

From @apendleton:

> FWIW we were also looking recently for a way to put a Rust crate and the neon bindings for it in the same repo, in a way that would let us point another Node app's package.json at it with a tarball link (`https://github.com/mapbox/<repo>/tarball/<gitsha>` or whatever), which we often use during development. npm really insists on its stuff being top-level though, so we eventually gave up and did separate repos. It does mean that development involves repeated changes in both repos though, which is mildly annoying.
> 
> but if there were a recommended workflow/pattern for that, it would be super useful

**Comment by victorhqc** [comment]
Is there any plan for this getting developed? 😄 How can I help?

**Comment by kjvalencik** [comment]
The workaround for a repo that only has a single neon module (despite multiple Rust crates) is to change the `target` directory to `native/target`.

In your root project, create a workspace `Cargo.toml` as normal. Create a cargo config at `.cargo/config` with the following:

```
[build]
target-dir = "native/target"
```

**Comment by kjvalencik** [comment]
Duplicates https://github.com/neon-bindings/neon/issues/297
