### ISSUE TITLE
Can't run cargo test

### ISSUE THREAD

**Issue by ioxua** [neon-bindings/neon#348]
Running:
```bash
$ neon new test
$ cd test/native
$ cargo test 
```
Results in ``error: linking with `cc` failed: exit code: 1``
No apparent reason. Possibly useful information:
```bash
$ node --version
v8.9.1
$ neon version
0.2.0
$ rustc --version
rustc 1.27.2 (58cc626de 2018-07-18)
```

**Comment by maackle** [comment]
Is there a chance we could have a `neon test` cli command? It would be useful to be able to write unit tests within native rust modules, I am currently trying to figure out how to do this.

**Comment by amilajack** [comment]
There's no work being done on this just yet. I do, however, have [an example that tests my neon binary](https://github.com/amilajack/disk-utility/blob/master/test/index.spec.js)

**Comment by kjvalencik** [comment]
The workaround that I use is to put most of my functionality in a separately tested library and keep my neon lib to a thin facade that is tested from javascript.

https://github.com/neon-bindings/neon/issues/345

**Comment by kjvalencik** [comment]
Another workaround is to test in release mode after a neon build. `neon build && cargo test --release`.

**Comment by kjvalencik** [comment]
I think this was fixed for legacy, but is not an issue at all in the Node-API backend.
