### ISSUE TITLE
Neon build does not run cargo update in native directory

### ISSUE THREAD

**Issue by gbenattar** [neon-bindings/neon#353]
When relying on Github packages in the Cargo.tml `git = "https://github.com[...]`, running `neon build` does not update those library (`cargo update` in `native/`).

My temporary solution for it is to add in `package.json`:

```
"scripts": {
  "install": "cd ./native && cargo update && cd .. && neon build"
}
```

Am I missing something?

Thanks!

**Comment by duncanbeevers** [comment]
@gbenattar I'm curious about this as well. I'm doing something similar

```json
{
  "scripts": {
    "build": "cargo --manifest-path native/Cargo.toml && neon build --release"
  }
}
```

It does seems like this would be generally useful as part of the build process, at least via a command-line flag.

**Comment by kjvalencik** [comment]
`cargo update` is the correct solution since `neon-cli` is deprecated in favor of direct `cargo` commands.
