### ISSUE TITLE
Allow specifying crate directory

### ISSUE THREAD

**Issue by demurgos** [neon-bindings/neon#361]
Hi,
I'd like to use the following file structure:

```
project
├── Cargo.toml
├── package.json
└── src
    ├── native
    │   └── lib.rs
    └── lib
        └── index.ts
```

It is possible to use with the API but it does not seem to be supported by the CLI.

There is an option to set the crate path:
https://github.com/neon-bindings/neon/blob/2506d2f1d70b94603877d29bc35dab6ad7d0bb97/cli/src/project.ts#L18-L19

But the build operation does not pass any options:
https://github.com/neon-bindings/neon/blob/2506d2f1d70b94603877d29bc35dab6ad7d0bb97/cli/src/ops/neon_build.ts#L7

I used this structure in the previous Neon version (before `0.2.0`) but can't find a way to make it work with the current version.

**Comment by kjvalencik** [comment]
This was resolved in the Node-API backend with `cargo-cp-artifact` and deferring to `cargo`.
