### ISSUE TITLE
Building on React-Native apps

### ISSUE THREAD

**Issue by GutteApps** [neon-bindings/neon#365]
Did anyone manage to build neon on a react-native app?

**Comment by stoically** [comment]
Might be possible with [`nodejs-mobile`](https://code.janeasystems.com/nodejs-mobile) since they support native modules and react-native.

**Comment by stoically** [comment]
Also, an alternative might be to use Rust directly in react-native, e.g. [react-native-rust-demo](https://github.com/Terrahop/react-native-rust-demo) shows how that could be accomplished.

**Comment by kjvalencik** [comment]
This should work with the Node-API backend.
