### ISSUE TITLE
[Linux] Allow building for MUSL

### ISSUE THREAD

**Issue by jjpe** [neon-bindings/neon#366]
I'd like to build an existing neon NPM module for `x86_64-unknown-linux-musl`.

If it is already possible, how can I achieve this?
And otherwise, could the functionality be added to the `neon` CLI utility?

**Comment by kjvalencik** [comment]
This should already be possible as long as you build and run against a version of node that uses musl. For example, if you use any of the alpine docker images (`node:*-alpine`, `node:lts-alpine`). Let me know if you have any issues.
