### ISSUE TITLE
scope ergonomics and a ToValue overload trait

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#37]
Some suggestions from @eddyb for making Scope objects more ergonomic:
- overloaded scope.primitive(v) to allow creating primitive JS types
- when callability becomes overloadable, this could be scope(v)
- look for other places to use overloading, like passing int/float/string/bool to various methods

**Comment by dherman** [comment]
This should be addressed by the Classes 2.0 and VM 2.0 RFCs.

**Comment by divmain** [comment]
Work tracked here:
https://github.com/neon-bindings/rfcs/issues/7
https://github.com/neon-bindings/rfcs/issues/6
