### ISSUE TITLE
"Hello, World!" Guide outdated

### ISSUE THREAD

**Issue by manuel2258** [neon-bindings/neon#370]
The Hello World Guide on the official website is outdated and does not work anymore!
Link: https://guides.neon-bindings.com/hello-world/
I guess that will result in every guide being outdated and therefor not working anymore. This is huge for newcomers, because it's the only real source to get started ...

**Comment by amilajack** [comment]
I'm working with Dave on some [new docs](https://amilajack.github.io/neon-docs/docs/en/intro). Would recommend taking a look

**Comment by manuel2258** [comment]
Thanks a lot! Gonna look into them later, however they seem atleast up to date! Without this I probably would never learn Neon, so thanks again!

**Comment by amilajack** [comment]
Update: the docs have been update. See https://github.com/neon-bindings/neon/issues/374#issuecomment-443334344

**Comment by amilajack** [comment]
@manuel2258 should this be closed?

**Comment by manuel2258** [comment]
Yes, thank you!
