### ISSUE TITLE
`neon new` should add necessary files to gitignore

### ISSUE THREAD

**Issue by amilajack** [neon-bindings/neon#373]
The following files should be gitignored when `neon new` is run:
* `target`
* `index.node`
* `artifacts.json`

**Comment by kjvalencik** [comment]
It looks like they are. Is this not working for you?

https://github.com/neon-bindings/neon/blob/master/cli/templates/.gitignore.hbs

**Comment by amilajack** [comment]
Ahh this was my mistake
