### ISSUE TITLE
🎉 PSA: NEW DOCS AND EXAMPLES 🎉

### ISSUE THREAD

**Issue by amilajack** [neon-bindings/neon#374]
This is a PSA for any newcommers to Neon. I'm working on examples and docs here:
* [docs site](https://neon-bindings.com) ([source is here](https://github.com/neon-bindings/website))
* [examples](https://github.com/neon-bindings/examples)

All the examples and docs are using the **latest version of Neon**.

**Comment by vaheqelyan** [comment]
Awesome

**Comment by jrop** [comment]
These were a lifesaver.  Thank you so much!  Any timeline to when they will be published?

**Comment by amilajack** [comment]
I'm working with @dherman to move both of these to the org. We're expecting to get these integrated this week

**Comment by amilajack** [comment]
Update: We just migrated the examples and site to the org:
The new site can now be visited at [https://neon-bindings.com](https://neon-bindings.com)
* [Examples](https://github.com/neon-bindings/examples)
* [Website Source](https://github.com/neon-bindings/website)

**Comment by vaheqelyan** [comment]
It is much better than the previous site.

**Comment by PSeitz** [comment]
Much better, but the API Link is down:
https://api.neon-bindings.com/neon/index.html

**Comment by amilajack** [comment]
@PSeitz thanks for reporting that. I'll look into it

**Comment by amilajack** [comment]
Fixed [neon-bindings.com/api/neon](https://neon-bindings.com/api/neon/)
