### ISSUE TITLE
rename Scope

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#38]
The name Scope is possibly misleading -- it could confuse people into thinking it has something to do with JavaScript scope, as opposed to being a memory management scope in Rust. Worth thinking about alternative names.

**Comment by maxjoehnk** [comment]
Why not call it MemoryScope (or MemoryContext)? This is explicit and should remove any confusion regarding the js side.

**Comment by dherman** [comment]
This will be addressed by the VM 2.0 RFC.

**Comment by divmain** [comment]
https://github.com/neon-bindings/rfcs/issues/7
