### ISSUE TITLE
Generated index.node file is too large (in file size)

### ISSUE THREAD

**Issue by kdy1** [neon-bindings/neon#383]
See https://github.com/swc-project/node-swc/releases/tag/v1.0.0-alpha.16
Each node binding file is almost 20mb.

**Comment by kdy1** [comment]
`libswc.rlib` file is 5.6MB (got after running cargo build --release)

**Comment by amilajack** [comment]
I saw https://github.com/swc-project/swc/pull/116, suggesting the issue wasn't related to Neon. If this is true, I think this should be closed
