### ISSUE TITLE
Serialized Rust version is unused in build settings

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#385]
The build settings serializes the Rust version but doesn't use it to determine whether the previous build has gone stale. I _think_ it's correct that we don't use it, since you should be able to upgrade Rust versions without needing to rebuild, but I'm not 100% sure of that. We should figure out if we need to check the Rust version or not. If not, we should stop serializing it. If so, we should start using it for the `match` comparison.

**Comment by kjvalencik** [comment]
No longer relevant with Node-API backend.
