### ISSUE TITLE
Question: async tasks/promises within classes

### ISSUE THREAD

**Issue by ddibiase** [neon-bindings/neon#386]
Are there any examples or can someone supply an example/instruction on how to use a method within a class as an async function? Assume I have a class called `Server` with a method `listen`. I want to call it this way:

    const server = new Server();
    server.listen((err, data) => {
         console.log(data);
    });

Another option is to return a promise.

    const server = new Server();
    await server.listen();

I've determined I can create an async method by creating a struct and adding the perform, complete methods. However, I'd like to use/return those within the class itself. I assume that I can define the struct and return it within the class method as a JS function?

Would Neon know to handle it from that point, if not what's the most appropriate approach?

Thanks in advance.

**Comment by kjvalencik** [comment]
@ddibiase You can create and schedule a callback from a class method in the same way as a normal function. Example:

https://github.com/kjvalencik/neon-example/blob/2ef932d42e2ce6dc7b5e11a013347de360dd134d/native/src/lib.rs#L252-L261

**Comment by ddibiase** [comment]
Thanks! Appreciate it. =)

**Comment by amilajack** [comment]
@kjvalencik how feasible do you think it would to implement async class methods for Neon? e.g.

```rust
async method() {
 // ...
}
```

**Comment by kjvalencik** [comment]
I don't think it would be too difficult to implement, but getting the API ergonomics might be tough. 

How to we delineate the three phases? Might be able to implement `Task` on an `FnOnce` that captures it's environment.
