### ISSUE TITLE
How to get current module?

### ISSUE THREAD

**Issue by uuhan** [neon-bindings/neon#390]
Help needed!

It seems that there is no way to get current module object from neon's CallContext. 
So how can I get the __filename or __dirname of current module file?

Thanks : )

**Comment by kjvalencik** [comment]
Are these exposed to native modules? It's not something I've encountered before. Is passing them in as an argument viable?

**Comment by uuhan** [comment]
> Are these exposed to native modules? It's not something I've encountered before. Is passing them in as an argument viable?

I want to expose a logger to my js code and sure I can pass the __filename to my logger.
But that means I need to pass __filename to every of my logger like this:

`const logger = new MyLogger()
  ...
  logger.info(__filename, 'fooooobarrrrrr')
`

But I think this can be done automaticly.

**Comment by uuhan** [comment]
Can I get the current Module just like the ctx.global(), maybe ctx.module() ?

**Comment by kjvalencik** [comment]
This is not possible in Node-API and would require a feature request there first.
