### ISSUE TITLE
Update template to rust 2018

### ISSUE THREAD

**Issue by theJian** [neon-bindings/neon#398]
I'm working on updating neon examples to rust 2018(https://github.com/neon-bindings/examples/issues/23). I can update neon project template to rust 2018 correspondingly. What do you think?

**Comment by dherman** [comment]
I love this idea! Are you thinking we could change the `Cargo.toml.hbs` to include the `"2018"` Edition and the `lib.rs.hbs` to remove this boilerplate?
```rust
#[macro_use]
extern crate neon;
```

**Comment by theJian** [comment]
@dherman That will be nice! We can use `use neon::prelude::*` to import all we need just like `test/dynamic/native/src/lib.rs`

**Comment by andradei** [comment]
Would love to see the PR for this merged :)
