### ISSUE TITLE
What is the difference between Call and Context?

### ISSUE THREAD

**Issue by galvez** [neon-bindings/neon#402]
```
fn myfunc(call: Call) -> JsResult<JsFoo> {
```

```
fn myfunc(mut cx: FunctionContext) -> JsResult<JsFoo> {
```

I can't seem to find docs on the difference between these two.

**Comment by samvv** [comment]
Where did you get these excerpts from? I can't seem to find a definition of the first one. Maybe it's an error in the documentation?

**Comment by kjvalencik** [comment]
@galvez There's not much of a difference. `Call` is from `0.1` of `neon` and `FunctionContext` is from the current version `0.2`.
