### ISSUE TITLE
minify spurious `improper_ctypes` warning

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#41]
In neon-sys there's a spurious compiler warning that's impossible to disable:

``` text
dherman$ cargo build
   Compiling neon-sys v0.1.5 (file:///Users/dherman/Sources/neon/crates/neon-sys)
src/buffer.rs:10:38: 10:45 warning: found non-foreign-function-safe member in struct marked #[repr(C)]: found struct without foreign-function-safe representation annotation in foreign module, consider adding a #[repr(C)] attribute to the type, #[warn(improper_ctypes)] on by default
src/buffer.rs:10     pub fn data<'a, 'b>(out: &'a mut Buf<'b>, obj: Local);
                                                      ^~~~~~~
```

I've informally confirmed with Rust team members that this is almost certainly a compiler bug, but we need to provide them with a minified test case.

**Comment by Siilwyn** [comment]
Just tried out neon, thank you for this awesome project @dherman !
Bumped into the same error, not sure how small the test case should be but just passing through a string and returning it already shows the error, [see this](https://github.com/Siilwyn/hello-neon/blob/master/native/src/lib.rs).

**Comment by dherman** [comment]
I _think_ this was fixed and can't reproduce, but please reopen if you see it happening again! I'll try to keep an eye out for it as well.
