### ISSUE TITLE
Documentation site has a lot of broken links

### ISSUE THREAD

**Issue by king-alpha** [neon-bindings/neon#413]
an example is [https://neon-bindings.com/handles-and-memory/](url).

**Comment by kjvalencik** [comment]
FYI, here is the website repo: https://github.com/neon-bindings/website

**Comment by king-alpha** [comment]
Oh okay.. Thanks, so which site did I visit then ?

**Comment by kjvalencik** [comment]
Duplicate of https://github.com/neon-bindings/website/issues/78
