### ISSUE TITLE
JsBuffer from raw parts

### ISSUE THREAD

**Issue by fudini** [neon-bindings/neon#414]
Is it possible to return JsBuffer created from raw parts similarily to `std::slice::from_raw_parts` ?

**Comment by kjvalencik** [comment]
Not directly. Would need to create the slice from the raw parts, create a buffer of the same size, and then copy the slice into the buffer.

**Comment by fudini** [comment]
The purpose is to use it to read/write shared memory / memory mapped file so copying is not an option.

**Comment by kjvalencik** [comment]
This doesn't sound like it would be sound since `JsBuffer` doesn't have safety guarantees on concurrent access.

Could a `class` wrapping a native Rust type solve this problem?

**Comment by fudini** [comment]
Of course this would be highly unsafe.
With Nan/C++ I could use this function from Nan:

```cpp
 inline MaybeLocal<v8::Object> NewBuffer(
      char* data
    , uint32_t size
)
```

Another scenario would be if some library returns a large (meaning: not-copyable) `Vec` that needs to be returned as a JS Buffer.

The `class` wrapping would mean a lot of changes for us. I was hoping for swapping the C++ addon for Rust transparently.

**Comment by kjvalencik** [comment]
Unfortunately, this is not currently a feature. Although, it could likely be added fairly easily.

https://github.com/neon-bindings/neon/blob/ac15216c4b53aaa405f88e768254f9c11114def9/crates/neon-runtime/src/neon.cc#L205-L208

**Comment by fudini** [comment]
Thanks @kjvalencik, I will have a look.

**Comment by kjvalencik** [comment]
This is covered as part of `JsBuffer::external`.
