### ISSUE TITLE
OSX Runtime Argument Problem

### ISSUE THREAD

**Issue by mudlee** [neon-bindings/neon#417]
Hi Guys!

I have a problem that my Rust integration which works on Linux, does not work on OSX.
In the Rust code I parse command line arguments with structopt and when I start the electron app, I get an error back from it which says:
```bash
error: Found argument '--inspect' which wasn't expected, or isn't valid in this context

USAGE:
    Electron [OPTIONS]

For more information try --help
```

If I run the Rust part alone, it works, and if I run it with electron on Linux, it also works.
The problem exists on OSX only.

Any idea?

**Comment by kjvalencik** [comment]
@mudlee What is injecting the `--inspect` flag? I'm not sure how neon could cause this. Is there any additional information that you can provide? Thanks!

**Comment by kjvalencik** [comment]
This issue is being closed due to missing details.
