### ISSUE TITLE
Fail when running tests: undefined reference to `v8::<>

### ISSUE THREAD

**Issue by nukeop** [neon-bindings/neon#425]
Neon version: 0.3.1
Rust version: 1.37.0
Platform: Linux

Running `cargo build` and `cargo build --release` works fine. However, when I try to run tests, I encounter a lot of errors like:

```
neon.cc:(.text+0x98): undefined reference to `v8::Isolate::Enter()'                                                                                                                                                          
          neon.cc:(.text+0xa7): undefined reference to `v8::HandleScope::HandleScope(v8::Isolate*)'                                                                                                                                    
          neon.cc:(.text+0xc3): undefined reference to `v8::HandleScope::CreateHandle(v8::internal::Isolate*, v8::internal::Object*)'
```

This continues for many more lines. Any idea how to mitigate this?

**Comment by kjvalencik** [comment]
One workaround is to build with neon and run tests in release mode.

https://github.com/neon-bindings/neon/issues/348#issuecomment-522626004

**Comment by nukeop** [comment]
I tried that, but it didn't help, I'm still getting the same error.

**Comment by nukeop** [comment]
Ok, I found that doing what you suggested in the other post (moving independent functionality to a separate crate) works best.

**Comment by kjvalencik** [comment]
Putting some more thought into this, I think it's a somewhat more complicated topic. This isn't working because `cargo test` builds a binary and part of that is the final linking. That linking would require `libnode` and `libv8` to work.

I'll have to put some more thoughts into this. For now, the only suggestion I have is to put non-neon code into a separate crate where `cargo test` can be used or to only execute tests from `node`.

**Comment by nukeop** [comment]
How long, approximately, does it take to build node as a shared library? Do you think it's feasible to do it in CI?

**Comment by kjvalencik** [comment]
@nukeop This hasn't been released yet, but it should be fixed on master.

**Comment by nukeop** [comment]
Thanks, great news.
