### ISSUE TITLE
automated tests that `neon new` creates valid programs

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#43]
There should be an automated test that a vanilla project created by `neon new` successfully compiles by just running the standard `npm install`.

/cc @mmun

**Comment by lp** [comment]
is it possible this test is already mostly covered by the test/cli/src/acceptance/new.ts test suite?

**Comment by kjvalencik** [comment]
It is not covered. However, as part of [this RFC](https://github.com/neon-bindings/rfcs/pull/36), `neon-cli` will be deprecated. Anything related to it that isn't necessary maintenance likely isn't needed.

We _will_ likely want this test to be part of the new CLI for `npm init neon`.

**Comment by dherman** [comment]
Since `neon new` is deprecated, I'm closing this as not worth it.
