### ISSUE TITLE
Packaged Electron Inclusion Error

### ISSUE THREAD

**Issue by joshuef** [neon-bindings/neon#430]
So after following the Electron guide on the main website, we have a module working well _unpacked_.

We're attempting to packager this now (full repo here: https://github.com/maidsafe/safe_browser/tree/NewDay )

But on load it's attempting to access the files from the unpacked location:

```
[2019-08-30 12:18:07.560] [error] whoops! there was an uncaught error:
[2019-08-30 12:18:07.560] [error] {"message":"Cannot open /Users/josh/Projects/safe/forks/browser/node_modules/safe_nodejs/native/index.node: Error: dlopen(/Users/josh/Projects/safe/forks/browser/node_modules/safe_nodejs/native/index.node, 1): image not found","name":"Error"}
[2019-08-30 12:18:07.561] [error] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
```

Electron rebuild works fine, I've tried with `electron-build-env` also, as per the site, but nothing changes this.

I cannot for the life of me see where this is being coded into the packaged electron app (using electron builder), and I've tried the ususal suspects of no asar, or manually including files, but it's not a module resolution error.

I am currently stumped, so any pointed anyone may have would be verrrry welcome!

----

Otherwise thanks for all the great work on neon, so far it's been great to use, so I'm hoping we can get over this hurdle!

**Comment by joshuef** [comment]
This is looking like it's _nothing to do with neon at all_. :| Apologies for confusion.

For those interested in neon in electron, this seems to be happening due to `.node` file handling in webpack, and their suggested loader is writing these hard paths... There's a [few solutions suggested in this issue](https://github.com/webpack-contrib/node-loader/issues/12), alternate loaders etc. 

I haven't got any of them working as yet, but I'll report back here when I do.

Closing in the meantime as not actually a neon issue 👍

**Comment by kjvalencik** [comment]
Thanks! This seems like it could be a useful thing to document once you figure it out. Electron + Neon is a powerful combo and we could use some improvement documenting the complexities.

**Comment by joshuef** [comment]
This loader was needed for us w/ webpack: https://github.com/smt116/node-native-ext-loader

With your neon as a dependency (not dev dep!), it shoud automatically be unpacked/resolved in the packaged appliction in a relative fashion 👍 

This is working well on both Mac and Linux. And _should_ also go for windows (though windows has its own issues: #404 )
