### ISSUE TITLE
Consider CARGO_TARGET_DIR

### ISSUE THREAD

**Issue by splix** [neon-bindings/neon#450]
It would be useful to have the ability to use a different directory for cargo build. 

The problem I faced is that `node-pre-gyp package` tries to pack everything under `binary/module_path: "./native"`, including `native/target` directory with all intermediary files. So I delete it before making pre-gyp, it makes a clean archive, but at this case I miss the ability to cache the directory between builds. 

By specifying `CARGO_TARGET_DIR` env I can tell Cargo to use different dir, it works, but at the last step neon fails to make `native/index.node`

**Comment by kjvalencik** [comment]
Correctly finding the target dir is fixed on master and will be included in the next release.
