### ISSUE TITLE
FFI style callbacks.

### ISSUE THREAD

**Issue by enzomd** [neon-bindings/neon#451]
Is it possible to pass a JS callback function to Neon Rust code, and have it be **called many times for events that originate from the Rust code**?

Something with the same meaning as this:
https://github.com/node-ffi/node-ffi/wiki/Node-FFI-Tutorial#callbacks

```js
var ffi = require('ffi');

// Interface into the native lib
var libname = ffi.Library('./libname', {
  'setCallback': ['void', ['pointer']]
});

// Callback from the native lib back into js
var callback = ffi.Callback('void', ['int', 'string'],
  function(id, name) {
    console.log("id: ", id);
    console.log("name: ", name);
  });

console.log("registering the callback");
libname.setCallback(callback);
console.log('done');

// Make an extra reference to the callback pointer to avoid GC
process.on('exit', function() {
  callback
});
```

I think this is the same issue as these ones:

**Related issues**
- https://github.com/neon-bindings/neon/issues/369
- https://github.com/neon-bindings/neon/issues/382

Has any progress been made on enabling this since those issues?

**Comment by kjvalencik** [comment]
This will be possible with the `EventHandler` API.

* [RFC](https://github.com/neon-bindings/rfcs/blob/master/text/0025-event-handler.md)
* [Implementation PR](https://github.com/neon-bindings/neon/pull/375)

**Comment by kjvalencik** [comment]
It's been merged!
