### ISSUE TITLE
cli should not discard cache files unrelated to neon

### ISSUE THREAD

**Issue by kdy1** [neon-bindings/neon#452]
Currently neon rebuilds whole dependency crates when nodejs version is changed, but it should not.

See: https://travis-ci.com/swc-project/node-swc/jobs/247021379

Related: #384, #388. 

Related code:

https://github.com/neon-bindings/neon/blob/44e67e40af2fff82d8dd9fa7ee45e670d8c1fe2b/cli/src/project.ts#L48-L51

**Comment by kjvalencik** [comment]
I wonder if the entire state file can be eliminated by moving the values to `if-env-changed` in `build.rs`. That would allow `cargo` to be smart about what it rebuilds.

For your CI use case, `sccache` may also be helpful.

**Comment by kjvalencik** [comment]
While this is still an issue, I am closing since `neon-cli` is deprecated.
