### ISSUE TITLE
Use JsBuffer with Task

### ISSUE THREAD

**Issue by xVanTuring** [neon-bindings/neon#460]
So I'm working on a project with need the Task feature, so I add a simple BackgroundTask , which will impl Task
``` rust
struct BackgroundTask<'a> {
    buf: &'a [u8],
    // extra
}
```
Here, because my rust native library would use the `buf: &'a [u8]` to calc a palette, so I pass a `JsBuffer` to main function, and extract the array, init the Task struct, call function `schedule` 
``` rust
fn image_palette(mut cx: FunctionContext){
    let buf = cx.argument::<JsBuffer>(0)?;
    let slice = cx.borrow(&buf, |data: neon::borrow::Ref<neon::types::BinaryData>| {
        data.as_slice::<u8>()
    });
    let task = BackgroundTask {
        // extra
        buf: slice,
    };

    task.schedule(callback);
}
```
And, it won't compile, I find the [Fix](https://github.com/kjvalencik/neon/commit/72df0b227fede09cb36d8bb1da607bb9cafc4162) about the lifetime should be `'static`.

So how can I fix it.(I'm kind of new to rust lang...)

Thanks.

**Comment by kjvalencik** [comment]
The task struct must be `Send` and only the `'static` lifetime is valid for `Send`. Most of the time it won't be helpful to take references in a `Task`.

My recommendation is to clone the byte slice into a new vector and store that on the background task.

```rust
struct BackgroundTask {
    buf: Vec<u8>,
    // extra
}

fn image_palette(mut cx: FunctionContext) -> JsResult<JsUndefined> {
    let buf = cx.argument::<JsBuffer>(0)?;
    let buf = cx.borrow(&buf, |data| data.as_slice().to_vec());
    let task = BackgroundTask {
        buf,
        // extra
    };

    Ok(cx.undefined())
}
```

**Comment by xVanTuring** [comment]
Wow, thanks for your reply! I tried your first solution, it worked. \
Also it would cost too much time to copy a large image, and I'm  confused about your `JsClass` way, is there any demo code.

Thanks.

**Comment by kjvalencik** [comment]
Not exactly, but the [Class Factory](https://github.com/neon-bindings/examples/blob/master/class-factory/native/src/lib.rs) example is similar. Although, that's not really appropriate for your use case.

The `to_vec()` method *is* copying the data. Unless your images are giant, this may be acceptable. If you really need to avoid copying the data you can use a raw pointer and `impl Send`, but that's getting into `unsafe` rust and outside the scope of a github issue. It also gives up some of the guarantees.

**Comment by xVanTuring** [comment]
Understood!  Thanks for your help!

**Comment by OR13** [comment]
Sorry for posting on such an old issue, but the snippet in :

https://github.com/neon-bindings/neon/issues/460#issuecomment-546597677

Did not work for me in neon `version = "0.10"`.

An AI told me to use:

```
use neon::prelude::*;
use std::slice;

// Function to convert JsArrayBuffer to Vec<u8>
fn array_buffer_to_vec(mut cx: FunctionContext) -> JsResult<JsArray> {
    // Get the argument at index 0, which should be the JsArrayBuffer
    let buffer: Handle<JsArrayBuffer> = cx.argument::<JsArrayBuffer>(0)?;

    // Get the contents of the JsArrayBuffer
    let data: Vec<u8> = cx.borrow(&buffer, |data| {
        let slice = slice::from_raw_parts(data.as_ptr(), data.len());
        slice.to_vec()
    });

    // Convert the Vec<u8> to a JsArray
    let js_array = JsArray::new(&mut cx, data.len() as u32);
    for (i, &byte) in data.iter().enumerate() {
        let js_byte = cx.number(byte as f64);
        js_array.set(&mut cx, i as u32, js_byte)?;
    }

    Ok(js_array)
}
```

which also did not work... I get the same error:

```
error[E0599]: no method named `borrow` found for struct `CallContext` in the current scope
  --> src/lib.rs:17:24
   |
17 | let data: Vec<u8> = cx.borrow(&buffer, |data| {
   |                     ---^^^^^^ method not found in `CallContext<'_, JsObject>`
```

I'm not a rust dev, just trying to wrap an existing rust program for use in browser js land... sorry for noob post.

**Comment by kjvalencik** [comment]
The API for borrowing buffers has changed. It's now under the `TypedArray` trait.

https://docs.rs/neon/1.0.0-alpha.4/neon/types/buffer/trait.TypedArray.html
