### ISSUE TITLE
How to expose rust enum to js enum?

### ISSUE THREAD

**Issue by manhnt9** [neon-bindings/neon#462]
Neon seems not supporting enum exporting.
I'd like to export rust enum to js.
Then js can use that enum to call a rust exported function taking enum as parameter.

**Comment by kjvalencik** [comment]
There are a couple of different ways, but the most straightforward way is to serialize the enum as a `String`. You can either do this with `Serde` or manually with a `match`.

**Comment by tracker1** [comment]
Not sure there really is a good canonical match... for simple values, you could just use the underlying string, but with more complex typed enum values, it may not be a 1:1 match.

`std::option::Option` for instance.  Option<T> Some(TValue) ... what if T effectively is a string?

Probably the most appropriate serialization would be...

`{
  "rustEnum": "std::option::Option",
  "key": "Some",
  "values": [eJsonSerializedTValue]
}`

This would support complex enums... Just a thought on this...

**Comment by manhnt9** [comment]
Thanks @kjvalencik and @tracker1. Since my enum currently doesn't have a lot of values, I decided to expose multiple functions for each enum case instead of a single function taking enum for input.

For future cases I may use Serde to serialize options since it's a very portable way, I can pass those data around too. I think this issue can be concluded.
