### ISSUE TITLE
call error in electron app

### ISSUE THREAD

**Issue by mantou132** [neon-bindings/neon#465]
example repo: https://github.com/mantou132/electron-neon-test

Reproduce:
```bash
git clone https://github.com/mantou132/electron-neon-test
cd electron-neon-test
npm i
node . # Running normally in nodejs
npm run build:rs
npm start
```
output:
```
Electron(60776,0x1180815c0) malloc: *** error for object 0x7fab5d58d440: pointer being freed was not allocated
Electron(60776,0x1180815c0) malloc: *** set a breakpoint in malloc_error_break to debug
```

env:
```
node -v
v12.3.1
npx electron -v
v7.1.1
npx electron -a
75
```

**Comment by kjvalencik** [comment]
This project looks like there are a few layers of indirection that aren't tested (builds a package which has a symlink and a separate `install`).

Are you able to reproduce with a more straightforward example?

If you set `export RUST_BACKTRACE=1` do you get any additional details? I.e., are you able to confirm that this is coming from neon code and not `enigo` or another dependency?

**Comment by mantou132** [comment]
@kjvalencik 
[enigojs](https://github.com/mantou132/enigojs/) is the enigo nodejs binding I created with neon.
enigo is the branch of my fork, but the code is now the same as the source repository.

can compile normally, set `export RUST_BACKTRACE=1` can't get any other information.

correct execution in the nodejs environment, the problem may be in electron?

**Comment by mantou132** [comment]
The same error was found in node
