### ISSUE TITLE
Context-aware modules support

### ISSUE THREAD

**Issue by MOZGIII** [neon-bindings/neon#470]
I'd like to build a context-aware node module. I don't think there's a way to achieve that currently.
Relevant refs:
- https://nodejs.org/api/addons.html#addons_context_aware_addons
- https://github.com/electron/electron/issues/18397

**Comment by dherman** [comment]
@MOZGIII This is an awesome point and I'd love to make progress on it! I'm curious if you have tried this out at all—I thought about it a bit and I think we may have some of the pieces in place already, maybe accidentally. :P But it's certainly not tested and I could believe it doesn't work. We should probably create some test cases to work from.

**Comment by valerauko** [comment]
I think I'm trying to do the same as MOZGIII above: use a neon-compiled crate from electron. Judging from the warnings electron throws at me, it seems that neon-generated modules aren't context aware.

I don't know node or neon well enough to figure out what to change but I'll happily help debug it if you tell me what to tweak where.

**Comment by valerauko** [comment]
Repro: take @amilajack's electron app example at https://github.com/neon-bindings/examples/tree/master/electron-app (loads the package and launches electron) and https://github.com/amilajack/neon-hello (the actual rust/neon code)

Update the electron version to 9.0.3 (though even with version 7 a warning is shown about non-context-aware modules) and it stops working.

Then if you set `app.allowRendererProcessReuse = false` in the main.js file, it starts working again -- with a nasty warning.

**Comment by rousan** [comment]
@kjvalencik @dherman 
Is there any progress on it?

**Comment by kjvalencik** [comment]
@rousan While we would be happy to accept a PR to resolve this issue; we have decided to focus most of our efforts on delivering N-API since it will inherently resolve this issue.

**Comment by rousan** [comment]
I will be happy to contribute on my spare time.

**Comment by kjvalencik** [comment]
I did a little investigation and while the effort to do this _safely_ is very minimal (it only requires marking the module as context aware), being able to perform this _without leaking memory_ is much higher.

**Comment by MOZGIII** [comment]
Could you elaborate please?

**Comment by kjvalencik** [comment]
Nothing inside neon won't work in a context aware module. For example, the global class map is still appropriately scoped.

However, neon does not have any mechanism to clean-up memory on long lived objects. For example, that class map or Js functions that wrap rust functions.

**Comment by exellian** [comment]
Any progress on this topic?

**Comment by kjvalencik** [comment]
@exellian The napi backend is context aware. We have prioritized finishing the napi backend above completing this for the legacy backend.

**Comment by exellian** [comment]
Ok great

**Comment by kjvalencik** [comment]
Closing since the Node-API backend has been context aware since it was introduced.
