### ISSUE TITLE
Support async/await in Rust 1.39+

### ISSUE THREAD

**Issue by jjeffcaii** [neon-bindings/neon#481]
Does neon support `async/await`? It seems that `neon build` compile failed.

```rust
#[macro_use]
extern crate neon;
extern crate futures;

use futures::future;
use futures::executor::block_on;
use futures::prelude::*;

use neon::prelude::*;

fn ping(mut cx: FunctionContext) -> JsResult<JsString> {
    // compile ok
    block_on(future::ok::<i32, i32>(1));

    // compile failed
//    --> src/lib.rs:25:14                                          
//    |                            
// 25 |     block_on(async {                                       
//    |              ^^^^^ not found in this scope                 
    block_on(async {
    });


    Ok(cx.string("pong"))
}
```

**Comment by kjvalencik** [comment]
This should work. Neon doesn't need to support async specifically because it is a language feature (although there are improvements that could be made to make it ergonomic and fast).

Can you run `rustc --version`?

**Comment by kjvalencik** [comment]
This should work. Neon doesn't need to directly support async/await because it is a language feature (although, we would like to make improvements to ergonomics and performance).

What rust version are you using?

**Comment by jjeffcaii** [comment]
Thanks! My local rust version is 1.40.

**Comment by adumbidiot** [comment]
Are you using the 2018 edition?

**Comment by jjeffcaii** [comment]
I found the solution. The `Cargo.toml` which generated by `neon new` missing `edition = "2018"`. I've added it and it works. Thanks! @adumbidiot @kjvalencik
