### ISSUE TITLE
Drop::drop not being called

### ISSUE THREAD

**Issue by jrop** [neon-bindings/neon#509]
Hello!  Thank you for an amazing library, first of all!

I have a question regarding Rust <=> object lifecycle management: is `Drop::drop` guaranteed to be called on Rust objects exposed to JS?  In a simple test, I cannot seem to fabricate an example where `drop` gets called on my object:

**lib.rs**:
```rust
struct NeonObj(...);
impl Drop for NeonObj {
    fn drop(&mut self) {
        // never called
        println!("NeonObj::drop");
    }
}

declare_types! {
    pub class JsObj for NeonObj {
        init(mut cx) {
            Ok(NeonObj(...))
        }
        method sayHello(mut cx) {
            ...
        }
    }
}
register_module!(mut cx, {
    cx.export_class::<JsObj>("JsObj")
});
```

**index.js**:
```js
const {JsObj} = require("../native");

let x = new JsObj();
// ...do stuff with `x`...
x = null;
global.gc();

// give the GC time to "work"?  Not sure if this is necessary...
setTimeout(() => console.log("exiting..."), 30000);
```

**Comment by jrop** [comment]
Never mind: it must be some more complex interaction with my _actual_ code.  When I create a simplified project from the above snippets, the `drop` works.

Perhaps I am on a different version of neon or something.

**Comment by kjvalencik** [comment]
There may be a leaked reference in javascript. One way to check for a leak is to use the chrome debugger and perform a heap dump. You can analyze the results for strong references.

Also, I've found in your example, letting then object be freed by limiting the scope to a function (+calling gc afterwards) can work a little better than assigning null to the variable.

**Comment by jrop** [comment]
@kjvalencik Sounds good.  The JS GC is a black-box to me, and I have observed odd behavior in the past with it, but that is likely due to my lack of knowledge with it.  Thanks for the info!
