### ISSUE TITLE
Linking issue on Windows with non-trival C/C++ code

### ISSUE THREAD

**Issue by xxuejie** [neon-bindings/neon#510]
When we are using neon to build Rust crates that contain non-trivial C code, such as [rust-rocksdb](https://github.com/rust-rocksdb/rust-rocksdb). Errors like the following would occur:

```
liblibrocksdb_sys-533a58a856d9850c.rlib(iterator.o) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in libneon_sys-80b65e28326c6273.rlib(neon.obj)
```

For the full output of errors, please refer to this [Travis build](https://travis-ci.com/github/nervosnetwork/lumos/jobs/320426441).

This could be traced back to a gyp issue: https://github.com/nodejs/node-gyp/issues/330. And could be fixed by tweaking the gyp config when building neon-sys: https://github.com/xxuejie/neon/commit/6e246f2edc37dbde9477743acd15ebefd3de99c2

So my question is: is it possible to alter gyp config, and use `/MD` build by default? I can open a PR if that is a legit change to you. Or can we provide an option to tweak gyp when needed?

**Comment by federico-terzi** [comment]
I'm currently facing the same problem

**Comment by Brooooooklyn** [comment]
Please try https://github.com/Brooooooklyn/napi-rs.
This library doesn't depend on `node-gyp`.
So if you can easily use this library, I will try to bring the `build infrastructure` in it to neon.

**Comment by retep998** [comment]
To be more accurate, the build script will have to read the `CARGO_CFG_TARGET_FEATURE` environment variable and check if it contains `crt-static` to determine which `RuntimeLibrary` to use.

**Comment by kjvalencik** [comment]
Closing since this is an issue building `rocksdb` and not Neon.
