### ISSUE TITLE
Can't build on Windows 8: spawn cargo ENOENT

### ISSUE THREAD

**Issue by roman-r-m** [neon-bindings/neon#522]
I'm trying to build a simple project that's generated with `neon new` and it fails with
```
Error: spawn cargo ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

I understand it means that neon could not run cargo but is there a way to see what exactly it tried to run? I saw in the code references to some log but can't find a way to enable it.

cargo is installed and I can run it without any issues from the same cmd line window I run `neon build` from.

**Comment by kjvalencik** [comment]
This error indicates that cargo couldn't be found on the PATH. It's odd that it can't be found. Do you have it set manually? Maybe the neon cli isn't inheriting the path.

**Comment by roman-r-m** [comment]
> Maybe the neon cli isn't inheriting the path.

Not neon but the process it spawns to run cargo.

According to this https://github.com/nodejs/node/issues/12986#issuecomment-301102566 spawned process inherits parent's process env by default but it seems that neon overrides the options and does not set env.

**Comment by roman-r-m** [comment]
As a workaround I added cargo dir to the global PATH variable.
It's not ideal as the global path now contains `C:\Users\XXX\.cargo\bin` but at least it works

**Comment by retep998** [comment]
Windows has the notion of *user specific* global environment variables, and any additions to that user specific `PATH` will be joined together with the system wide `PATH`.

**Comment by kjvalencik** [comment]
No `env` is being sent to the child process. It should be defaulting to `process.env`. I'm not sure why this would happen.

Is this issue happening for both `neon build` right on the command line as well as `neon build` in an npm script? E.g., the default `npm install` on a fresh project.

**Comment by roman-r-m** [comment]
> No `env` is being sent to the child process. It should be defaulting to `process.env`. I'm not sure why this would happen.

The default value is only used if `spawn` is called with 2 args, then the 3rd arg will have the default value as described here: https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options

Neon seems to pass the 3rd arg (options):
https://github.com/neon-bindings/neon/blob/44e67e40af2fff82d8dd9fa7ee45e670d8c1fe2b/cli/src/async/child_process.ts#L6
so the defaults are not applied.

**Comment by roman-r-m** [comment]
> Is this issue happening for both `neon build` right on the command line as well as `neon build` in an npm script? E.g., the default `npm install` on a fresh project.

I think both but I'm only sure about the 1st case (`neon build` from the command line).

**Comment by kjvalencik** [comment]
@roman-r-m It should use `process.env` as long as the options object doesn't provide a truthy `env` property.

https://github.com/nodejs/node/blob/f1ae7ea343020f608fdc1ca77d9cdfe2c093ac72/lib/child_process.js#L517

**Comment by roman-r-m** [comment]
Yes, looks like it should work. Not sure why I'm still seeing the error - I'll try to look into this on the weekend.

**Comment by c-nixon** [comment]
I ran into this error when I had 2 entries in my path variable for $HOME/.cargo/bin

**Comment by That3Percent** [comment]
I also have this error, but on OSX not Windows. Like @c-nixon, I also had 2 entries for cargo in the $PATH but removing one did not resolve the issue for me.

**Comment by glebpom** [comment]
The same problem happens for me on OSX. Any updates on how to fix it?

**Comment by kjvalencik** [comment]
This is likely still an issue, but I am closing since it is related to the `neon-cli` which is deprecated.
