### ISSUE TITLE
Question: Array of functions

### ISSUE THREAD

**Issue by xxczaki** [neon-bindings/neon#523]
I'm currently in process of rewriting a TypeScript module to Rust (using Neon). It's pretty simple:

```ts
class Name {
	constructor(private readonly plugins?: ReadonlyArray<(expression: string) => Promise<string>>) { }

	async parse(expression: string): Promise<any> {
		// ...
	}
}
```

Your documentation has a pretty good example of how to create classes (and therefore constructors, methods etc.), but I'm not sure how I can type an array of functions (`ReadonlyArray<(expression: string) => Promise<string>>`) in Rust :cry:

**Comment by kjvalencik** [comment]
Are these functions created in rust or in javascript? Example of creating an array: https://github.com/neon-bindings/neon/blob/master/test/dynamic/native/src/js/arrays.rs

**Comment by xxczaki** [comment]
@kjvalencik Thanks for a quick reply. These functions are created in JavaScript.

**Comment by kjvalencik** [comment]
Closing since I _think_ the question was answered.
