### ISSUE TITLE
Move CI to GitHub Actions

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#528]
GitHub Actions seems like a great fit for this project, since we have tests across Linux, Mac, and Windows, and today that requires maintaining two different CI setups with Travis and Appveyor.

If someone wants to help us out with this, I'll be happy to work with you to get you the credentials you need to set it up! Hit me up on our [community slack](https://rust-bindings.slack.com/) (get your [auto-invite here](https://rust-bindings-slackin.herokuapp.com/))--my Slack handle is `dherman`.

**Comment by lhr0909** [comment]
Hey! I am trying to see if anyone has picked up the github actions work yet, I have some experience setting up neon builds on GitHub - https://github.com/xanthous-tech/dgraph-js-native . Hope to be able to contribute.

**Comment by kjvalencik** [comment]
@lhr0909 It's still up for grabs and help would be appreciated!

I had started a branch with this work back when actions was still in beta, but, at the time actions didn't trigger on PRs from forks which was a show stopper for an open source project.

https://github.com/neon-bindings/neon/tree/gh-actions

**Comment by dherman** [comment]
Thank you, @lhr0909! Keep us posted on your progress and let me know when you need my assistance getting things set up with proper credentials, etc.
