### ISSUE TITLE
Convert vector<u8> into JsBuffer

### ISSUE THREAD

**Issue by MoMannn** [neon-bindings/neon#535]
As the title says I want to convert a stream (vector of u8) into JsBuffer but cannot find any way to do so.

**Comment by kjvalencik** [comment]
A reference to the underlying bytes of a `JsBuffer` can be grabbed with the `Borrow` API.

https://docs.rs/neon/0.4.0/neon/context/trait.Context.html#method.borrow

```rust
pub fn write_buffer(mut cx: FunctionContext) -> JsResult<JsBuffer> {
    let message = "Hello, World".as_bytes();
    let mut buf = cx.buffer(message.len() as u32)?;
    
    cx.borrow_mut(&mut buf, |data| {
        data.as_mut_slice::<u8>().copy_from_slice(message)
    });

    Ok(buf)
}
```

**Comment by MoMannn** [comment]
Yep this works with the exception that I had to use: 
`let mut buffer = JsBuffer::new(&mut cx, message.len() as u32)?;` instead of ` cx.buffer(message.len() as u32)?;` otherwise it did not work.
