### ISSUE TITLE
Linking static/dynamic library issue

### ISSUE THREAD

**Issue by cpcdoy** [neon-bindings/neon#538]
Hi,

First of all, thanks for the great library, it's great being able to combine Rust and the latest Node.js 🙂

_Note: I've opened an issue with the `tch-rs` library [here](https://github.com/LaurentMazare/tch-rs/issues/227) about the same problem and the author suggested to check with you here._

Now here's the issue: I've been trying to build a UI using the Neon library to expose a deep learning model in a user-friendly manner but Neon doesn't seem to support linking modules with my app that are static libraries, like the crate `tch-rs`.

Here's the error I get after a `neon build --release`:

`= note: libneon_sys-6772eb4daabce052.rlib(neon.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in libtorch_sys-7a762622fab88f97.rlib(torch_api.o) libcpmt.lib(raisehan.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in libtorch_sys-7a762622fab88f97.rlib(torch_api.o) Creating library C:\Users\###\projects\rust-bert-viz-neon\test\bert-viz\native\target\x86_64-pc-windows-msvc\release\deps\bert_viz.dll.lib and object C:\Users\###\projects\rust-bert-viz-neon\test\bert-viz\native\target\x86_64-pc-windows-msvc\release\deps\bert_viz.dll.exp LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library C:\Users\###\projects\rust-bert-viz-neon\test\bert-viz\native\target\x86_64-pc-windows-msvc\release\deps\bert_viz.dll : fatal error LNK1319: 2 mismatches detected`

This most likely means that Neon is trying to link my Rust module dynamically but the library `tch-rs` is linked statically.
Is there any way to work around that using Neon?
 
Thanks a lot.

**Comment by SergejJurecko** [comment]
neon/crates/neon-sys/native/binding.gyp

VCCLCompilerTool sections need to have RuntimeLibrary set to 2.

**Comment by samizdatco** [comment]
I've recently run into this issue as well. 

Is @SergejJurecko’s suggestion something that could be added to neon’s default configuration or is this situation enough of an edge-case that users should modify binding.gyp as part of a build-script when generating windows libraries?

**Comment by kjvalencik** [comment]
@samizdatco We would be willing to accept a thoroughly tested patch, but I'm not familiar enough with the edges of Windows builds to know if this change would cause issues for other environments.

The neon team most likely will _not_ be working on fixing this because we are getting pretty close to delivering the N-API backend for Neon. The N-API backend won't require node-gyp. Given that N-API is *much* better than bespoke bindings and unlocks a lot of important features like pre-builds, we will most likely be moving the node-gyp/legacy backend into maintenance mode.

**Comment by samizdatco** [comment]
> I'm not familiar enough with the edges of Windows builds to know if this change would cause issues

You and me both :)

That's exciting news that the N-API backend is around the corner though! I'll see if I can find a stopgap solution to this in the meantime...

**Comment by kjvalencik** [comment]
The Node-API backend is now the default. Closing this issue.
