### ISSUE TITLE
Docs should explain the use of `constructor` in classes beyond `init`

### ISSUE THREAD

**Issue by bitrocks** [neon-bindings/neon#557]
I am reading the code https://github.com/geovie/neon/blob/4f3b1f21b38a95f1b0d67698eb5a38b04fca4eea/test/dynamic/native/src/js/eventhandler.rs#L19 here, and wondering what's the difference between `init` and `constructor`, and can't I just use `init` do all the work here?

**Comment by kjvalencik** [comment]
This example is somewhat contrived and you are correct that this example could be entirely accomplished with `init`.

`init` is required. It creates the rust struct that will be wrapped by the class. `constructor` is optional and is called _after_ the class is constructed. This gives an opportunity to perform actions that require access to `this`. For example, if you would like to assign a property to `this` at construction time, it would need to happen in `constructor`.

Order of operations:

1. User invokes `new MyClass()`
1. `init` is called to create the Rust struct
1. Neon internally creates the class and wraps the Rust struct
1. (Optional) `constructor` callback is invoked with access to the newly created class as `this`

Thanks for the feedback. I'll leave this issue open as a documentation issue.

**Comment by bitrocks** [comment]
Thanks!
