### ISSUE TITLE
create-neon CLI tool

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#565]
Create the `create-neon` CLI tool so users can create Neon projects via `npm init neon`.

----

~This is a tracking issue for the three neon-create-* CLI tools we'll need in order to enable developers to use `npm init neon-*` instead of `neon new`.~

- ~`neon-create-app` (#566)~
- ~`neon-create-lib` (#567)~
- ~`neon-create-electron-app` (#568)~

**Comment by kjvalencik** [comment]
We will use `process.versions.napi` to get the current N-API version to default in `Cargo.toml`. We should also add placeholder N-API versions to `neon` to prevent `create-neon` from unexpectedly breaking when a new version is released.

**Comment by dherman** [comment]
After a bunch of discussion and prototyping, we have figured out a few key simplifying changes we can make to how Neon projects work, which will allow us to simplify the `npm init` story to just one single tool: `create-neon`, thanks to a few things:

- With N-API, there's no longer any special build logic needed for different types of projects (e.g. Electron vs plain Node).
- We have eliminated the `index.js` wrapper and the concept that a Neon project includes arbitrary wrapping logic in pure JS. A Neon project is just a `.node` plugin that you can embed anywhere, and the developer can decide what, if any, wrapping they want to do on the outside of that.
- We are streamlining the directory layout to be much flatter as a result.
- All of this makes for a simpler to understand mental model of Neon projects, and a simpler CLI UX.

**Comment by dherman** [comment]
Work items for this issue:
- Nail down the directory layout, which is mostly in shape in the [CLI RFC](https://github.com/neon-bindings/rfcs/pull/36)
- Need logic for inferring NAPI version (see https://github.com/neon-bindings/neon/issues/565#issuecomment-780720630)
- Need to update the templates based on that directory layout

**Comment by dherman** [comment]
Implemented in #690.
