### ISSUE TITLE
Cargo build wrapper

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#571]
Cargo doesn't quite have the extensibility we need to use a cargo command directly to build and generate an `index.node` file (we tried using `cargo rustc`, but unfortunately that circumvents and breaks the Cargo caching logic for rebuilds). So we still need a small wrapper for doing Neon builds, but we can make the UX feel comfortable by putting this in an npm script, so users can just run the familiar `npm run build` command or even `npm I`.

To make that work, we need to create a small npm CLI, called `cargo-build-and-copy`, which will be automatically included as a `devDependencies` entry by the `npm init neon` script, and will be used by the `"build"` script in the `"scripts"` section of the generated `package.json`.

@kjvalencik did an [experimental prototype](https://github.com/neon-bindings/create-neon/pull/1) with a slightly different design, where the script on did a build but output the filename so you could pipe it to a `cp` command; however this won't quite work because build failures will not propagate a non-zero error code correctly. So instead we want a single script that does the build and copies.

Specifications for this CLI tool:

- name: `cargo-build-and-copy`
- namespace:
  - can be a separate repo in GH: `neon-bindings/cargo-build-and-copy`
  - should not be under the `@neon` namespace in npm since it's really not specific in any way to Neon
- wrapper calls `cargo build` with `--message-format=json-render-diagnostics` to extract the generated filename (which will vary by OS)
- wrapper takes a command-line argument to specify the target path to copy the file to
- wrapper copies the generated file from the build to the specified target path
- user can pass additional flags at the end of the CLI tool's arguments to pass through to the generated `cargo build` command

old issue description:
~Make the basic template for a Neon project require no post-processing logic so that we can use `cargo build` directly. This will probably require a change to the JS code in the project template to know the right filename of the DLL to load, since cargo won't generate a file called `*.node`.~

**Comment by dherman** [comment]
A sketch of what the `package.json` would look like:

```
"scripts": {
    "install": "npm run build",
    "build": "cargo-build-and-copy -o index.node"
},
...
"devDependencies": {
    "cargo-build-and-copy": "0.1"
},
...
```

**Comment by dherman** [comment]
@amilajack Do you mind creating the `neon-bindings/cargo-build-and-copy` repo and reaching out to the community member who had contributed a CLI tool for us a few months ago? I'd love to see if they're interested in contributing this one.

**Comment by dherman** [comment]
Bikeshedding: what if we called this package `cargo-build-addon`? I.e., it's not specific to Neon, but because it's in npm, it's a tool for building a Node addon. It feels a little more purposeful than "build-and-copy" and also acknowledges the fact that it's really only for building one particular type of Cargo project (e.g. it's not for building executables).

**Comment by kjvalencik** [comment]
@dherman What I like about `cargo-build-and-copy` is how transparent what it does is. It doesn't do anything more than execute `cargo build` and copy the artifact.

I think it loses some of that with `cargo-build-addon`.

It's not the intent, but for what's it's worth, it would work for executables as well.

**Comment by dherman** [comment]
This was done in https://github.com/neon-bindings/cargo-cp-artifact
