### ISSUE TITLE
Eliminate third-party promise wrappers

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#574]
Now that Node has standard promise-based libraries built-in, and we don't support older Nodes than v10, can we get rid of much or even all of our "promiseify" wrappers in favor of the built-in promise APIs?

**Comment by lp** [comment]
Hi @dherman , is this open task still relevant?

**Comment by kjvalencik** [comment]
As part of [this RFC](https://github.com/neon-bindings/rfcs/pull/36), `neon-cli` will be deprecated. Anything related to it that isn't necessary maintenance likely isn't needed.
