### ISSUE TITLE
Hello World! example uses outdated `extern crate num_cpus;`

### ISSUE THREAD

**Issue by zedseven** [neon-bindings/neon#586]
Hi! Today I'm starting out learning Neon and Rust together, and I was following the [Hello World! example](https://neon-bindings.com/docs/hello-world/), but I ended up burning a few hours trying to get it to build due to the following error:
```
> neon build --release
neon info forcing rebuild for new build settings
neon info running cargo
   Compiling memchr v2.3.3
   Compiling lazy_static v1.4.0
   Compiling regex-syntax v0.6.18
   Compiling cc v1.0.58
   Compiling cfg-if v0.1.10
   Compiling libc v0.2.74
   Compiling semver-parser v0.7.0
   Compiling cslice v0.2.0
   Compiling neon-build v0.4.0
   Compiling thread_local v1.0.1
   Compiling semver v0.9.0
   Compiling num_cpus v1.13.0
   Compiling aho-corasick v0.7.13
   Compiling regex v1.3.9
   Compiling neon-sys v0.4.0
   Compiling neon-runtime v0.4.0
   Compiling neon v0.4.0
   Compiling thread-count v0.1.0 (F:\Project Files\Neon Files\thread-count\native)
error[E0463]: can't find crate for `num_cpus`
 --> build.rs:2:1
  |
2 | extern crate num_cpus;
  | ^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `thread-count`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
neon ERR! cargo build failed
```

I finally found [a StackOverflow post](https://stackoverflow.com/a/50307802) that showed it was no longer necessary to use the `extern crate num_cpus;` anymore, and after removing it the build went smoothly.

Just thought I'd point it out to save other beginners hours of troubleshooting.

**Comment by zedseven** [comment]
Unrelated, but I also found that the Electron App link is broken in the top section. (it links to ./electron-apps/ instead of ../electron-apps/)
![image](https://user-images.githubusercontent.com/25164338/89722664-e4540c00-d9db-11ea-8c9c-ef0b4ac3219a.png)

**Comment by adumbidiot** [comment]
That `extern` decl should be in the main file, not the build file. I'm guessing that you put `num_cpus` under `dependenies`,making it not available to build scripts. If that declaration was in the main file, the code would compile fine; the `extern crate` is optional. I'm pretty sure that is just some cruft left from the 2015 edition. Maybe it would make sense to remove that from the documentation though to reduce confusion.

**Comment by kjvalencik** [comment]
CC: @amilajack. Is this something that we have on the list to clean up?

**Comment by amilajack** [comment]
Yup! I'll take a look at this.

**Comment by amilajack** [comment]
Fixed 🎉 https://neon-bindings.com/docs/hello-world
