### ISSUE TITLE
"Module did not self-register" when working with Electron 9.2.0

### ISSUE THREAD

**Issue by hawkeye2013** [neon-bindings/neon#587]
Hi!

I have been working with Neon, trying to implement a boilerplate application using Angular, Electron, and Rust with examples of how to connect everything.  The repository is here: [https://github.com/hawkeye2013/angular-rust-electron](https://github.com/hawkeye2013/angular-rust-electron).  I wrote a script, `buildSystem/buildexecutables.js`, that builds all the modules into executables and places them into the `tools/` folder.  I build the native module with the Neon CLI through this script and copy the `lib/` folder and the `native/index.node` file, as well as the `package.json` in the same directory structure that they were in in the build folder.  I tested the copied files in the `tools/` folder with the same:
```
node
> var threadCount = require('.')
> threadCount()
```
that was is found on the [hello-world](https://neon-bindings.com/docs/hello-world) example of the neon docs.  That works like a champ so I know the module works correctly with node.  Once I put Electron into the equation, things are starting to fail.  The file that imports the native module is: `backend/ipc/IPCButton/IPCButton.ts`.  This file looks like this:
```
import { ipcMain, IpcMainEvent } from 'electron';
import App from '../../core/App';
const threadCount = require('../../../tools/thread-count');

export class IPCButton {
  constructor() {
    this.watchIPCChannels();
  }

  watchIPCChannels() {
    ipcMain.on('button::click', this.handleButtonClick);
  }

  handleButtonClick(event: IpcMainEvent, args: any) {
    console.log('Handle Button Click');
    console.log(event, args);
    console.log(threadCount());
  }
}
```
Basically it watches the IPC channel `button::click` that is being sent to it from the electron render process.  Once it gets that, it will fire off the threadCount function which I know works normally in Node.  I get the following error:
```
App threw an error during load
Error: Module did not self-register: '\\?\D:\code\angular-rust-electron\tools\thread-count\native\index.node'.
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\code\angular-rust-electron\tools\thread-count\lib\index.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
```
I have been searching to find out what it means.  I found a couple of posts: #389 and #265.  #265 explains that I should recompile the module for electron and a link to [https://guides.neon-bindings.com/electron-apps/](https://guides.neon-bindings.com/electron-apps/).  This explains how to rebuild a module on npm but I am struggling to get a solution for a local module that I do not want to be tossed up on NPM yet.  I tried using `electron-build-env` like was shown in the solution but could not get it to work.  I then started searching the electron docs to see if I could find anything useful there.  I found this section about [Troubleshooting](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md#troubleshooting) with `win_delay_load_hook`.  It says this: 

>If the module is built with node-gyp, ensure that the `win_delay_load_hook` variable is set to `true` in the `binding.gyp` file, and isn't getting overridden anywhere. If the module is built with another system, you'll need to ensure that you build with a delay-load hook installed in the main .node file.

I am still new to Neon, but I would guess it does this correctly.  At this point, I have exhausted the options I came up with so I am hoping someone might be able to point me in the right direction to fix this error.

Here are some handy version numbers if a version mismatch could be an issue:
```
node: v12.18.3
Windows 10: OS build 19041.388
electron: ^9.2.0
```
There are a lot of packages in the repo so the rest of the version numbers can be found at: [https://github.com/hawkeye2013/angular-rust-electron/blob/master/package.json](https://github.com/hawkeye2013/angular-rust-electron/blob/master/package.json)

**Comment by kjvalencik** [comment]
@hawkeye2013 There's a unit test that uses `electron@^6`. Can pull that and see if it works for you? It uses the `electron-build-env` wrapper in the build step. This wrapper provides the necessary environment variables for the node version electron is using and also bundles in the `win_delay_load_hook`.

https://github.com/neon-bindings/neon/tree/master/test/electron

If that works for you, but your project does not, there are a couple potential issues:

* `electron-build-env` isn't finding the `electron` module. I haven't tested electron beyond having the module at the root of the project. You can try using the wrapper with a simple program that logs the environment variables to see if they look correct. `electron-build-env node -e 'console.log(process.env)'`
* The electron version is incompatible. Newer versions of electron require that native modules support multiple contexts. Neon *does not* currently and does not register itself as such. You could try setting `app.allowRendererProcessReuse = false` or downgrading electron.

**Comment by hawkeye2013** [comment]
Hi @kjvalencik, thanks for getting back to me!  pulled the Neon repo and ran the test which passed.  I ran the `electron-build-env node -e 'console.log(process.env)'` to inspect the environment variables.  Everything seems to be pointing to the right place, although I don't see anything that specifically talks about the electron version or location.  I tried picking apart the code in `electron-build-env` to see how it pulls the electron version to run against but haven't gotten anywhere yet.  

I also tried looking into the test in the Neon repo to see if I could mirror that.  I think I might be missing something.  I see the command to build it is: `electron-build-env node ../../cli/bin/cli.js build --release`.  I can see how it calls out `node` and the local version of the `neon-cli`.  I'm confused about how it knows that the module to build is in the `native/` directory since it doesn't call that out at all with a command line argument.  How does it know to build in that folder, and can I specifically tell it to build a module in a different folder?

**Comment by kjvalencik** [comment]
@hawkeye2013 It's the `npm_config_*` environment variables that `electron-build-env` sets. The unit test is referencing the local copy of the cli, but it should be exactly the same as running `neon build`.

I took a look at your project and `"rebuild": "electron-build-env neon build thread-count --release"` looks correct.

**Comment by hawkeye2013** [comment]
@kjvalencik I got it working - I ended up removing the `rebuild` npm script I had in the `package.json` and using:

```
execSync(
    `cd ${/path/to/project} && npx electron-build-env neon build --release`,
    {
      encoding: 'utf-8',
    }
  );
```
in the script to programmatically build the executable.  The `electron-build-env` was the key to fixing the `Module did not self-register` error I was getting.  I have it running against `"electron": "^9.2.0"` right now and it doesn't seem to be having any issues.  Thank you for all the help!

**Comment by kjvalencik** [comment]
@hawkeye2013 That's great! We're currently pretty far along with the N-API port and it won't have the same limitations. N-API can be compiled once per platform and will work across node versions.

Hopefully it solves some of the more complex workflow issues like this! If you are interested in giving it a try and don't rely on the `Task` trait, almost everything else is there with the `napi-runtime` feature flag.

**Comment by hawkeye2013** [comment]
@kjvalencik Perfect!  I will look into that!  Seems like a good feature for the workflow.  Thank you!
