### ISSUE TITLE
`JsFunction::call` should take a `AsRef<[T]` instead of `IntoIterator<Item = T>`

### ISSUE THREAD

**Issue by kjvalencik** [neon-bindings/neon#608]
As demonstrated in https://github.com/neon-bindings/neon/pull/607, iterating and constructing a heap allocated `Vec` takes a non-trivial amount of time when calling a `JsFunction`. One possible optimization is using `smallvec` instead of `Vec`.

However, given that the N-API endpoint requires an array pointer, the data will *always* be collected into a `Vec`. Since this is an implementation detail that is unlikely to change, directly accepting a slice will result in better performance.

Additionally, since function arguments are typically constructed statically, the loss of `IntoIterator` is unlikely to cause a loss of ergonomics for most users. The `AsRef<[T]>` implementation will allow us to abstract over `Vec<T>`, `&Vec<T>`, `[T; _]`, `&[T]` and others.

**Comment by sbillig** [comment]
:+1:
The same change should be made to `JsFunction::construct`, and `Class::new`.

**Comment by kjvalencik** [comment]
This was changed.
