### ISSUE TITLE
Convert `JsArray` to `&[&str]`

### ISSUE THREAD

**Issue by Richienb** [neon-bindings/neon#613]
I'm trying to convert a `JsArray` to a `&[&str]` so that I can provide it in a function. Using the [documentation](https://neon-bindings.com/docs/arrays), I was able to convert it into a Vec but when I tried to convert that into a slice, the items were `Handle<JsValue>`s. How do I convert these to strings?

**Comment by kjvalencik** [comment]
This will take a few steps:

1. Downcast each element to a `JsString`
2. Get the value of each as a `String`
3. Get a `&str` for each element

**Comment by Richienb** [comment]
@kjvalencik I'm running this within a function but it's expecting `&self` as an argument:

![image](https://user-images.githubusercontent.com/29491356/95705147-7f54b500-0caf-11eb-85da-d43b817352ef.png)

Is this supposed to happen?

**Comment by kjvalencik** [comment]
@Richienb Sorry about that, I quickly put that together on my phone without testing. `downcast_or_throw` expects two type arguments. It would require a placeholder: `downcast_or_throw::<JsString, _>`.

Here is a complete working example with comments of what each line is doing. I omitted describing `?` which always either return `Err(Throw)` or unwrap the `Ok` value.

```rust
use neon::prelude::*;

fn print_str_array(strs: Vec<&str>) {
    for s in strs {
        println!("{}", s);
    }
}

fn example(mut cx: FunctionContext) -> JsResult<JsUndefined> {
    // Get the 0th argument and downcast to `JsArray`
    let strs = cx.argument::<JsArray>(0)?
        // Convert `JsArray` to `Vec<JsValue>`
        .to_vec(&mut cx)?
        // Iterate, yielding `Handle<JsValue>` elements
        .into_iter()
        .map(|v| {
            // Downcast to `JsString>`
            v.downcast::<JsString>()
                // Throw an exception if it's not a `string`
                .or_throw(&mut cx)
                // Convert `Ok(JsString)` to `Ok(String)`
                .map(|v| v.value())
        })
        // Collect into a `Result<Vec<String>, Throw>`
        .collect::<Result<Vec<_>, _>>()?;

    // Convert the `Vec<String>` to `Vec<&str>`
    let strs = strs.iter().map(|v| v.as_str()).collect();

    print_str_array(strs);

    Ok(cx.undefined())
}

register_module!(mut cx, {
    cx.export_function("example", example)
});
```

**Comment by thekingofcity** [comment]
For those who want to run this example in 0.9, several lines need to be changed.

```rust
            // Downcast to `JsString`
            v.downcast::<JsString, _>(&mut cx) // `&mut cx` and `_` are required
                // Throw an exception if it's not a `string`
                .or_throw(&mut cx)
                // Convert `Ok(JsString)` to `Ok(String)`
                .map(|v| v.value(&mut cx)) // `&mut cx` is required
```
