### ISSUE TITLE
Allow Rust objects to be (safely) traced by the v8 GC

### ISSUE THREAD

**Issue by DemiMarie** [neon-bindings/neon#63]
It would be nice for Rust objects to be safely traceable by the v8 GC.  This will require syntax extensions to handle the various tracing methods safely.

**Comment by dherman** [comment]
@drbo I'm still a bit wobbly on my GC/memory management skills so let me see if I follow:

* The handles API makes it possible for the stack to safely hold references to JS objects.
* The class API (implemented in #58) makes it possible for JS objects to safely own Rust objects.
* But we can't currently have JS objects own Rust objects that hold references back to more JS objects.

So is that specifically what this would enable? If we could provide a safe way to implement the trace hooks for a Rust type, then it would be safe for a neon class to own Rust objects of that type.

Do I have that right?

**Comment by drbo** [comment]
Yes, that is what I am thinking of.  It would probably require a compiler
plugin though.

**Comment by vinipsmaker** [comment]
Are there plans to let the heap to safely hold references to JS objects (i.e. a a Rust object that "owns" a JS object, prevents a JS object from being GCed, `v8::Persistent`...)? If this is allowed, then the #26 would be a no-brainer and even more patterns could be implemented.

**Comment by dherman** [comment]
I'd love to see an RFC sketching out the API! I'll open an issue in the RFCs repo.
