### ISSUE TITLE
Is it possible to speed up reading/modifying object properties using threads?

### ISSUE THREAD

**Issue by adamsoutar** [neon-bindings/neon#638]
Hi,

I'm using Neon to get an array of objects from JS, and on each of those objects I'm getting a string property from them and changing it (run a profanity filter on it).

So the signature on the JS side is like this:
(Except I'm calling it with a very large array of objects)

```js
filter([{ name: 'Hello' }, { name: 'Some bad word' }])
```

and it comes back as:

```js
[{ name: 'Hello' }, { name: 'Some *** word'}]
```

I was wondering if I could use something like Rayon to speed up this process, but I can't pass JS values between threads (understandably).

Neon's [rayon demo](https://github.com/dherman/wc-demo/blob/master/native/src/lib.rs) seems to use it by basically turning everything into Rust values and sending those through rayon, then turning them back to JS values afterward. But I'm not sure I'd be able to do that because I have a JsArray of JsObject, on which there is a JsString property which is what I'm trying to read. I could theoretically do some serial work to get this into a Vec<String> but the overhead of doing that & changing it back afterward might not be worth it?

Is it possible to parallelise reading & modifying properties of many objects in an array?

**Comment by kjvalencik** [comment]
It is not possible. Javascript objects are only accessible on the main thread and accessesing them would need to be single threaded.

There might be some other options for improving performance. What is the source of the data? Is it an http request or file? If the data starts as a `Buffer`, it can be better to keep it that way and pass it to Neon directly. The underlying bytes of the `Buffer` can accessed cheaply and parsed with `serde`.

**Comment by adamsoutar** [comment]
Thank you. I suspected so, but it was worth asking :)

Those are very interesting suggestions. I'll experiment with different ways of passing in my data and see what I can do, but I think that fits outside the scope of an issue with this repo. Thanks for your reply & help
