### ISSUE TITLE
neon and type=module

### ISSUE THREAD

**Issue by all789-pixel** [neon-bindings/neon#656]
Hello

I have neon@0.6.0.

I'm trying node `14.15.1` and `15.4.0` with `type=module` inside package.json.
If I rename `lib/index.js` to `lib/index.cjs`, it's ok (great)

If I create `lib/index.mjs` with first line `import * as addon from '../native';` i have this error `Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/home/dev/test_neon/native' is not supported resolving ES modules imported from /home/dev/test_neon/lib/test_index.mjs`

How import native module with esm syntax ? Is it possible ?

Thank

**Comment by demurgos** [comment]
My solution is to pass through a commonjs module.

Use two files: `index.cjs` and `index.mjs`.
```
// index.cjs
module.exports = require("./native/index.node");

// index.mjs
export addon from "./index.cjs"
```

You may also use the `index.mjs` to provide named exports:
```
// index.cjs
module.exports = require("./native/index.node");

// index.mjs
import addon from "./index.cjs"

export const foo = native.foo;
export const bar = native.bar;
```

**Comment by all789-pixel** [comment]
Great workaround ! Thank you.

**Comment by kjvalencik** [comment]
@demurgos Thanks for sharing a fix! I am closing this issue since it is not directly related to `neon` and would apply to all native libraries.

**Comment by neezer** [comment]
You can also use [module.createRequire](https://nodejs.org/api/module.html#modulecreaterequirefilename):

```js
import { createRequire } from "module";

const require = createRequire(import.meta.url);
const addon = require("./index.node");

export const foo = addon.foo;
export const bar = addon.bar;
```
