### ISSUE TITLE
N-API support for EventHandler

### ISSUE THREAD

**Issue by demurgos** [neon-bindings/neon#657]
Hi,
I am trying to port one of my packages from the `legacy-runtime` to the `napi-runtime` but I am currently blocked because the `EventHandler` constructor is not implemented.

What is the current status of `EventHandler` with the `napi-runtime`?

I've seen the [PR#622: Threadsafe Handles](https://github.com/neon-bindings/neon/pull/622/files) and it seems like it would offer an alternative solution for use-cases involving `EventHandler`. Is it planned to supersede it?

In my use case I use `EventHandler` to notify JS when a tokio task completes.

**Comment by kjvalencik** [comment]
@demurgos You are correct that Threadsafe Handles are meant to supersede `EventHandler`. We _may_ implement `EventHandler` on top of it to help with migration, but if we do, it will be marked as deprecated and cause a compiler warning.

**Comment by kjvalencik** [comment]
Part of the JsPromise/TaskBuilder RFC.

https://github.com/neon-bindings/rfcs/pull/35
