### ISSUE TITLE
Hot Reload Electron

### ISSUE THREAD

**Issue by jruiseco** [neon-bindings/neon#670]
Is there a standardized way for hot reloading a neon binding in electron?

**Comment by kjvalencik** [comment]
As far as I'm aware, there isn't a way to hot reload _native_ modules in Node/Electron.

Since the same techniques and limitations of this would also apply to `C` and `C++` modules, it is not Rust/Neon specific. Given that, I am closing this issue.

Sorry that I couldn't be more helpful!
