### ISSUE TITLE
[neon-build]: How to use build options

### ISSUE THREAD

**Issue by ssssota** [neon-bindings/neon#675]
Can I use build options?

I checked [this example](https://docs.rs/neon-build/0.7.0/neon_build/struct.Setup.html#example).
And I tried this in `windows 10`, `rustc 1.49.0` and `neon 0.7.0`.

build.rs
```rust
extern crate neon_build;

fn main() {
    neon_build::Setup::options()
        .output_dir("../dist")
        .setup();
}
```

then

```
> neon build --release

neon info forcing rebuild for new build settings
neon info running cargo
   Compiling semver-parser v0.7.0
   Compiling cfg-if v1.0.0
   Compiling smallvec v1.6.1
   Compiling cslice v0.2.0
   Compiling neon-sys v0.7.0
   Compiling hello-project v0.1.0 (D:\Dev\hello-project\native)
   Compiling neon v0.7.0
error[E0433]: failed to resolve: could not find `Setup` in `neon_build`
 --> build.rs:4:17
  |
4 |     neon_build::Setup::options()
  |                 ^^^^^ could not find `Setup` in `neon_build`

error: aborting due to previous error
```

Sorry, I can't use English well.
And I don't know Rust well.

Thank you.

**Comment by kjvalencik** [comment]
These build options are only available with the `napi` backend. Please ensure you are using the napi backend.

**Comment by ssssota** [comment]
@kjvalencik 
How to use napi backend?

**Comment by kjvalencik** [comment]
@ssssota It's feature flag based. There are some additional details in the "manual steps" section. https://github.com/neon-bindings/neon/issues/444

**Comment by ssssota** [comment]
@kjvalencik 
Thank you so much!
