### ISSUE TITLE
Treat Future/async function as a Promise

### ISSUE THREAD

**Issue by oeed** [neon-bindings/neon#684]
I have an async Rust function already built and I'm wanting to expose it to JavaScript.

I've read the [Async Tasks](https://neon-bindings.com/docs/async/) page, but the `perform` function in `Task` only deals in synchronous code. I'm unclear how to best have some executor run the `Future`.

Admittedly, I'm not too well versed in how executors work and what's required. ` futures::executor::block_on` seems like it might work, but I don't want the Rust thread to block as there may be multiple calls executing at once. There's obviously no place to put `#[tokio::main]` or similar.

Converting the callback function to a Promise is trivial, I'm not confused about that, purely the Rust side of this issue.

Any tips or advice for what the best approach is?

**Comment by kjvalencik** [comment]
The `legacy-backend` has the [`EventHandler`](https://docs.rs/neon/0.7.1/neon/event/struct.EventHandler.html) API enabled with the `event-handler-api` feature flag.

The `N-API` backend has [`EventQueue`](https://docs.rs/neon/0.7.0-napi.3/neon/event/struct.EventQueue.html) API enabled with `event-queue-api`.

Both give access to a `Context` from other threads. An example can be found of what this might look like here: https://github.com/neon-bindings/neon/issues/560#issuecomment-767620278

**Comment by oeed** [comment]
Thanks, with a lot of trial and error trying to get N-API working I managed to get your example work; does the job perfectly, thanks!
