### ISSUE TITLE
Class Methods using FunctionContext are ignored

### ISSUE THREAD

**Issue by sarocu** [neon-bindings/neon#688]
Quirky issue, if I am exporting a class and using `FunctionContext`, `neon build` will essentially ignore the method. If I leave off the `FunctionContext` type it seems to be fine however. 

So this builds and works:
```rust
use neon::prelude::*;

pub struct CoolTest {
    name: String
}

declare_types! {
    pub class CoolJs for CoolTest {
        init(mut cx) {
            Ok(CoolTest {
                name: cx.string("Cool").value(),
            })
        }

        method call_func(mut cx) {
            let func = cx.argument::<JsFunction>(0)?;
            let null = cx.null();
            let args: Vec<Handle<JsNumber>> = vec![cx.number(1.0)];
            func.call(&mut cx, null, args);
            Ok(cx.string("hi").upcast())
        }
    }
}

register_module!(mut m, { m.export_class::<CoolJs>("CoolTest") });
```

While this will build but not with the method:
```rust
use neon::prelude::*;

pub struct CoolTest {
    name: String
}

declare_types! {
    pub class CoolJs for CoolTest {
        init(mut cx) {
            Ok(CoolTest {
                name: cx.string("Cool").value(),
            })
        }

        method call_func(mut cx: FunctionContext) {
            let func = cx.argument::<JsFunction>(0)?;
            let null = cx.null();
            let args: Vec<Handle<JsNumber>> = vec![cx.number(1.0)];
            func.call(&mut cx, null, args);
            Ok(cx.string("hi").upcast())
        }
    }
}

register_module!(mut m, { m.export_class::<CoolJs>("CoolTest") });
```

Also interesting, you can also specify the return type and `neon build` will ignore it: `method call_func(mut cx) -> JsResult<JsNumber> {...}`

**Comment by kjvalencik** [comment]
There are lots of issues with the `declare_types` macro. It is deprecated and will *not* be ported to the N-API backend.

https://github.com/neon-bindings/neon/issues/682

**Comment by ashutoshvarma** [comment]
@kjvalencik If you don't mind, can you point me some examples or documentation for creating classes with `JsBox`.

**Comment by kjvalencik** [comment]
@ashutoshvarma The idea is to implement the class in pure JavaScript, delegating the functionality to Neon functions that take a `JsBox` as an argument.

```js
const { personNew, personGreet } = require("./index.node");

class Person {
    constructor(name) {
        this.native = personNew(name);
    }
    
    greet(greeting) {
        personGreet(this.native, greeting);
    }
}
```

```rust
struct Person {
    name: String,
}

impl Person {
    fn new(name: String) -> Self {
        Self { name }
    }
    
    fn greet(&self, greeting: &str) -> String {
        format!("{}, {}!", greeting, &self.name)
    }
}

impl Finalize for Person {}

fn person_new(mut cx: FunctionContext) -> JsResult<JsBox<Person>> {
    let name = cx.argument::<JsString>(0)?.value(&mut cx);
    let person = Person::new(name);
    
    Ok(cx.boxed(person))
}

fn person_greet(mut cx: FunctionContext) -> JsResult<JsString> {
    let person = cx.argument::<JsBox<Person>>(0)?;
    let greeting = cx.argument::<JsString>(0)?.value(&mut cx);
    let message = person.greet(&greeting);
    
    Ok(cx.string(message))    
}
```

**Comment by NadirSahllal** [comment]
@kjvalencik I would be curious to know how to change the methods of the class from example the greet into async methods. If there is any examples that would be great help. Thank you!!

**Comment by NadirSahllal** [comment]
@kjvalencik another comment on the JsBox in neon::types. it seems that id doesn't exist anymore??

**Comment by kjvalencik** [comment]
Neon does not provide an API for seamlessly integrating with promises. However, you can pass a callback into the Neon function and promisfy the function on the Js side to make it async.

This example demonstrates the pattern: https://github.com/neon-bindings/examples/tree/main/examples/async-sqlite
