### ISSUE TITLE
Static linking VC++ runtime library

### ISSUE THREAD

**Issue by wspl** [neon-bindings/neon#689]
Related:
https://github.com/neon-bindings/neon/issues/510
https://github.com/neon-bindings/neon/issues/519

Currently, neon does not support (or I don't know if it already does) static linking of the VC++ runtime to the production, which can cause some operating systems that do not have the VC++ runtime pre-installed, such as Win7/8, to not run properly.

Is it possible to support this feature in a future release?

**Comment by kjvalencik** [comment]
@wspl There may some `node-gyp` flags that can be set to static link the VC++ runtime; however, making these available is not currently on the roadmap.

The main Neon contributors likely do not have bandwidth to tackle this at this time, but a patch would be welcome if it's something of interest.

I also encourage you to try out the `napi` backend for Neon which does not depend on `node-gyp` or any C++ code. It _should_ work without any static linking. We are still working on a streamlined `npm init neon` for creating a Neon project with N-API, but in the meantime, the test package can be used as an example:

https://github.com/neon-bindings/neon/tree/main/test/napi

**Comment by rajivshah3** [comment]
In the meantime, you can add this to `.cargo/config.toml`:

```toml
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
```

This uses Rust's [`crt-static` feature](https://doc.rust-lang.org/reference/linkage.html#static-and-dynamic-c-runtimes)

**Comment by kjvalencik** [comment]
Closing since the Node-API backend acts as a normal Rust shared library built with cargo. Linking should work identically to non-neon shared libraries.
