### ISSUE TITLE
Uncaught TypeError: domain.enter is not a function

### ISSUE THREAD

**Issue by fuyoo** [neon-bindings/neon#693]
when i try fibonacci-async-task example 
the console throw an error 

```javascript
Uncaught TypeError: domain.enter is not a function
    at topLevelDomainCallback (domain.js:137:12)
    at callbackTrampoline (internal/async_hooks.js:121:14)
> (node:11584) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```
my node version is v14.5.0

**Comment by fuyoo** [comment]
neon version : 0.7.1
os version: osx 10.14.6

**Comment by kjvalencik** [comment]
@fuyoo I was not able to reproduce this issue on macOS with Node 14.5.4. Can you try updating to the latest `14.5.x` to rule out a Node issue?

**Comment by fuyoo** [comment]
thank a lot, `14.5.x` is  works

**Comment by fuyoo** [comment]
i change node version to v10.15.x, the demo can running, at the node version `14.16.0`  *domain api* has been deprecated (detail)[https://nodejs.org/dist/latest-v14.x/docs/api/domain.html]
