### ISSUE TITLE
Date API

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#70]
Expose an object type as `neon::js::date::JsDate`, using `v8::Date`.

🔒 @jaredwy is implementing!

**Comment by dherman** [comment]
Here's an RFC for the API: neon-bindings/rfcs#18

**Comment by jaredwy** [comment]
I’ll nab this one now there’s an rfc.

**Comment by jaredwy** [comment]
I won’t be able to start until next week though. (I can’t seem to assign this to my self on the GitHub mobile website)
