### ISSUE TITLE
Can the Event Queue API invoke a JS function multiple times?

### ISSUE THREAD

**Issue by lynaghk** [neon-bindings/neon#702]
First, let me say thanks for Neon --- I've been happily using it for years to hook into native APIs from my Electron apps and it has worked swimmingly!

Yesterday I discovered the Event Queue API and was excited about the ability to invoke JS functions async from Rust.
However, from what I can tell of the API design, the JS callbacks can be invoked at most once.

Is it possible to invoke the JS callback multiple times from Rust?
I.e., would it be possible to re-implement JavaScript's `setInterval` using Neon?

Here's the example from the [migration guide](https://github.com/neon-bindings/neon/blob/main/MIGRATION_GUIDE.md#deprecated-event-handler-api):

```rust
pub fn start_task(mut cx: FunctionContext) -> JsResult<JsUndefined> {
    let callback = cx.argument::<JsFunction>(0)?.root(&mut cx);
    let queue = cx.queue();

    std::thread::spawn(move || {
        let result = // compute the result...
        queue.send(move |mut cx| {
            let callback = callback.into_inner(&mut cx);
            let this = cx.undefined();
            let args = vec![
                cx.null().upcast::<JsValue>(),
                cx.number(result).upcast()
            ];
            callback.call(&mut cx, this, args)?;
            Ok(())
        });
    });

    Ok(cx.undefined())
}
```

the `callback` function is moved into the `queue.send` closure and consumed there, so there's no way to use it again in a later call to `queue.send`

I tried moving a clone of `callback` into the `queue.send` closure:

```rust
std::thread::spawn(move || {
    let cb2 = callback.clone(...); //doesn't work, I don't have a `cx` here.
    queue.send(move |mut cx| {
        let callback = cb2.into_inner(&mut cx);
        let this = cx.undefined();
        ...
```

but that doesn't work because `clone` requires a `cx`, which the Rust async scope doesn't have.

Is it possible to use this API to asynchronously invoke a JS function multiple times?

My use case is passing events from a Quartz EventTap into my Electron render process so it can handle global input events.

**Comment by kjvalencik** [comment]
Yes! There are two different methods to get the function back from a `Root`, `into_inner` and `to_inner`. The first takes ownership, but the second only takes `&self`.

The callback can be used many times from multiple threads by wrapping it in an `Arc` and cloning the `Arc`. However, take care to dispose of the `Root` on the final call when it's cleared. `Arc::try_unwrap` can be used to get the last insurance or you can manually dispose with `drop`.

I have an open PR that will make ensuring the `Root` doesn't leak unnecessary.

**Comment by lynaghk** [comment]
Thanks for the quick reply!

Here's my first pass which works as intended.
Seems pretty complicated, though --- do you have any suggestions for how this might be cleaned up?

```rust
use lazy_static::lazy_static;
use neon::prelude::*;
use std::sync::{Arc, Mutex};
lazy_static! {
    static ref CALLBACK: Arc<Mutex<Option<neon::handle::Root<neon::types::JsFunction>>>> =
        Arc::new(Mutex::new(None));
    static ref Q: Arc<Mutex<Option<EventQueue>>> = Arc::new(Mutex::new(None));
}

fn init(mut cx: FunctionContext) -> JsResult<JsUndefined> {
    //Set global ref to callback
    CALLBACK
        .lock()
        .unwrap()
        .replace(cx.argument::<JsFunction>(0)?.root(&mut cx));

    //Set global ref to queue
    Q.lock().unwrap().replace(cx.queue());

    //Just spawn a thread to simulate calling from an outside C program.
    std::thread::spawn(|| loop {
        std::thread::sleep_ms(1000);
        invoke_callback_from_c();
    });

    Ok(cx.undefined())
}

#[no_mangle]
extern "C" fn invoke_callback_from_c() {
    if let Some(ref queue) = *Q.lock().unwrap() {
        queue.send(|mut cx| {
            if let Some(ref root_callback) = *CALLBACK.lock().unwrap() {
                let callback = root_callback.to_inner(&mut cx);
                let this = cx.undefined();
                let args = vec![cx.string("hello")];
                callback.call(&mut cx, this, args)?;
            }
            Ok(())
        })
    }
}

register_module!(mut cx, {
    cx.export_function("init", init)?;
    Ok(())
});
```

**Comment by kjvalencik** [comment]
@lynaghk It depends if the `invoke_callback_from_c` can take a data pointer or not. If it can, it's likely cleaner to pass in a reference to the callback there. If it needs to be global, [`once_cell`](https://docs.rs/once_cell/1/once_cell/) provides a bit cleaner of an API than `lazy_static` for this use case.

However, your code is essentially correct.

```rust
use once_cell::sync::OnceCell;

static CALLBACK: OnceCell<Root<JsFunction>> = OnceCell::new();

/* ... */

CALLBACK.set(callback).or_else(|callback| {
    callback.drop(&mut cx);
    cx.throw_error("Attempted to re-initialize callback")
})?;

/* ... */

let cb = CALLBACK.get().ok_or(())
    .or_else(|| cx.throw_error("Expected callback to be initialized"))?;
    .to_inner(&mut cx);
```

**Comment by lynaghk** [comment]
Gotcha. I wanted to double check because it felt weird having to hold onto both the queue and the JS function itself.
I didn't know about `once_cell`, I'll take a look at using that instead of the lazy_static macro.
Thanks for the help and your work Neon!

**Comment by kjvalencik** [comment]
@lynaghk They are separate because there are use cases that may not involve a callback at all. We started by adding basic primitives that are flexible. However, I agree that now we are gaining some user experience, Neon would benefit with some higher level structures to make common patterns simpler.
