### ISSUE TITLE
bug(create-neon): Answering "no" leaves partial project on disk

### ISSUE THREAD

**Issue by kjvalencik** [neon-bindings/neon#706]
The end of the `npm init` prompts ask if the `package.json` looks correct. Users may answer "no" and it terminates the child process with an exit code of `1`. `create-neon` properly aborts the remainder of the init; however, it has already created the directory and a partial `package.json`.

`create-neon` should delete the partial project directory on a non-zero exit code.

**Comment by Caryyon** [comment]
Is this issue still valid? I just used `neon new foo` to test this, and it no longer gives me an option to give a 'yes' or 'no.' 
Happy to jump on this, but I believe it's been fixed.

**Comment by kjvalencik** [comment]
@Caryyon Yes, this is still an issue. `neon new foo` and `npm init neon foo` are two different packages.

The `neon` CLI corresponds with `cli/` in the source repo and is _deprecated_. This issue is for `create-neon/` and is the recommended way to create a new Neon project.

To reproduce, run `npm init neon my-project` and then terminate in any way:
* Answering, "no"
* `Ctrl+C`
* kill the process

All of them will leave files on disk.

This should likely be implemented by initializing the project in a temp directory and once successfully bootstrapped, move the directory to the target location. We can try to delete the temp directory if the internal `npm init` exits with a non-zero code, but even if that fails or the process is killed, at worst we've left files in `/tmp`.

**Comment by Caryyon** [comment]
I'll work on this!

**Comment by kjvalencik** [comment]
Awesome! Thanks so much!

**Comment by dherman** [comment]
@Caryyon Are you still interested in working on this? Let us know if you got stuck somewhere and we'd be happy to help.

**Comment by kjvalencik** [comment]
This was fixed!
