### ISSUE TITLE
Mention Node 16 support in the README

### ISSUE THREAD

**Issue by antonok-edm** [neon-bindings/neon#716]
I recently updated my system to use the new Node 16.0.0 which was released a few days ago, and I'm no longer able to `npm install` a library I'm using with Neon. I filed an issue with a traceback [here](https://github.com/brave/adblock-rust/issues/167) as I assumed I just needed to update Neon to the latest version, but it appears to still have issues with Neon 8.0 and even with the newer N-API feature. I verified that it still builds correctly when switching back to Node 15 using `nvm`.

It would be great to see support for Node 16 if possible, considering that it is now officially the "Current" release.

Also, the README [only lists](https://github.com/neon-bindings/neon#nodejs) Node 10, Node 12, and Node 14 compatibility - perhaps it would be worth updating with an extra column for Node 16.

**Comment by antonok-edm** [comment]
Actually, I just saw #715, which I'm having trouble testing locally but I trust the CI if that's passing :sweat_smile:. I can open a PR for updating the README at least!

**Comment by amilajack** [comment]
Sure, PR's welcome!

**Comment by kjvalencik** [comment]
The fix for the legacy backend in Node 16 was just merged today. It's awaiting a publish.
