### ISSUE TITLE
Status of `neon-build`

### ISSUE THREAD

**Issue by antonok-edm** [neon-bindings/neon#729]
I realized that the issue I had building on Node 16 (originally reported as https://github.com/neon-bindings/neon/issues/716) was not fixed by the 0.8.1 release, and I was only able to get it to build on Node 16 by removing the `neon_build::setup()` call from my crate's `build.rs`. Upon further investigation I don't see any mentions of `build.rs` or `neon-build` in the readme, docs, changelog, or migration guide, and the `create-neon` tool doesn't appear to create a `build.rs` either. I do still see it used in [this test](https://github.com/neon-bindings/neon/tree/main/test/dynamic), however (which I _can_ compile and run correctly!).

What's the status of the `neon-build` crate, and the requirement to use it in a `build.rs` file? Is there a use case for it; will I lose something by removing it from my crate? Also, if it is still useful, it seems like an issue that it doesn't work in my crate as of Node 16.

**Comment by kjvalencik** [comment]
`neon-build` and `build.rs` are only required for `legacy-backend`. `napi-backend`, which is what `create-neon` uses and is encouraged for new projects, does not use `neon-build`.
