### ISSUE TITLE
Promise API

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#73]
Expose the Promise object type under `neon::js::promise::JsPromise`, using `v8::Promise`. This one is going to require some good experimentation and thinking around the neon async story (see #26).

**Comment by winding-lines** [comment]
@dherman I finally have some time to play with neon, will check this out :)

**Comment by cdbattags** [comment]
Any update here with rust 1.39, future 0.3 and tokio 0.2 release?

Would love to do some experimentation wiring express.js controllers and actix-web services

**Comment by bochaco** [comment]
I was also wondering the same, I am looking for a way to bind `async` functions to JS `Promises`

**Comment by dherman** [comment]
This has a great v1 design for promises in RFC neon-bindings/rfcs#35. 🎉
