### ISSUE TITLE
could not find `declare_types` in `neon`

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [neon-bindings/neon#745]
i want to use Class feature and napi feature .

when compile this code:
```rust

neon::declare_types! {
    /// JS class wrapping LoginLicenseManager .
    pub class JsLoginLicenseManager for LoginLicenseManager {
```

use this config
```
[dependencies]
neon = { version = "0.8.2", default-features = false, features = ["default-panic-hook", "napi-6", "try-catch-api", "event-queue-api"] }
```

i get this error:
```
error[E0433]: failed to resolve: could not find `declare_types` in `neon`
   --> src\lib.rs:529:7
    |
529 | neon::declare_types! {
    |       ^^^^^^^^^^^^^ could not find `declare_types` in `neon`
```

which features i need to enable ?

**Comment by kjvalencik** [comment]
Classes are not implemented for N-API and there is no intent to migrate the `declare_types` macro. There will likely be a different approach when it is implemented.

However, `JsBox` can be used to wrap Rust data and pass it to Js. The instance of JsBox can be wrapped by a class in JavaScript. This example uses the pattern https://github.com/neon-bindings/examples/tree/main/examples/async-sqlite

**Comment by thekingofcity** [comment]
That's a bit shocking. Isn't the whole neon-bindings targets for N-API? If not, what's it targeting? Web? But the whole README and docs are talking about running rust under node...

*Someone who want to use rust library in js.*

**Comment by kjvalencik** [comment]
@thekingofcity There are currently two Neon backends, legacy and Node-API (formerly known as N-API). Both are targeting Node, but the legacy backend uses NAN and C++ as glue code.

The reason for this is that Neon predates the existence of Node-API by a couple of years. Both backends have been maintained to help users with the transition. However, the legacy backend is deprecated and not recommended for new projects.

**Comment by thekingofcity** [comment]
Ok, I get it. So everything in https://github.com/neon-bindings/neon/blob/25f0b72c018f7fab9aa405055c4c2612acf8df84/test/dynamic/native/src/js/classes.rs and https://neon-bindings.com/blog/2016/04/01/native-js-classes-in-neon/ are deprecated and are not supported in N-API. Those who want to have `class` in js should look for `JsBox` in the `async-sqlite` example, right?

**Comment by kjvalencik** [comment]
That's correct. There is an open RFC for adding classes to the Node-API backend.
