### ISSUE TITLE
Code coverage for initial test suite

### ISSUE THREAD

**Issue by mfpiccolo** [neon-bindings/neon#76]
# Code Coverage

This issue is intended to identify and track tests that will provide a solid level of code coverage for the inital test suite.  

---
### Code Coverage
- [x] The list below describes satisfactory coverage for the intial suite

---
### Types
- [ ] successful upcasts between various types in Rust
- [ ] successful downcasts between various types in Rust
- [ ] unsuccessful downcasts between various types in Rust
### Classes
- [ ] call methods on objects of the wrong type
### Control Flow
- [ ] propagate exceptions from JS through Rust back to JS
- [ ] trigger exceptions from Rust
### JsString
- [x] create a JsString in Rust
- [ ] exotic code points properly round-tripping between Rust and JS
### JsNumber
- [x] create a JsNumber in Rust
- [ ] large integers > int32.max properly round-tripping between Rust and JS
- [ ] negative integers properly round-tripping between Rust and JS
### JsArray
- [x] create a JsArray in Rust
- [x] populate JsArray in Rust 
### JsObject
- [x] create a JsObject in Rust
- [x] populate JsObject in Rust 
### Typed Arrays
- [ ] create a typed array in Rust
- [ ] get/set data from a typed array in Rust
### Compile Test Crate
- [x] Setup and configure the crate that will handle testing compile failures
- [ ] scope lifetime errors
### CI
- [x] Setup Travis or other CI system and integrate with Github

**Comment by mfpiccolo** [comment]
@dherman This is obviously not the whole test suite yet but the idea is that we can continue to add to this issue until you feel that we have covered enough for the initial test suite setup.  Then we can mark the first checkbox off to let us know what to aim for.  Then we can start knocking off the tests.

**Comment by dherman** [comment]
That's probably a good initial set. It's almost impossible to have any real notion of coverage being "complete" for a project like this, but it's at least a good breadth-first start. I'm so excited to grow the test suite over time!

**Comment by mfpiccolo** [comment]
Yeah agree that "complete" is a bit ambitious.  Thanks for adding to this!

**Comment by kjvalencik** [comment]
Neon has pretty good coverage in the test suite since the Node-API backend.
