### ISSUE TITLE
build neon-sys v0.8.3 error for electron13.x.y

### ISSUE THREAD

**Issue by simonfire007** [neon-bindings/neon#760]
I get errors such as

> ../src/neon.cc:223:20: error: ‘Contents’ is not a member of ‘v8::ArrayBuffer’
  223 |   v8::ArrayBuffer::Contents contents = buffer->GetContents();
      |                    ^~~~~~~~

> ../src/neon.cc:224:15: error: ‘contents’ was not declared in this scope
  224 |   *base_out = contents.Data();

Electron12.x.y is ok,it seems that electron's v8 has changed

**Comment by kjvalencik** [comment]
Interesting. Electron is based on Node v14 and those tests are passing. The class also exists in the latest version of Node. https://v8docs.nodesource.com/node-16.0/d7/d34/classv8_1_1_array_buffer_1_1_contents.html

I wonder if this is a regression in Electron?

**Comment by simonfire007** [comment]
https://chromium-review.googlesource.com/c/v8/v8/+/2720306

**Comment by simonfire007** [comment]
The change of v8 occurred in version 9.1.117, the latest version of nodejs uses 9.0.257.25, so nodejs has not been affected yet

**Comment by kjvalencik** [comment]
Oh, interesting. I didn't realize that Electron used a different version of V8 than the Node version it was based on.'

If this is something you would like to work on, the fix would be greatly appreciated. At this time, the core team is focusing on the N-API backend which is unaffected. Cheers!
