### ISSUE TITLE
Help: Need help in publishing the package to npmjs

### ISSUE THREAD

**Issue by VarunPotti** [neon-bindings/neon#764]
I almost completed writing this **https://github.com/jsx-one/jsx-one** and now I am working on the editor however I am not able to publish this package to npmjs and then use it in the editor.

The issues I encountered are the Framework I am using (SolidJS) is not loading the website after adding this module
``` sh
> node_modules/.pnpm/@jsx-one+jsx-one@0.0.1/node_modules/@jsx-one/jsx-one/src/index.ts:1:18: error: No loader is configured for ".node" files: node_modules/.pnpm/@jsx-one+jsx-one@0.0.1/node_modules/@jsx-one/jsx-one/src/index.node
    1 │ const a = require("./index.node");
      ╵                   ~~~~~~~~~~~~~~
```
Can someone please help me?

**Comment by kjvalencik** [comment]
@VarunPotti Can you tell me a little bit more about the environment? Is it Electron? Are you using Webpack?

`.node` is the extension for native modules in Node.js. This error is unrelated to Neon and would happen trying to load _any_ native module. My guess is something about the environment doesn't provide a native module loader by default.

**Comment by VarunPotti** [comment]
I am using webpack.

**Comment by kjvalencik** [comment]
@VarunPotti You will need to configure the `node-loader`. https://webpack.js.org/loaders/node-loader/

**Comment by VarunPotti** [comment]
Sure, will do thanks.
