### ISSUE TITLE
Neon Channel example

### ISSUE THREAD

**Issue by gerald9784** [neon-bindings/neon#766]
I have a program that carries out a heavy tasks with the use of threads, From some of the issues i have seen Task which could be used for background task can not be used in v0.8.3. How can i use channel to channel to communicate with javascript main thread

**Comment by kjvalencik** [comment]
Full example: https://github.com/neon-bindings/examples/tree/main/examples/async-sqlite
Unit tests: https://github.com/neon-bindings/neon/blob/main/test/napi/src/js/threads.rs
Docs: https://docs.rs/neon/0.8.3-napi/neon/event/struct.EventQueue.html
