### ISSUE TITLE
Can't get Electron example to build

### ISSUE THREAD

**Issue by cegredev** [neon-bindings/neon#773]
I'm currently trying to run the [Electron Apps](https://neon-bindings.com/docs/electron-apps) example on my machine (Win10, Node v14.17.4, rustc 1.53.0), but can't get it to work.

Trying to

> npm install @amilajack/neon-hello

<details>
<summary>I get these errors.</summary>

> npm ERR! code 1
> npm ERR! path C:\Users\Nutzer\Downloads\electron\node_modules\@amilajack\neon-hello
> npm ERR! command failed
> npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npm run build
> npm ERR! > @amilajack/neon-hello@1.0.2 build
> npm ERR! > neon build --release
> npm ERR!
> npm ERR! neon info forcing rebuild for new build settings
> npm ERR! neon info running cargo
> npm ERR! Compiling memchr v2.3.0
> npm ERR!    Compiling lazy_static v1.4.0
> npm ERR!    Compiling regex-syntax v0.6.14
> npm ERR!    Compiling cc v1.0.50
> npm ERR!    Compiling cfg-if v0.1.10
> npm ERR!    Compiling semver-parser v0.7.0
> npm ERR!    Compiling cslice v0.2.0
> npm ERR!    Compiling thread_local v1.0.1
> npm ERR!    Compiling semver v0.9.0
> npm ERR!    Compiling neon-build v0.3.3
> npm ERR!    Compiling aho-corasick v0.7.7
> npm ERR!    Compiling regex v1.3.4
> npm ERR!    Compiling neon-sys v0.3.3
> npm ERR! error: failed to run custom build command for `neon-sys v0.3.3`
> npm ERR!
> npm ERR! Caused by:
> npm ERR!   process didn't exit successfully: `C:\Users\Nutzer\Downloads\electron\node_modules\@amilajack\neon-hello\native\target\release\build\neon-sys-ba0b9d44bf6a3d65\build-script-build` (exit code: 101)
> npm ERR!   --- stdout
> npm ERR!   'Skipping node-gyp installation as part of npm install.'
> npm ERR!
> npm ERR!   --- stderr
> npm ERR!   thread 'main' panicked at 'Failed to run "node-gyp configure" for neon-sys!
> npm ERR!    Out:
> npm ERR!   > configure-release
> npm ERR!   > node-gyp configure --verbose
> npm ERR!
> npm ERR!
> npm ERR!    Err: gyp info it worked if it ends with ok
> npm ERR!   gyp verb cli [
> npm ERR!   gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
> npm ERR!   gyp verb cli   'C:\\Users\\Nutzer\\Downloads\\electron\\node_modules\\@amilajack\\neon-hello\\native\\target\\release\\build\\neon-sys-aa1b6d6b62839e48\\out\\native\\node_modules\\node-gyp\\bin\\node-gyp.js',
> npm ERR!   gyp verb cli   'configure',
> npm ERR!   gyp verb cli   '--verbose'
> npm ERR!   gyp verb cli ]
> npm ERR!   gyp info using node-gyp@3.6.2
> npm ERR!   gyp info using node@14.17.4 | win32 | x64
> npm ERR!   gyp verb command configure []
> npm ERR!   gyp verb check python checking for Python executable "python2" in the PATH
> npm ERR!   gyp verb `which` failed Error: not found: python2
> npm ERR!   gyp verb `which` failed     at getNotFoundError (C:\Users\Nutzer\Downloads\electron\node_modules\@amilajack\neon-hello\native\target\release\build\neon-sys-aa1b6d6b62839e48\out\native\node_modules\which\which.js:13:12)
> npm ERR!   gyp verb `which` failed     at F (C:\Users\Nutzer\Downloads\electron\node_modules\@amilajack\neon-hello\native\target\release\build\neon-sys-aa1b6d6b62839e48\out\native\node_modules\which\which.js:68:19)
> npm ERR!   gyp verb `which` failed     at E (C:\Users\Nutzer\Downloads\electron\node_modules\@amilajack\neon-hello\native\target\release\build\neon-sys-aa1b6d6b62839e48\out\native\node_modules\which\which.js:80:29)
> npm ERR!   gyp verb `which` failed     at C:\Users\Nutzer\Downloads\electron\node_modules\@amilajack\neon-hello\native\target\release\build\neon-sys-aa1b6d6b62839e48\out\native\node_modules\which\which.js:89:16
> npm ERR!   gyp verb `which` failed     at C:\Users\Nutzer\Downloads\electron\node_modules\@amilajack\neon-hello\native\target\release\build\neon-sys-aa1b6d6b62839e48\out\native\node_modules\isexe\index.js:42:5
> npm ERR!   gyp verb `which` failed     at C:\Users\Nutzer\Downloads\electron\node_modules\@amilajack\neon-hello\native\target\release\build\neon-sys-aa1b6d6b62839e48\out\native\node_modules\isexe\windows.js:36:5
> npm ERR!   gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:192:21)
> npm ERR!   gyp verb `which` failed  python2 Error: not found: python2
> npm ERR!   gyp verb `which` failed     at getNotFoundError (C:\Users\Nutzer\Downloads\electron\node_modules\@amilajack\neon-hello\native\target\release\build\neon-sys-aa1b6d6b62839e48\out\native\node_modules\which\which.js:13:12)
> npm ERR!   gyp verb `which` failed     at F (C:\Users\Nutzer\Downloads\electron\node_modules\@amilajack\neon-hello\native\target\release\build\neon-sys-aa1b6d6b62839e48\out\native\node_modules\which\which.js:68:19)
> npm ERR!   gyp verb `which` failed     at E (C:\Users\Nutzer\Downloads\electron\node_modules\@amilajack\neon-hello\native\target\release\build\neon-sys-aa1b6d6b62839e48\out\native\node_modules\which\which.js:80:29)
> npm ERR!   gyp verb `which` failed     at C:\Users\Nutzer\Downloads\electron\node_modules\@amilajack\neon-hello\native\target\release\build\neon-sys-aa1b6d6b62839e48\out\native\node_modules\which\which.js:89:16
> npm ERR!   gyp verb `which` failed     at C:\Users\Nutzer\Downloads\electron\node_modules\@amilajack\neon-hello\native\target\release\build\neon-sys-aa1b6d6b62839e48\out\native\node_modules\isexe\index.js:42:5
> npm ERR!   gyp verb `which` failed     at C:\Users\Nutzer\Downloads\electron\node_modules\@amilajack\neon-hello\native\target\release\build\neon-sys-aa1b6d6b62839e48\out\native\node_modules\isexe\windows.js:36:5
> npm ERR!   gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:192:21) {
> npm ERR!   gyp verb `which` failed   code: 'ENOENT'
> npm ERR!   gyp verb `which` failed }
> npm ERR!   gyp verb check python checking for Python executable "python" in the PATH
> npm ERR!   gyp verb `which` succeeded python C:\Python39\python.EXE
> npm ERR!   gyp verb check python version `C:\Python39\python.EXE -c "import platform; print(platform.python_version());"` returned: "3.9.6\r\n"
> npm ERR!   gyp verb could not find "C:\Python39\python.EXE". checking python launcher
> npm ERR!   gyp verb could not find "C:\Python39\python.EXE". guessing location
> npm ERR!   gyp verb ensuring that file exists: C:\Python27\python.exe
> npm ERR!   gyp ERR! configure error
> npm ERR!   gyp ERR! stack Error: Can't find Python executable "C:\Python39\python.EXE", you can set the PYTHON env variable.
> npm ERR!   gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Nutzer\Downloads\electron\node_modules\@amilajack\neon-hello\native\target\release\build\neon-sys-aa1b6d6b62839e48\out\native\node_modules\node-gyp\lib\configure.js:483:19)
> npm ERR!   gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Nutzer\Downloads\electron\node_modules\@amilajack\neon-hello\native\target\release\build\neon-sys-aa1b6d6b62839e48\out\native\node_modules\node-gyp\lib\configure.js:508:16)npm ERR!   gyp ERR! stack     at C:\Users\Nutzer\Downloads\electron\node_modules\@amilajack\neon-hello\native\target\release\build\neon-sys-aa1b6d6b62839e48\out\native\node_modules\graceful-fs\polyfills.js:284:29
> npm ERR!   gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:192:21)
> npm ERR!   gyp ERR! System Windows_NT 10.0.19042
> npm ERR!   gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Nutzer\\Downloads\\electron\\node_modules\\@amilajack\\neon-hello\\native\\target\\release\\build\\neon-sys-aa1b6d6b62839e48\\out\\native\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--verbose"
> npm ERR!   gyp ERR! cwd C:\Users\Nutzer\Downloads\electron\node_modules\@amilajack\neon-hello\native\target\release\build\neon-sys-aa1b6d6b62839e48\out\native
> npm ERR!   gyp ERR! node -v v14.17.4
> npm ERR!   gyp ERR! node-gyp -v v3.6.2
> npm ERR!   gyp ERR! not ok
> npm ERR!   ', C:\Users\Nutzer\.cargo\registry\src\github.com-1ecc6299db9ec823\neon-sys-0.3.3\build.rs:148:9
> npm ERR!   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> npm ERR! warning: build failed, waiting for other jobs to finish...
> npm ERR! error: build failed
> npm ERR! neon ERR! cargo build failed
> npm ERR!
> npm ERR! Error: cargo build failed
> npm ERR!     at Target.<anonymous> (C:\Users\Nutzer\Downloads\electron\node_modules\@amilajack\neon-hello\node_modules\neon-cli\lib\target.js:121:35)
> npm ERR!     at step (C:\Users\Nutzer\Downloads\electron\node_modules\@amilajack\neon-hello\node_modules\neon-cli\lib\target.js:32:23)
> npm ERR!     at Object.next (C:\Users\Nutzer\Downloads\electron\node_modules\@amilajack\neon-hello\node_modules\neon-cli\lib\target.js:13:53)
> npm ERR!     at fulfilled (C:\Users\Nutzer\Downloads\electron\node_modules\@amilajack\neon-hello\node_modules\neon-cli\lib\target.js:4:58)
> npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:95:5)

</details>

`PATH` contains the `...\.cargo\bin` as well as the Python directory.

I then tried using my own neon-dependency. This is a simplified version of my file tree:

```
- backend
    -- src
        --- lib.rs
    -- cargo.toml
    -- package.json
    -- index.node
- electron
    -- index.html
    -- package.json
    -- main.js
```

In short, `backend` is the [Hello World!](https://neon-bindings.com/docs/hello-world) example and `electron` was cloned from [electron/electron-quick-start](https://github.com/electron/electron-quick-start).

I installed backend in electron using `npm install ../backend` and ended up with an `electron/package.json` like this (only the most important parts):

```json
{
  "main": "main.js",
  "scripts": {
    "build": "electron-build-env neon build backend --release"
  },
  "devDependencies": {
    "electron": "^13.1.7",
    "electron-build-env": "^0.2.0",
    "neon-cli": "^0.9.0"
  },
  "dependencies": {
    "backend": "file:../backend"
  }
}
```

However, now running `npm run build` resulted in the following error:

> neon ERR! spawn cargo ENOENT
> 
> Error: spawn cargo ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
>     at onErrorNT (internal/child_process.js:467:16)
>     at processTicksAndRejections (internal/process/task_queues.js:82:21)
> electron-build-env error

Note that I modified the `build` script to include my custom module instead of `@amilajack/neon-hello` and the way I did this could be wrong, but I don't think this is the problem, as the error persists even if I change `backend` to complete nonsense.

Does anyone know how to fix this?

**Comment by kjvalencik** [comment]
@cegredev The electron example is no longer maintained. I'm sorry for the confusion for that has caused. We're still going through and updating docs--we're just about done Rust docs and the website will be next.

I'm not exactly sure what the original is, but it's likely something that has since been fixed since those examples are on old versions.

If you don't mind, I would like to address the 2nd question because it is more relevant. Firstly, `neon-cli` should not be used with the Node-API backend. Secondly, `electron-build` env is unnecessary with the Node-API backend. With that backend, compiled modules are portable across node versions (but, not operating systems / CPU architectures).

My recommendation is to delete the `backend` directory and re-create it with `create` script:

```
npm init neon backend
```

This will create the "Hello, World" example from scratch with the proper structure and scripts in `package.json`. From there, you should be able to `npm install` and use the module in the Electron app.

There are no additional steps that need to be taken to make a Neon module work with Electron when using the Node-API backend.

Let me know if you have any additional questions. Cheers!

**Comment by cegredev** [comment]
Ah okay, no problem. Maybe consider adding just a small info text at the top of the page to make people aware not all examples might still be valid, though. ;D

Anyways, glad to see it working now, thanks for your help. Next I'm going to try to integrate Neon using webpack; do you happen to know anything I should know too before doing so?

I'll start getting into it now and let you know if I get it to work or otherwise come back with more questions. ;)
