### ISSUE TITLE
extending macros

### ISSUE THREAD

**Issue by Dennis-Zhang-SH** [neon-bindings/neon#775]
Hi,

First of all, many thanks to this crate and appreciate your works, but I wonder is there anyway to build this crate in a macro way like crate structopt did, that would be convenient for us to convert a struct between Rust and JS.

**Comment by kjvalencik** [comment]
This is a neat idea and something that's been requested a [few](https://github.com/neon-bindings/neon/issues/556) times.

It's been implemented via serde in a community module [`neon-serde2`](https://crates.io/crates/neon-serde2). I think using `serde` is the [right approach](https://github.com/neon-bindings/neon/pull/701) for converting types, but I think functions and classes could benefit from proc macros like in [this proposal](https://github.com/neon-bindings/rfcs/pull/43).

I hope that answers your question. Let me know if there's anything else I can help with!
