### ISSUE TITLE
Broken [Neon fundamentals docs] link on README

### ISSUE THREAD

**Issue by mikeevmm** [neon-bindings/neon#798]
Hello,

The link in the [Docs section of the README](https://github.com/neon-bindings/neon#docs) pointing to the "Neon fundamentals docs" points to `https://neon-bindings.com/docs/intro` instead of `https://neon-bindings.com/docs/introduction`.

**Comment by kjvalencik** [comment]
Thanks! Fixed here: https://github.com/neon-bindings/website/pull/220
