### ISSUE TITLE
Cache context?

### ISSUE THREAD

**Issue by scientific-dev** [neon-bindings/neon#805]
I am a beginner in neonjs but i have a doubt i want to share a rust instance `Arc<T>` to the javascript so i wanted to create some sort of resource table like `Vec<Arc<T>>` where new instances are pushed and indexes are returned as id. So how can i store that `Vec<Arc<T>>` . I mean in rust i cannot put it in the body and if its within the exported function it's value will get dropped.

**Comment by kjvalencik** [comment]
`JsBox` allows wrapping Rust data in JavaScript objects to be managed by the garbage collector.

There are a couple of catches:
* You no longer have control over when the data will be dropped. The garbage collector may not free it for a long time. If you need tighter control, use an `Option` that you can replace with `None`.
* JavaScript allows aliasing pointers. For safety, Neon will only give shared `&` references. If mutability is required, a `RefCell` or similar type can be used.

https://docs.rs/neon/0.9.1/neon/types/struct.JsBox.html
https://docs.rs/neon/0.9.1/neon/context/trait.Context.html#method.boxed
