### ISSUE TITLE
How to receive one JS argument as JsBuffer ?

### ISSUE THREAD

**Issue by Pana** [neon-bindings/neon#821]
From js to rust how to receive one JS argument as JsBuffer ?
JsBuffer does not have one `value` method to retrieve the data as vec<u8>

**Comment by kjvalencik** [comment]
This uses the `Borrow` API in the current version of Neon (0.9).

```rust
fn buffer_to_vec(mut cx: FunctionContext) -> JsResult<JsUndefined> {
    let buffer = cx.argument::<JsArrayBuffer>(0)?;
    let data: Vec<u8> = cx.borrow(&buffer, |buf| buf.as_slice().to_vec());

    Ok(cx.undefined())
}
```

https://docs.rs/neon/0.9.1/neon/types/struct.BinaryData.html

However, this will be simplified in the upcoming Neon `0.10` with the `TypedArray` trait:
https://docs.rs/neon/0.10.0-alpha.2/neon/types/buffer/trait.TypedArray.html

```rust
use neon::types::buffer::TypedArray;

fn buffer_to_vec(mut cx: FunctionContext) -> JsResult<JsUndefined> {
    let data: Vec<u8> = cx.argument::<JsArrayBuffer>(0)?.as_slice(&cx).to_vec();

    Ok(cx.undefined())
}
```

**Comment by Pana** [comment]
Thanks very much
