### ISSUE TITLE
consider support TOML v1.0 for neon-cli

### ISSUE THREAD

**Issue by LongTengDao** [neon-bindings/neon#826]
TOML v0.5 and v1.0 had released for a long time, but the dependency `toml` of `neon-cli` still only support TOML v0.4.

<https://github.com/toml-lang/toml/blob/master/CHANGELOG.md>

Here are some alternative options in the community: <https://github.com/toml-lang/toml/wiki>

**Comment by kjvalencik** [comment]
Can you explain what you mean in more detail? The toml dependency in neon-cli is on 3.0.

**Comment by LongTengDao** [comment]
Hh, sorry, the config language TOML's name is same with the npm package `toml`'s name...

I mean, the npm package `toml` (which is the dependency of `neon-cli` now), its latest version `3.0.0` is published 3 years ago, and during these years, the config language TOML's version has been updated from `0.4` to `0.5` to `1.0` (with many new feature, see <https://github.com/toml-lang/toml/blob/master/CHANGELOG.md>).

There was no sign of that the npm package `toml` is still maintained and will support TOML spec version `1.0`.

So I suggest to use alternative package (which list in <https://github.com/toml-lang/toml/wiki>) to let `neon-cli` support `.toml` file which is under latest version TOML spec.

**Comment by kjvalencik** [comment]
`neon-cli` is only used for the legacy backend which is deprecated and will be removed in 1.0.

A PR would be welcome, but this issue will be obsolete soon.

**Comment by LongTengDao** [comment]
PR is very easy, but since it is about to be deprecated, it not worth the risk of breaking compatibility to make this kind of change.

Is there an alternative thing to replace the `neon-cli` in 1.0? Maybe we can update the dependency in that.

**Comment by kjvalencik** [comment]
@LongTengDao `neon-cli` is no longer necessary with the Node-API backend. `cargo` is sufficient to build node native modules directly.

We have a very simple `cargo-cp-artifact` wrapper for `cargo` that reads the metadata and copies the shared library to `index.node`, but it has zero dependencies and won't be necessary once `cargo` can specify output locations.
