### ISSUE TITLE
How to use argument rawValue in Rust function?

### ISSUE THREAD

**Issue by okbug** [neon-bindings/neon#827]
In: Rust:

```rust
fn fib(n: i32) -> i32{
    if n < 2 {
        return n;
    } else {
        return fib(n - 1) + fib(n - 2);
    }
}

fn js_fib(mut cx: FunctionContext ) -> JsResult<JsString> {
    let n = cx.argument::<JsNumber>(0)?;

}
```

In JavaScript:

```js
fib(3) // 3
```

I want to use argument `n` in Rust.But How?

**Comment by okbug** [comment]
And I hope It can write in docs demo,thanks.

**Comment by okbug** [comment]
Maybe I found the answer...

**Comment by kjvalencik** [comment]
``.value(&mut cx)` will return the type as a `f64`.

https://docs.rs/neon/0.9.1/neon/types/struct.JsNumber.html#method.value
