### ISSUE TITLE
Cargo fails to unpack neon-sys on Windows

### ISSUE THREAD

**Issue by CryZe** [neon-bindings/neon#83]
This is due to the immensely deep package hierarchy used causing super long paths like this:
![](http://puu.sh/oEXPL.png)

Windows can't handle these long paths and Cargo fails to unpack the crate for that reason.

**Comment by Programming4life** [comment]
Is there any workaround ?

**Comment by kjvalencik** [comment]
Closing because neon-sys is no longer the default backend and will be removed in the future.

Additionally this was likely fixed by changes to `npm`.
