### ISSUE TITLE
A possible memory leak in JsBox

### ISSUE THREAD

**Issue by bigteech** [neon-bindings/neon#830]
Hi, 
I was evaluating the code below,  and found  quite fast greatly leaking piece of code. 

```javascript
const os = require("os");
const { prepare } = (() => {
  return require(`../dist/lib.${os.platform()}.${os.arch()}`);
})();
let count = 0;
global.emit = () => {
  count --;
}
const heapUsed = () => (process.memoryUsage().rss / 1024 / 1024).toFixed(2);
function checkPrepare() {
  global.gc();
  console.log(`before rsz：`, heapUsed());
  for (let index = 0; index < 300000; index++) {
    prepare();
    count ++;
  }
  setTimeout(() => {
    global.gc();
    console.log('pending:', count);
    console.log(`after rsz：`, heapUsed());
  }, 30000);
}

checkPrepare();

```
```rust
use neon::prelude::*;

struct Foo(Vec<u8>);

impl Finalize for Foo {
    fn finalize<'a, C: Context<'a>>(self, cx: &mut C) {
        let global = cx.global();
        let emit = global
            .get(cx, "emit")
            .unwrap()
            .downcast::<JsFunction, _>(cx)
            .unwrap();

        let args = vec![
            cx.string("gc_point").upcast::<JsValue>(),
        ];

        emit.call(cx, global, args).unwrap();
    }
}

fn prepare(mut cx: FunctionContext) -> JsResult<JsBox<Foo>> {
    let vecu8: Vec<u8> = Vec::with_capacity(100000);
    Ok(cx.boxed(Foo(vecu8)))
}

#[neon::main]
fn main(mut cx: ModuleContext) -> NeonResult<()> {
    cx.export_function("prepare", prepare).unwrap();
    Ok(())
}

```
The function prepare preduce 300000 jsbox,  and force gc after 30000ms,  but even if all the jsbox has been dropped,  the rss still used  40Mb。
Here's the console log:
```text
before rsz： 19.96
pending: 0
after rsz： 61.89
```
But if I remove the jsbox like this:
```rust
fn prepare(mut cx: FunctionContext) -> JsResult<JsNull> {
    Ok(cx.null())
}
```
The memory can be free
```
before rsz： 20.08
pending: 300000
after rsz： 21.34
```
```

**Comment by kjvalencik** [comment]
Interesting find. I have a couple of observations and questions.

First, the memory being measured is v8 heap and not process memory. This means the size of the `Vec` should have no impact on growth.  Using a unit struct or smaller dataset may help get more iterations in a brief amount of time.

Next, removing the box doesn't just remove the box, but also the `Finalize` callback which is constructing a string and calling `global.emit`.

1. What versions of Neon and Node? OS?
2. In the version where `JsBox` is removed, what happens if you still call `emit`? (I.e., copy paste finalize into the `prepare` body).
3. If run for a long time does memory continue to grow or does it reach a limit?

GC in V8 does not remove everything, it may still keep things around, such as buffers. Performing a heap dump with Chrome dev tools a few times whole running and comparing can help determine if there's any object growth. It's possible the memory is from the buffer pool growing from having multiple `gc_point`.

Thanks!

**Comment by bigteech** [comment]
OS: CentOS Linux release 7.9.2009 (Core)
Node: v14.18.1
Neon: 0.9.1
rustc:  1.55.0 (c8dfcfe04 2021-09-06)

I replace the `process.memoryUsage().rss` by  `cat /proc/${process.pid}/status | grep VmRSS` to measure the memory used. and print the memeory used and the jsbox which waiting for gc。 I found  the v8 heap size change small, and the memory used  changed within a reasonable range。The only thing confuse me is that even if the scope of  function checkPrepare is end and all  the jsbox is gc totaly but the VmRSS is still used very much. 
```javascript
'use strict';

const os = require('os');
const child_process = require('child_process');
const { prepare } = (() => {
  return require(`./dist/lib.${os.platform()}.${os.arch()}`);
})();

const heapUsed = () =>
  child_process
    .execSync(`cat /proc/${process.pid}/status | grep VmRSS`)
    .toString().trim();

const v8heapTotal = () =>
  (process.memoryUsage().heapTotal / 1024 / 1024).toFixed(2);

function checkPrepare() {
  let boxCount = 0;
  global.emit = () => {
    boxCount--;
  };
  return new Promise(resolve => {
    global.gc();
    console.log('before', 'v8: ', v8heapTotal(), heapUsed(), 'pending:', boxCount);
    let count = 0;
    let groupCount = 0;
    const timer = setInterval(() => {
      if (groupCount > 60) {
        clearInterval(timer);
        setTimeout(() => {
          global.gc();
          console.log('the end:', 'v8: ', v8heapTotal(), heapUsed(), 'pending:', boxCount);
          resolve();
        }, 30000);
        return;
      }
      if (count > 10) {
        count = 0;
        global.gc();
        console.log(new Date(), 'v8: ', v8heapTotal(), heapUsed(), 'pending:', boxCount);
        groupCount++;
      }
      for (let index = 0; index < 70000; index++) {
        prepare();
        boxCount++;
      }
      count++;
    }, 100);
  });
}

checkPrepare().then(() => {
  console.log('do something else');
  for (let index = 0; index < 100000; index++) {
    JSON.parse(JSON.stringify({
      a: 1,
      b: 2,
      c: 3,
    }));
  }
  console.log('something end:', 'v8: ', v8heapTotal(), heapUsed());
  heapdump.writeSnapshot('/quanzheng/glue-hessian/sample.heapsnapshot');
  console.log(child_process
    .execSync(`cat /proc/${process.pid}/maps`)
    .toString().trim());
});
```
```rust
use neon::prelude::*;

struct Foo(Vec<u8>);

impl Finalize for Foo {
    fn finalize<'a, C: Context<'a>>(self, cx: &mut C) {
        let global = cx.global();
        let emit = global
            .get(cx, "emit")
            .unwrap()
            .downcast::<JsFunction, _>(cx)
            .unwrap();

        let args: Vec<Handle<JsValue>> = vec![
        ];

        emit.call(cx, global, args).unwrap();
    }
}


fn prepare(mut cx: FunctionContext) -> JsResult<JsNull> {
    let vecu8: Vec<u8> = Vec::with_capacity(10000);
    cx.boxed(Foo(vecu8));
    Ok(cx.null())
}

#[neon::main]
fn main(mut cx: ModuleContext) -> NeonResult<()> {
    cx.export_function("prepare", prepare).unwrap();
    Ok(())
}

```
Below is the output:
![image](https://user-images.githubusercontent.com/16490211/143418027-8e53e6cd-82af-44b6-9b91-abbf57dfe90c.png)
I found 
Below is v8 heap dump:
![image](https://user-images.githubusercontent.com/16490211/143423146-261bfbba-23fb-4c83-939f-64ee8c6949be.png)
Below is maps:
![image](https://user-images.githubusercontent.com/16490211/143423229-c32323f8-782f-4db3-bca4-6f235bbf305e.png)

**Comment by bigteech** [comment]
OS: CentOS Linux release 7.9.2009 (Core)
Node: v14.18.1
Neon: 0.9.1
rustc:  1.55.0 (c8dfcfe04 2021-09-06)

I replace the `process.memoryUsage().rss` with  `cat /proc/${process.pid}/status | grep VmRSS` to measure the memory used. and print the used memeory and the jsbox which waiting for gc。 I found  the v8 heap size change small, and the used memory  changed within a reasonable range。The only thing confuse me is that even if the scope of  function checkPrepare is end and all  the jsbox is gc totaly but the VmRSS is still used very much. 
```javascript
'use strict';

const os = require('os');
const child_process = require('child_process');
const { prepare } = (() => {
  return require(`./dist/lib.${os.platform()}.${os.arch()}`);
})();

const heapUsed = () =>
  child_process
    .execSync(`cat /proc/${process.pid}/status | grep VmRSS`)
    .toString().trim();

const v8heapTotal = () =>
  (process.memoryUsage().heapTotal / 1024 / 1024).toFixed(2);

function checkPrepare() {
  let boxCount = 0;
  global.emit = () => {
    boxCount--;
  };
  return new Promise(resolve => {
    global.gc();
    console.log('before', 'v8: ', v8heapTotal(), heapUsed(), 'pending:', boxCount);
    let count = 0;
    let groupCount = 0;
    const timer = setInterval(() => {
      if (groupCount > 60) {
        clearInterval(timer);
        setTimeout(() => {
          global.gc();
          console.log('the end:', 'v8: ', v8heapTotal(), heapUsed(), 'pending:', boxCount);
          resolve();
        }, 30000);
        return;
      }
      if (count > 10) {
        count = 0;
        global.gc();
        console.log(new Date(), 'v8: ', v8heapTotal(), heapUsed(), 'pending:', boxCount);
        groupCount++;
      }
      for (let index = 0; index < 70000; index++) {
        prepare();
        boxCount++;
      }
      count++;
    }, 100);
  });
}

checkPrepare().then(() => {
  console.log('do something else');
  for (let index = 0; index < 100000; index++) {
    JSON.parse(JSON.stringify({
      a: 1,
      b: 2,
      c: 3,
    }));
  }
  console.log('something end:', 'v8: ', v8heapTotal(), heapUsed());
  heapdump.writeSnapshot('/quanzheng/glue-hessian/sample.heapsnapshot');
  console.log(child_process
    .execSync(`cat /proc/${process.pid}/maps`)
    .toString().trim());
});
```
```rust
use neon::prelude::*;

struct Foo(Vec<u8>);

impl Finalize for Foo {
    fn finalize<'a, C: Context<'a>>(self, cx: &mut C) {
        let global = cx.global();
        let emit = global
            .get(cx, "emit")
            .unwrap()
            .downcast::<JsFunction, _>(cx)
            .unwrap();

        let args: Vec<Handle<JsValue>> = vec![
        ];

        emit.call(cx, global, args).unwrap();
    }
}


fn prepare(mut cx: FunctionContext) -> JsResult<JsNull> {
    let vecu8: Vec<u8> = Vec::with_capacity(10000);
    cx.boxed(Foo(vecu8));
    Ok(cx.null())
}

#[neon::main]
fn main(mut cx: ModuleContext) -> NeonResult<()> {
    cx.export_function("prepare", prepare).unwrap();
    Ok(())
}

```
Below is the output:
![image](https://user-images.githubusercontent.com/16490211/143418027-8e53e6cd-82af-44b6-9b91-abbf57dfe90c.png)
I found 
Below is v8 heap dump:
![image](https://user-images.githubusercontent.com/16490211/143423146-261bfbba-23fb-4c83-939f-64ee8c6949be.png)
Below is maps:

**Comment by kjvalencik** [comment]
Thank you for the incredible investigation!

Node is fairly greedy with memory allocations. It doesn't quickly free memory back to the OS even after the objects have been garbage collected. Instead it maintains pools for its own use to make future allocations faster.

My guess is if the heap size isn't growing that is what is happening. What usually happens in this situation is memory will continue to grow for awhile, but eventually V8 will decide it doesn't need the memory and free it back. I've found it difficult to keep Node.js consistently under 100MB.

Let me know if you are seeing unbounded growth, especially if it reaches a couple hundred MB or more and I will investigate.

**Comment by bigteech** [comment]
> Thank you for the incredible investigation!
> 
> Node is fairly greedy with memory allocations. It doesn't quickly free memory back to the OS even after the objects have been garbage collected. Instead it maintains pools for its own use to make future allocations faster.
> 
> My guess is if the heap size isn't growing that is what is happening. What usually happens in this situation is memory will continue to grow for awhile, but eventually V8 will decide it doesn't need the memory and free it back. I've found it difficult to keep Node.js consistently under 100MB.
> 
> Let me know if you are seeing unbounded growth, especially if it reaches a couple hundred MB or more and I will investigate.

Thanks you very much!  I learned a lot from your replay，it is very useful. if I find unbounded growth, I will open another issue.
