### ISSUE TITLE
linking with `cc` failed: exit status: 1

### ISSUE THREAD

**Issue by schizobulia** [neon-bindings/neon#842]
```
os: mac m1

target: aarch64-apple-darwin

neon: 0.9.1

Have tried: xcode-select --install

shell: npm run build
```

**Comment by kjvalencik** [comment]
The legacy backend is not supported for M1. It's possible to get it working if the tool chain is configured properly, but it's not documented.

See the [Migration Guide](https://github.com/neon-bindings/neon/blob/main/MIGRATION_GUIDE.md) or bootstrap a new project with:

```
npm init neon my-project
```

**Comment by schizobulia** [comment]
> M1 不支持旧后端。如果工具链配置正确，则可以使其正常工作，但未记录在案。
> 
> 请参阅[迁移指南](https://github.com/neon-bindings/neon/blob/main/MIGRATION_GUIDE.md)或使用以下命令引导新项目：
> 
> ```
> npm init neon my-project
> ```
```
use npm init neon my-project
```
That's a mistake too

**Comment by schizobulia** [comment]
```
brew install cmake 
```
Yes, thank you very much @kjvalencik

**Comment by kjvalencik** [comment]
@schizobulia That looks like a problem with a Rust dependency not related to Neon.

Can you make sure that your terminal, node, and rust are all using the aarch64 versions?

**Comment by schizobulia** [comment]
Yes it seems to be a problem with this code。 https://github.com/DaGenix/rust-crypto/blob/master/examples/symmetriccipher.rs

**Comment by kjvalencik** [comment]
@schizobulia Can you verify that your Node install is aarch64? Neon is not part of the compilation process and shouldn't cause this problem. However, if you are using a x86_64 Node process, it may be causing the dependency to try to compile for the wrong architecture.

**Comment by schizobulia** [comment]
@kjvalencik Sorry, I messed up my environment using NVM. Switch to Node V16.13.1。everything is normal。

Thank you very much!

**Comment by kjvalencik** [comment]
No problem! I'm glad you fixed it.
