### ISSUE TITLE
How to pass JavaScript callback to tokio server?

### ISSUE THREAD

**Issue by owenthereal** [neon-bindings/neon#848]
Hello, I'm new to Rust. Please bear with me for the question 🙂

I would like to run a gRPC server in Rust via [tonic](https://github.com/hyperium/tonic) (essentially a tokio server) and when there is a request, the server calls the JavaScript callback to process the request and respond with the result from the JavaScript callback. But I'm stuck with not knowing how to pass the JavaScript callback to the async tokio server properly. Please help. 

This is my Rust file (see inline comments):

```rust
use neon::prelude::*;
use once_cell::sync::OnceCell;
use tokio::runtime::Runtime;
use tonic::{transport::Server, Request, Response, Status};
use grpc::function_server::{Function, FunctionServer};
use grpc::{ProcessRecordRequest, ProcessRecordResponse};

pub mod grpc {
    tonic::include_proto!("grpc_test");
}

fn runtime<'a, C: Context<'a>>(cx: &mut C) -> NeonResult<&'static Runtime> {
    static RUNTIME: OnceCell<Runtime> = OnceCell::new();

    RUNTIME.get_or_try_init(|| Runtime::new().or_else(|err| cx.throw_error(err.to_string())))
}

fn start_func(mut cx: FunctionContext) -> JsResult<JsString> {
    let callback = cx.argument::<JsFunction>(0)?.root(&mut cx);

    // I would like to pass this callback into FunctionImpl and call it when there is a request
    // see CALL_CALLBACK below

    let addr = "[::1]:50051".parse().unwrap();
    let func = FunctionImpl { };

    let rt = runtime(&mut cx)?;
    let result = rt.block_on(
        Server::builder()
            .add_service(FunctionServer::new(func))
            .serve(addr),
    );

    Ok(cx.string("hello node"))
}

pub struct FunctionImpl {
}

#[tonic::async_trait]
impl Function for FunctionImpl {
    async fn process(
        &self,
        request: Request<ProcessRecordRequest>,
    ) -> Result<Response<ProcessRecordResponse>, Status> {
        let records = request.into_inner().records;

        // CALL_CALLBACK here
        // I would like to call the JavaScript callback here and return its result as response 

        let reply = grpc::ProcessRecordResponse { records: records };

        Ok(Response::new(reply))
    }
}

#[neon::main]
fn main(mut cx: ModuleContext) -> NeonResult<()> {
    cx.export_function("startFunc", start_func)?;
    Ok(())
}

```

This is my js file:

```js
"use strict";

const {startFunc} = require(".");

startFunc(function(records) {
    // process record and return it
    return records
})
```

Thank you in advance for any help! Cheers!

**Comment by kjvalencik** [comment]
@owenthereal `Context` and `Handle` / JavaScript `Value` are neither `Send` or `Sync` and cannot be used across threads. This is for two safety reasons:

1. References to JavaScript values may become invalid if they are garbage collected after control is returned to JavaScript from Rust
2. It's not valid / possible to call / access JavaScript from anywhere except the main JavaScript thread.

The solution to the first problem is [`Root`](https://docs.rs/neon/latest/neon/handle/struct.Root.html). `Root` create a persistent handle to a JavaScript object (e.g., `JsFunction`) and prevent it from being garbage collected. These types *are* `Send` and `Sync`.

However, a `Root` can not be used directly. It's only a handle. In order to access the value (e.g., call the function), it requires execution on the JavaScript main thread. This is where [`Channel`](https://docs.rs/neon/latest/neon/event/struct.Channel.html) comes in.

`Channel` allows sending a closure to the JavaScript main thread for execution. In your case, you _also_ want to return some data from the JavaScript main thread back to the tokio thread.

The prerelease of Neon 0.10 includes a [`JoinHandle`](https://docs.rs/neon/0.10.0-alpha.3/neon/event/struct.JoinHandle.html) that is returned from `Channel::send`. A `JoinHandle` can be used to block the current thread and get the return value from the closure.

```rust
let f = cx.argument::<JsFunction>(0)?.root(&mut cx);
let channel = cx.channel();

std::thread::spawn(move || {
    let value = channel
        .send(move |mut cx| {
            // Note: `to_inner(&mut cx)` can be used if `f` needs to be used multiple times
            // and is hidden behind a `&` reference (e.g., with an `Arc<Root<_>>`.
            let f = f.into_inner(&mut cx);
            let this = cx.undefined();
            let value: Handle<JsString> = f.call(&mut cx, this, [])?;
            
            Ok(value.value(&mut cx))
        })
        .join()
        .unwrap();
        
    println!("Value: {}", value);
});
```

However, this has a couple of problems. First, it's not available in current stable `0.9`, but that's not that big of a deal since `0.10` will be released soon. The bigger problem is that it *blocks* the current thread while waiting for execution. This isn't ideal for an async thread pool. Instead, we want to asynchronously wait for it to run.

I have a proposal I'm working on to build this into Neon, but in the meantime, it's possible to use a oneshot async channel. For example, [`tokio::sync::oneshot::channel`](https://docs.rs/tokio/1.15.0/tokio/sync/oneshot/fn.channel.html).

```rust
let f = cx.argument::<JsFunction>(0)?.root(&mut cx);
let channel = cx.channel();

tokio::spawn(async move {
    let (sender, receiver) = tokio::sync::oneshot::channel();

    channel.send(move |mut cx| {
        let f = f.into_inner(&mut cx);
        let this = cx.undefined();
        let value: Handle<JsString> = f.call(&mut cx, this, [])?;

        sender.send(value.value(&mut cx));
    });
    
    let value = receiver.recv().await.unwrap();

    println!("Value: {}", value);
});
```

Keep in mind, in both cases, the value returned back to tokio cannot be a JavaScript value (unless wrapped in a `Root`) since it must be `Send` + `Sync`.

**Comment by owenthereal** [comment]
@kjvalencik:

Thank you for the detailed reply! This does give me some direction! But I would still need a bit more hand-holding. I published my example [here](https://github.com/owenthereal/neon-tonic-example) so that we could discuss it more concretely.

I created [this PR](https://github.com/owenthereal/neon-tonic-example/pull/1/files) to make use of [Channel](https://docs.rs/neon/latest/neon/event/struct.Channel.html) and [tokio::sync::oneshot::channel](https://docs.rs/tokio/1.15.0/tokio/sync/oneshot/fn.channel.html) as you suggested. But I'm having trouble [passing the `JsFunction` root](https://github.com/owenthereal/neon-tonic-example/pull/1/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R10) into the `Function` struct so that I can use it [in the struct's async method](https://github.com/owenthereal/neon-tonic-example/pull/1/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R48). I ran into all kinds of compilation errors that are related to moving the ownership of `JsFunction` root object etc.

Would you be able to help me to get this example to compile and run? Feel free to create PR to that repo and such if that helps with communication. Thanks in advance. This example might be a source of inspiration for more tokio server with neon-bindings examples in https://github.com/neon-bindings/examples. I'm more than happy to contribute to more examples after we get this to work 🙂

**Comment by kjvalencik** [comment]
This is based on the tonic `helloworld` example:

```rust
/// lib.rs
use std::cell::RefCell;
use std::sync::Arc;

use futures::stream::AbortHandle;
use once_cell::sync::OnceCell;
use neon::prelude::*;
use tokio::runtime::Runtime;
use tonic::{transport::Server, Request, Response, Status};

use hello_world::greeter_server::{Greeter, GreeterServer};
use hello_world::{HelloReply, HelloRequest};

fn runtime<'a, C: Context<'a>>(cx: &mut C) -> NeonResult<&'static Runtime> {
    static RUNTIME: OnceCell<Runtime> = OnceCell::new();

    RUNTIME
        .get_or_try_init(|| Runtime::new())
        .or_else(|err| cx.throw_error(err.to_string()))
}

pub mod hello_world {
    tonic::include_proto!("helloworld");
}

pub struct MyGreeter {
    channel: Channel,
    greet: Arc<Root<JsFunction>>,
}

#[tonic::async_trait]
impl Greeter for MyGreeter {
    async fn say_hello(
        &self,
        request: Request<HelloRequest>,
    ) -> Result<Response<HelloReply>, Status> {
        println!("Got a request from {:?}", request.remote_addr());

        let request = request.into_inner();
        let greet = self.greet.clone();
        let (tx, rx) = futures::channel::oneshot::channel();

        let _ = self.channel.try_send(move |mut cx| {
            let this = cx.undefined();
            let name = cx.string(request.name);
            let greeting = greet
                .to_inner(&mut cx)
                .call(&mut cx, this, [name])?
                .downcast_or_throw::<JsString, _>(&mut cx)?
                .value(&mut cx);

            let _ = tx.send(greeting);

            Ok(())
        });

        let message = rx.await
            .map_err(|_| Status::internal("Failed to call JavaScript"))?;

        let reply = hello_world::HelloReply {
            message,
        };

        Ok(Response::new(reply))
    }
}

struct MyServer {
    handle: RefCell<Option<AbortHandle>>,
}

impl Finalize for MyServer {}

fn new_server(mut cx: FunctionContext) -> JsResult<JsBox<MyServer>> {
    let addr = "[::1]:50051".parse().unwrap();
    let channel = Channel::new(&mut cx);
    let greet = cx.argument::<JsFunction>(0)?.root(&mut cx);
    let greeter = MyGreeter {
        channel,
        greet: Arc::new(greet),
    };

    println!("GreeterServer listening on {}", addr);

    let serve = Server::builder()
        .add_service(GreeterServer::new(greeter))
        .serve(addr);

    let (abortable, handle) = futures::future::abortable(serve);

    runtime(&mut cx)?.spawn(abortable);

    let server = MyServer { handle: RefCell::new(Some(handle)) };

    Ok(cx.boxed(server))
}

fn close_server(mut cx: FunctionContext) -> JsResult<JsUndefined> {
    let server = cx.argument::<JsBox<MyServer>>(0)?;

    *server.handle.borrow_mut() = None;

    Ok(cx.undefined())
}

#[neon::main]
fn main(mut cx: ModuleContext) -> NeonResult<()> {
    cx.export_function("new_server", new_server)?;
    cx.export_function("close_server", close_server)?;
    Ok(())
}
```

I expect the bits you are most interested in are `struct MyGreeter` and `say_hello`.

Usage:
```
> const server = require('.').new_server(name => `Hello, ${name}!`);
GreeterServer listening on [::1]:50051
Got a request from Some([::1]:56227)
```

From a client:
```
RESPONSE=Response { metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Sat, 29 Jan 2022 21:48:05 GMT", "grpc-status": "0"} }, message: HelloReply { message: "Hello, Tonic!" }, extensions: Extensions }
```

If you don't ever need to stop the server, you can ignore the `MyServer` implementation with the `RefCell<Option<AbortHandle>>`. That lets the server be stopped if either the handle is garbage collected or if you call `close_server(handle)` with the handle returned from `new_server`.

Sorry that it's pretty messy. It was written hastily. A lot of the verbosity will get cleaned up in `0.10`.

**Comment by demurgos** [comment]
If you want more examples, I used Neon to progressively migrate a server from Node to Rust from the inside.

I had a similar use case with a server wrapped in Neon: here are the main pieces:
- [tokio runtime](https://gitlab.com/eternaltwin/etwin/-/blob/master/packages/native/native/src/tokio_runtime.rs)
- [Request handler](https://gitlab.com/eternaltwin/etwin/-/blob/master/packages/native/native/src/rest.rs#L170)
- [Neon helpers](https://gitlab.com/eternaltwin/etwin/-/blob/master/packages/native/native/src/neon_helpers.rs#L67)

**Comment by kjvalencik** [comment]
@demurgos That's really cool! Thanks for sharing!

**Comment by owenthereal** [comment]
@kjvalencik & @demurgos Thank you! I got it to work by copying your examples: https://github.com/owenthereal/neon-tonic-example/blob/master/src/lib.rs 🎉
