### ISSUE TITLE
[Enhancement] Object::call_method

### ISSUE THREAD

**Issue by jrose-signal** [neon-bindings/neon#873]
libsignal-client has a pretty ubiquitous helper `call_method`:

```rust
/// A convenience for calling a method on an object.
///
/// Equivalent to calling `get`, downcasting to a function, and then using `call`.
pub fn call_method<'a>(
    cx: &mut impl Context<'a>,
    this: Handle<'a, impl Object>,
    method_name: &str,
    args: impl AsRef<[Handle<'a, JsValue>]>,
) -> JsResult<'a, JsValue> {
    let method: Handle<JsFunction> = this.get(cx, method_name)?;
    method.call(cx, this, args)
}
```

This would be a useful convenience to have on Object, though whether it should be built on the low-level `call` or the high-level `call_with` is an open question. (I suppose I could have put ours on an ObjectExt trait rather than making it a top-level function too.)

**Comment by kjvalencik** [comment]
@jrose-signal Great idea! I like how it uses the `Object` also as the `this` variable to mimic how `object.method()` would work in JavaScript.

I think with addition [call builders](https://github.com/neon-bindings/neon/blob/main/MIGRATION_GUIDE_0.10.md#object-property-access-is-generic) in 0.10, it would be good to also have a `call_with`.

```rust
trait Object {
    fn call_with<'a, C, K>(&self, cx: &mut C, method: K) -> NeonResult<CallOptions<'a>>
    where
        C: Context<'a>,
        K: PropertyKey,
    {
        self.get::<JsFunction, _, _>(cx, method)?.call_with(cx).this(self)
    }
}
```

**Comment by dherman** [comment]
Totally agree there's a missing convenience here! I wonder if we might only want the higher-level `call_with` API here, and not the lower-level `call_method`, since this is just a convenience method on `Object`. How about we start with that one and get some usage experience, and from there we can see if we discover additional use cases for the other one?
