### ISSUE TITLE
Is it possible to call async functions? If yes how? 

### ISSUE THREAD

**Issue by weezy20** [neon-bindings/neon#876]
I am using a rust crate that requires the use of async functions, and so my main function looks like this: 
```rust
#[neon::main]
fn main(mut cx: ModuleContext) -> NeonResult<()> {
    cx.export_function("async_fn", async_fn)?;
    Ok(())
}

```
I would like to `.await` on the `async_fn`, what is the way to achieve this?

**Comment by kjvalencik** [comment]
There is a [proposal to simplify](https://github.com/neon-bindings/rfcs/pull/46), but it currently requires some boilerplate.

See the [`tokio-fetch`](https://github.com/neon-bindings/examples/tree/main/examples/tokio-fetch) example for more details.

If it's acceptable to block the JavaScript main thread while awaiting, it can be significantly simplified by using [`block_on`](https://docs.rs/tokio/latest/tokio/runtime/struct.Handle.html#method.block_on) to synchronously block until the `Future` completes.
