### ISSUE TITLE
[Question] How to use TypedArray as a result type

### ISSUE THREAD

**Issue by Pruxis** [neon-bindings/neon#882]
Sorry to be utilising an issue to ask a question, but I've been having a really bad time to figure out how to use JsResult<TypedArray<u8>> for example

``` rust
fn sample(mut cx: FunctionContext) -> JsResult<JsTypedArray<f32>> {
    let arr = Vec::<f32>::new();
    Ok(arr)
}
```

However this results in a type mismatch which I've had some trouble dealing with:
```
expected struct `neon::handle::Handle`, found struct `std::vec::Vec`
```

Anyone knows how to utilise this?

**Comment by kjvalencik** [comment]
There is not currently a good way to create a `JsTypedArray` *from* Rust. The workaround is to return a `JsArrayBuffer` and wrap it in a typed array in JavaScript.

```rust
use neon::{prelude::*, types::buffer::TypedArray};

fn example(mut cx: FunctionContext) -> JsResult<JsArrayBuffer> {
    let data: Vec<i32> = vec![0, 1, 2, 3];
    let data: &[u8] = bytemuck::cast_slice(&data);
    let len = data.len().try_into().unwrap();
    let mut ab = JsArrayBuffer::new(&mut cx, len)?;

    ab.as_mut_slice(&mut cx).copy_from_slice(data);

    Ok(ab)
}

#[neon::main]
fn main(mut cx: ModuleContext) -> NeonResult<()> {
    cx.export_function("example", example)?;
    Ok(())
}
```

On the JavaScript side:

```js
const addon = require(".");

function example() {
    return new Int32Array(addon.example());
}
```

There are a few other ways to do this, but they all follow the same general idea.

**Comment by Pruxis** [comment]
Hey @kjvalencik thanks a lot for this 👍 
I was so convinced that I had to make a TypedArray while this was also an approach.

**Comment by kjvalencik** [comment]
It would be great to support creating TypedArray directly, but that will probably wait until Node supports it in [Node-API](https://nodejs.org/api/n-api.html), since Neon wouldn't be doing anything different than a user's Neon code:

```rust
let view = cx
    .global()
    .get::<JsFunction, _>(&mut cx, "Int32Array")?
    .construct_with(&cx)
    .arg(cx.array_buffer(1024))
    .apply::<JsTypedArray<i32>, _>(&mut cx)?;
```
