### ISSUE TITLE
Not Support Apple M1?

### ISSUE THREAD

**Issue by southorange1228** [neon-bindings/neon#892]
I try to run `hello world` and get some error.
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/32590310/163909497-539fde37-5de2-438f-8f5d-cd869f6e6117.png">

**Comment by kjvalencik** [comment]
Neon supports M1. From this error message, it appears like the Neon module was correctly built for M1, but `test.js` is attempting to load it in Node compiled for x86_64. Neon modules are portable across Node versions, but not across OS or processor architecture.

```
node -e 'console.log(process.arch)'
```

I suggest uninstalling Node and re-installing the version compiled for M1.
