### ISSUE TITLE
Bun support issue

### ISSUE THREAD

**Issue by xHyroM** [neon-bindings/neon#915]
I'm getting this:
![image](https://user-images.githubusercontent.com/56601352/178115969-d538e56a-885a-4ff3-bb08-36205000f5af.png)

**Comment by kjvalencik** [comment]
This fixed by https://github.com/neon-bindings/neon/pull/914 on main but not published.

It moves missing symbol errors from load time to usage. Missing symbols after that fix need to be added to bun.

**Comment by xHyroM** [comment]
> This was fixed by #914 on main but not published.
> 
> It moves missing symbol errors from load time to usage. Missing symbols after that fix need to be added to bun.

How can I install unpublished version?

**Comment by kjvalencik** [comment]
https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories
