### ISSUE TITLE
How to convert Vec<Enum> to Array(Object)?

### ISSUE THREAD

**Issue by southorange1228** [neon-bindings/neon#926]
Just like it. How to convert Rust(Vec<Statement>) to JS(Array(Object))？

I can't find any example on the website.

Could you provider a example? And i think the docs  which is to simple for me.I think if it can provider more exmaples and it can be better! Thanks.

**Comment by kjvalencik** [comment]
This included in the arrays section of the docs.

https://neon-bindings.com/docs/arrays#converting-a-rust-vector-to-an-array

**Comment by southorange1228** [comment]
> This included in the arrays section of the docs.
> 
> https://neon-bindings.com/docs/arrays#converting-a-rust-vector-to-an-array

In fact, i want to know `JsObject` only call `set` method for eveny field? Is there any simple method to convert?

**Comment by kjvalencik** [comment]
There is the unofficial [`neon-serde2`](https://crates.io/crates/neon-serde2) crate that will generate the code, but that's the only way built in.
