### ISSUE TITLE
Support for UTF-16 strings

### ISSUE THREAD

**Issue by dnaka91** [neon-bindings/neon#943]
I'm using Neon to build a VS Code extension, and I am listening for editing events on open text editors. While doing so, I realized that JavaScript strings are represented as UTF-16.

Usually that's not an issue, because Neon uses the NAPI APIs that auto-convert to UTF-8 and the string can be used as usual in Rust.

Now these editing events include line and character positions, and sadly those character positions are not actual char positions but UTF-16 byte positions. So I'll have to adjust them to UTF-8 lengths to work with them in Rust, which I currently do in JavaScript/TypeScript.

I saw that the NAPI has `napi_get_value_string_utf16`, so it would be possible to get the UTF-16 variant of the string, and I could do all these conversions directly in Rust.

The standard library doesn't have any specific UTF-16 string type, but the [`widestring`](https://docs.rs/widestring/latest/widestring) crate seems very popular and has what would be needed for this. Probably preferred to hide this behind a feature flag (although, the crate has zero deps).

---

It would be great if we can add APIs for the UTF-16 string variants of this. Maybe not even necessary to add `widestring`, and could possibly just expose a `to_string_utf16()` on the `JsString` type that returns a `Vec<u16>` 🤔. The `widestring` variant would then return a [`Utf16String`](https://docs.rs/widestring/latest/widestring/utfstring/struct.Utf16String.html).

What do you think about this idea? I could prepare a PR for this, if there is interest to extend the APIs a bit.

**Comment by kjvalencik** [comment]
This seems like a great addition. I think I somewhat favor a version that returns `Vec<u16>` to defer a decision on what crate or representation it should be.

Neon could document that the value is guaranteed to be valid UTF-8, allowing a user to feel confident about using `unsafe { widestring::utfstring::Utf16String::from_vec_unchecked(val) }`.

This is a small enough addition that it does not require a RFC. What do you think of the name `JsString::to_utf16`?

A PR with an implementation would be greatly appreciated!

**Comment by dnaka91** [comment]
Thanks, will get started on a PR tomorrow.

I tend towards the `Vec<u16>` for the same reason. Especially, UTF-16 is probably niche enough for the average Rust project, to not pull in an extra dependency. And of course, can still be added later in case of high demand.

`JsString::to_utf16` is a good naming, I believe. The return value is a `Vec<u16>`, so it matches with the standard library naming.
