### ISSUE TITLE
Bumping MSRV from `1.53` to `1.56`

### ISSUE THREAD

**Issue by dnaka91** [neon-bindings/neon#946]
I would like to discuss to eventually bump the MSRV of neon to `1.56`, as part of the 1.0 release. I used `cargo-msrv` to find out that the current MSRV is `1.53`. This would allow for 2 specific changes (that come to mind now, maybe there are some convenient APIs that we'd get access to):

- Cargo.toml's `rust-version` setting, to signal the minimum version.
  - Makes it easier for users to find out the current MSRV, and helps the tools in detecting the version as well.
  - Not sure about this, but may help clippy to avoid lints, where the change would require a higher MSRV.
- Change the Rust edition to `2021`.
  - Nothing too specific about this version, as I haven't had a deep look in the source code yet, but may allow doing some code simplifications here and there.
  - More than actual language features, likely to signal that the project stays up-to-date with recent Rust versions.

The bump is totally optional. I personally always use the latest Rust compiler, but I understand that's not what everyone does (or can).

**Comment by kjvalencik** [comment]
We've discussed, but never formally decided how we will handle MSRV other than, it must *at least* run on current stable.

If we decide to pick a MSRV, I'd lean towards 1.65 since there are some neat things we could do with GATs.

@dherman any thoughts on this?

**Comment by kjvalencik** [comment]
Closing this in favor of https://github.com/neon-bindings/neon/issues/738

Latest Neon currently requires 1.65.
