### ISSUE TITLE
How to get the installation path?

### ISSUE THREAD

**Issue by patrick91** [neon-bindings/neon#947]
Hi there! 

Is there a way to get the installation path for a module? 
I'm trying to use minijinja and would love to ship some default templates with my library. I can try to find the template from `node_modules/my_lib/...`, but I'm not sure if I should hard-code them or not.

Is there a way to get the installation path from neon?

**Comment by kjvalencik** [comment]
You can [`require.resolve`](https://nodejs.org/api/modules.html#requireresolverequest-options).
