### ISSUE TITLE
Neon modules for Electron apps targeting Windows may require privileges

### ISSUE THREAD

**Issue by JohnScience** [neon-bindings/neon#956]
Hi, I've created a [`neon_example_cant_find`](https://github.com/JohnScience/neon_example_cant_find) repo that shows the problem.

I have a project that currently uses [`electron-forge`](https://www.electronforge.io/) and it was fine until I tried using file system from the [`neon`](https://crates.io/crates/neon) module for Node.js written in Rust. Now I realize that `electron-forge` [lacks options](https://js.electronforge.io/interfaces/_electron_forge_maker_squirrel.InternalOptions.Options.html) for elevating execution level and I wonder if the best solution is to replace `electron-forge` with another tool for packaging and distributing my Electron app.

**Comment by kjvalencik** [comment]
The example code doesn't seem like it should work. It returns early if `app_data_path` already exists. If it does not exist, it pushes an extra directory and tries to create it.

The `create_dir` function is *not* recursive, which means this will never work. If you add an extra `create_dir` before the `for` loop, this code will run correctly.

Do you need administrative permissions? It shouldn't be necessary to read/write files.

**Comment by JohnScience** [comment]
This was embarrassing. Thank you
