### ISSUE TITLE
Return jsobject or undefined

### ISSUE THREAD

**Issue by stevenliebregt** [neon-bindings/neon#965]
Hi, I'm trying to create a function, that based on some parameter returns either a JSObject or undefined/null.

The returntype I have is `JsResult<JsObject>` because I can't find a way to do it optional.

Is this supported?

**Comment by kjvalencik** [comment]
Yes, it is! This is documented in the [type hierarchy](https://docs.rs/neon/1.0.0-alpha.2/neon/types/index.html). The `JsValue` type is a super type of all types. You can `upcast()` to a `JsValue` from any type to unify two different types.

```rust
fn object_or_undefined(mut cx: FunctionContext) -> JsResult<JsValue> {
    let create_object = cx.argument::<JsBoolean>(0)?.value(&mut cx);

    if create_object {
        return Ok(cx.empty_object().upcast());
    }
    
    Ok(cx.undefined().upcast())
}
```

**Comment by stevenliebregt** [comment]
Ah that makes sense, must've missed that, thanks a lot!
