### ISSUE TITLE
Slack invite link is dead in README

### ISSUE THREAD

**Issue by olalonde** [neon-bindings/neon#967]
Slack invite link is dead in README

**Comment by dherman** [comment]
Thanks for the report, @olalonde, and sorry you weren't able to get in! I've created a [new permanent link](https://join.slack.com/t/rust-bindings/shared_invite/zt-1pl5s83xe-ZvXyrzL8vuUmijU~7yiEcg) that I believe should work. Can you give it a try and see if you're able to get in? Thanks!

**Comment by dherman** [comment]
Noting for the record: I found out from bazelbuild/bazel-website#251 that Slack now supports permanent invite links without the need for third-party automation, and from a web search I found these instructions for [configuring public Slack instances with permanent invite links](https://getlowdown.com/how-to-create-a-slack-community-and-landing-page-in-one-hour/).
