### ISSUE TITLE
Implement Debug trait

### ISSUE THREAD

**Issue by tomdale** [neon-bindings/neon#99]
Neon structs tend not to implement the `Debug` trait, so they can't be logged easily with `println!`, and it is not possible to derive the `Debug` trait outside the `neon` crate.

It would be nice to implement this trait to help with debugging. Inspecting the object may inherently cause some interaction with the JavaScript VM, but at least printing the name of the struct would be a nice start.

**Comment by winding-lines** [comment]
I just ran into this while exploring callbacks.

```
   Compiling neotify v0.1.0 ()
src/lib.rs:23:44: 23:50 error: no method named `expect` found for type `std::result::Result<neon::mem::Handle<'_, neon::js::JsValue>, neon::vm::Throw>` in the current scope
src/lib.rs:23         callback.call(scope,  this_, args).expect("invoke js callback");
                                                         ^~~~~~
src/lib.rs:23:44: 23:50 note: the method `expect` exists but the following trait bounds were not satisfied: `neon::vm::Throw : std::fmt::Debug`
error: aborting due to previous error
```

**Comment by KenanSulayman** [comment]
@winding-lines `try!(callback.call(scope,  this_, args))` maybe?

**Comment by kjvalencik** [comment]
We would still like this, but https://github.com/neon-bindings/neon/issues/269 duplicates this issue, but contains more details. Closing.
